import type { GuideInfo } from "./guides";

export const GUIDES_G6: ReadonlyArray<GuideInfo> = [
  {
    slug: "hiking-trails-guide",
    title: "Hiking in Cyprus — Troodos, Akamas, and Coastal Trails",
    description:
      "A practical guide to the best hiking in Cyprus — from the Troodos mountain circuit trails to the Akamas Peninsula and coastal paths — with difficulty ratings, trailhead logistics, and seasonal advice.",
    sections: [
      {
        heading: "Troodos National Park: Atalante, Artemis, and Caledonian Falls",
        body: "The Troodos massif — Cyprus's highest range, topping out at Mount Olympus at 1,952m — hosts the island's most developed trail network. The Atalante Trail is the flagship: a 14km circular route that circles Mount Olympus through pine forest and cedar stands, starting and ending at the Troodos resort area. It's rated medium difficulty, with 400m of cumulative elevation change, and takes 4–5 hours at a relaxed pace. The Artemis Trail at 9km is a shorter circular at high elevation (1,700–1,952m) with panoramic views of both coasts on clear days — one of the best two-hour walks in the island. The Caledonian Falls trail is a 3km linear path descending through waterfalls and riparian woodland to the island's highest waterfall at 13m; the trailhead is at Pano Platres village. All three trails are well-signposted with CTO (Cyprus Tourism Organisation) brown waymarkers and have parking at trailheads. The Troodos visitor centre (free entry) near the summit provides trail maps.",
      },
      {
        heading: "Akamas Peninsula: Adonis, Aphrodite, and Cape Arnaoutis",
        body: "Akamas is Cyprus's wildest hiking terrain — a legally protected peninsula at the northwest tip of the island with no permanent residents and limited road access. The Aphrodite Nature Trail (7.5km circular, 3–4 hours, medium difficulty) loops from the Baths of Aphrodite on the coast through thick maquis scrubland to ridge viewpoints overlooking Turkey on clear days; the trailhead is at the Baths of Aphrodite car park near Neo Chorio. The Adonis Nature Trail (7.5km circular, similar difficulty) covers adjacent terrain with denser forest sections and passes the Fontana Amoroza spring. Both trails share the same parking area and are often done as a combined figure-eight by experienced hikers in one day. Cape Arnaoutis, the westernmost point of Cyprus, requires a 4WD vehicle to reach the trailhead area and then a 2km walk to the cape itself — spectacular isolated coastal scenery. Note: hiking in Akamas without a guide in summer is not recommended; the terrain disorients easily and mobile coverage is minimal.",
      },
      {
        heading: "Paphos Forest, Coastal Paths, and the E4 European Trail",
        body: "Paphos Forest, covering over 60,000 hectares of the Troodos foothills, contains a network of lesser-used trails suitable for half-day walks. The Cedar Valley trail (5km, easy) passes through the last significant stand of Cedrus brevifolia, the Cyprus cedar endemic to the island — a short drive from Paphos town into the forest interior. Coastal trails are less formalised but rewarding: the Akamas coastal path from Latchi to Aphrodite's Baths follows cliff edges and small coves for 6km; the sea caves stretch near Paphos town has flat coastal walking on gravel tracks. Cyprus also hosts a segment of the E4 European long-distance path, which runs from Paphos through Troodos to Larnaca — the total Cypriot section is approximately 250km. Waymarkers are yellow/black diamonds and sections vary from excellent to overgrown; the Troodos-area E4 sections are the most consistently maintained.",
      },
      {
        heading: "Best months, heat avoidance, and seasonal conditions",
        body: "October through April is the hiking season. March and April bring wildflowers across the lower trails — poppies, anemones, orchids — and comfortable temperatures of 15–22°C at altitude. November through February sees Troodos snow (Olympus typically holds snow from December to March), which makes the mountain trails beautiful but requires proper footwear and layers. May becomes warm quickly; by June, lowland and coastal trails are genuinely dangerous by midday with temperatures above 35°C and no shade. July and August hiking in Cyprus at low altitude is inadvisable for most people — if you go, start before 7am and finish by 10am. The Troodos summit area is tolerable at 25–28°C even in August but access roads are congested with day-trippers. The best single month for hiking across all trail types is October: cool temperatures, no crowds, post-summer rains greening the landscape, and 8–9 hours of daylight.",
      },
      {
        heading: "Essential kit and practical logistics",
        body: "For summer hiking, even in October: 3 litres of water minimum per person for a half-day trail — water is not available on-trail anywhere in Cyprus. A hat and SPF50+ are non-negotiable; UV intensity at Troodos altitude is higher than most visitors expect. Trail shoes with ankle support rather than road trainers, since the terrain is rocky limestone and loose schist. For Troodos in winter: waterproof layer, thermal base layer, traction devices (micro-spikes) if you are attempting the summit trails after snowfall. Navigation: download the official CTO trail maps from visitcyprus.com (PDF) before heading out — the Troodos trails are also on AllTrails, but the coverage is incomplete. Mobile data is absent in most of Akamas and patchy on Troodos. The emergency number in Cyprus is 112 (works with any SIM). Trailhead parking is free at virtually all CTO-maintained trails; the exception is the Aphrodite Baths car park which charges €2 in high season.",
      },
    ],
  },
  {
    slug: "beach-guide-by-district",
    title: "Cyprus Beach Guide — Best Beaches by District",
    description:
      "A district-by-district guide to Cyprus's best beaches — from Limassol and Paphos to Larnaca, Ayia Napa, and Protaras — with crowd levels, facilities, Blue Flag status, and who each beach suits best.",
    sections: [
      {
        heading: "Limassol beaches: Lady's Mile, Governor's Beach, and Amathus",
        body: "Limassol's coastline stretches 20km east to west, with beaches ranging from gritty to genuinely good. Lady's Mile is a 7km undeveloped sandy strip south of Limassol port near Akrotiri — no sunbeds, no showers, no lifeguard, but also almost no crowds outside weekends; popular with kite-surfers and families with dogs (dogs are banned on most groomed beaches). It does not hold Blue Flag status. Governor's Beach, 30km east of Limassol near Kalavasos, is the most distinctive beach in the district: white chalk cliffs contrasting against dark volcanic sand and clear water; small, intimate, with basic facilities and a Blue Flag. Amathus Beach sits on the hotel strip east of the city — it is the city's most accessible groomed beach, with sunbeds (€8–12/day), showers, lifeguards in season (May–October), and Blue Flag certification. It is predominantly fronted by hotel guests in peak season but public sections are free. Parking is on-street along the main road; crowding peaks July–August.",
      },
      {
        heading: "Paphos beaches: Coral Bay, Lara Bay, and Aphrodite Hills coast",
        body: "Coral Bay, 10km north of Paphos town, is the district's busiest and most family-oriented beach: a curved sandy cove with calm water, full facilities (sunbeds, showers, lifeguards, cafes, water sports rentals), Blue Flag status, and good parking 200m back. It gets genuinely crowded in July–August; arrive before 10am for a good spot. Lara Bay is the antithesis — a protected nesting site for green and loggerhead sea turtles, accessible via 3km of unsealed track north of Coral Bay requiring a high-clearance vehicle, with no facilities and a seasonal prohibition on night visits and motorised water sports. The remoteness means calm water, pristine sand, and small numbers outside weekends; ideal for naturalists and anyone willing to drive the track. Aphrodite Hills coast near Kouklia offers smaller, quieter coves accessible by hotel shuttle or steep foot path from the clifftop resort — not independently accessible without a walk. The entire Paphos coastal area suits couples and families in roughly equal measure depending on which beach; Coral Bay is explicitly family-oriented, Lara Bay suits those who prefer undeveloped nature.",
      },
      {
        heading: "Larnaca beaches: Mackenzie, Finikoudes, and Mazotos",
        body: "Larnaca has three distinct beach types. Finikoudes is the city's palm-lined promenade beach — narrow, right on the seafront boulevard, popular with locals and tourists for the social atmosphere and proximity to restaurants and cafes; it holds Blue Flag status, has sunbeds and showers, but is not the island's most impressive sand. Best for couples and solo travellers who want beach access attached to a walkable town. Mackenzie Beach, 2km south of the city near the airport end, is wider than Finikoudes, less manicured, and known for its beach bars and casual atmosphere — a younger crowd, louder on weekends, free entry, basic facilities. The noise of Larnaca Airport landing approach is audible here but rarely bothersome. Mazotos Beach, 20km south of the city along a quiet coastal road, is a naturist-friendly (though not officially designated) long sandy stretch with a small traditional taverna; it has Blue Flag status and is genuinely uncrowded even in summer — the drive self-selects for people willing to make an effort. Families tend towards Finikoudes; couples and naturists towards Mazotos.",
      },
      {
        heading: "Ayia Napa and Protaras: Nissi Bay, Fig Tree Bay, and Cape Greco",
        body: "Ayia Napa and the Protaras coast hold the island's most photographed beaches. Nissi Bay, 3km west of Ayia Napa town, has the classic postcard look: fine white sand, turquoise shallow water, a small connected island at low tide, and a dramatic rock arch. Blue Flag, full facilities (sunbeds €10–15/day, showers, lifeguards, water sports), and extremely busy July–August — arrive before 9am or accept standing room only. This is genuinely one of the Mediterranean's most beautiful beaches but it is a tourist beach in peak season. Fig Tree Bay at Protaras (10km north) consistently ranks as Cyprus's top-rated beach by visitor surveys: finer sand than Nissi, calmer water (sheltered cove), clear visibility to 5m depth in calm weather, Blue Flag, full facilities. Better for families with young children than Nissi due to the shallow gradient. Cape Greco, between the two, has rocky coves and sea caves accessible by foot from the national park — no facilities, snorkelling is excellent, and it attracts a different crowd: divers, photographers, and hikers. Parking is limited and fills by 10am on summer weekends.",
      },
      {
        heading: "Practical notes on sunbeds, parking, and seasonal variation",
        body: "Sunbed pricing: €8–15 per pair per day across commercial beaches, with umbrella included. Most Blue Flag beaches have free public access zones without sunbeds alongside the commercial zones — walk past the sunbed rows and you can usually find a free stretch. Showers on Blue Flag beaches are cold water only. Lifeguards operate May through October, typically 9am–6pm; out of hours the sea is unpatrolled. Dog restrictions: dogs are banned on almost all groomed beaches with Blue Flag status from June through September; Lady's Mile, Lara Bay, and a few municipal beaches are exceptions. Parking: most major beaches have dedicated car parks (free or €1–2/day in summer); Nissi Bay and Fig Tree Bay have large paid car parks that fill by 10am in August — arrive early or take a taxi from Ayia Napa or Protaras towns. Out of season (October–April), all beaches are free, uncrowded, and facilities are minimal or closed; the sea remains swimmable until November at around 22–24°C.",
      },
    ],
  },
  {
    slug: "food-delivery-apps",
    title: "Food Delivery in Cyprus — Apps, Coverage, and What Actually Works",
    description:
      "A practical guide to food delivery apps in Cyprus — Bolt Food, Wolt, Foody — with honest coverage maps, typical fees, delivery times, and which cities and hours actually work.",
    sections: [
      {
        heading: "The three main apps and how they divide the market",
        body: "Cyprus has three meaningful food delivery platforms. Bolt Food is the dominant player with the widest restaurant selection in the four main cities — Limassol, Nicosia, Paphos, and Larnaca. It entered the Cyprus market around 2020 and has been aggressive in signing up restaurants, giving it the broadest coverage for both international cuisine and local Cypriot restaurants. Wolt has a smaller restaurant catalogue but strong quality curation — it tends to onboard restaurants that present well and deliver consistently, so average order quality is often better even if selection is narrower. Foody is the local Cypriot alternative, launched by a Cypriot company, with particular strength in signing up independent Cypriot restaurants that the international platforms have not yet reached. For a relocator, the practical strategy is to have all three installed: use Bolt Food for selection and speed, Wolt when you want a reliable result from a known restaurant, and Foody to discover local spots not listed elsewhere.",
      },
      {
        heading: "Coverage by city: where it works and where it doesn't",
        body: "Limassol has the best food delivery coverage on the island — all three apps have strong restaurant catalogues, most areas of the city are within delivery range, and average delivery times are 25–40 minutes. Nicosia is comparable in terms of variety, with Bolt Food particularly strong in the commercial centre and suburb areas. Larnaca has decent coverage for a smaller city; the central and coastal areas are well served, but suburbs more than 5km from the centre can fall outside delivery zones. Paphos coverage is workable for the Kato Paphos and Paphos town areas but thinner for outlying residential areas. Ayia Napa has very limited delivery options — the infrastructure for year-round delivery is not there, and outside July–August most restaurants that do list are sporadically available. Rural areas and villages outside the major cities are effectively not served. If you are relocating outside the four main cities, plan on cooking or driving; food delivery is not a reliable option.",
      },
      {
        heading: "Fees, minimums, and subscription plans",
        body: "Delivery fees across all three platforms are modest by EU standards: typical range is €1–3 per order depending on distance and whether the restaurant has a promotional rate. Platform fees (service charges) add another €0.30–0.70 in most cases. Minimum order values are typically €8–15 depending on the restaurant; most Cypriot restaurants set their minimum at €10–12. The platforms all offer subscription plans that eliminate delivery fees: Bolt Food's Bolt Pass runs approximately €5–7/month and covers unlimited free deliveries from eligible restaurants. Wolt+ is similarly priced. These subscriptions pay for themselves quickly for anyone ordering 2–3 times per week, and both plans include other Bolt/Wolt service discounts (rides, etc.) which makes them particularly useful to new residents. Foody does not currently have an equivalent subscription plan. Promo codes are common on all three apps in the first month after sign-up — check in-app on first launch.",
      },
      {
        heading: "Delivery times and late-night options",
        body: "Expected delivery time for a prepared order is 25–45 minutes in the main cities under normal conditions. This stretches to 45–60 minutes during peak hours (Friday and Saturday 7–9pm in Limassol particularly) and can exceed 60 minutes on public holidays or during storms. Bolt Food typically gives the most accurate real-time tracking. Late-night delivery is available but limited: most Cypriot restaurants stop taking delivery orders by 10pm or 11pm. The apps continue to operate until midnight–1am in the larger cities, but the available restaurants after 10pm are largely fast food chains, pizza outlets, and a small number of late-service restaurants. Genuine late-night food variety (post-midnight) is effectively only available in Limassol and occasionally central Nicosia. Ayia Napa in summer is an exception: July–August late-night delivery coverage briefly improves due to seasonal restaurant activity.",
      },
      {
        heading: "Practical tips for new residents",
        body: "Set your delivery address precisely on first use — Cyprus street addressing is inconsistent, and dropping the pin on the map is more reliable than typing the address. New buildings under 3 years old may not appear in the apps' address databases at all; in that case, add a delivery note with the building name and entry gate instructions. Cash on delivery is available on Foody and Bolt Food at many restaurants; Wolt is predominantly card only. All three apps work in Greek and English — the English UI is complete on all platforms, and most restaurant menus have English translations. For restaurants listing only in Greek, Google Translate's camera function on the menu image is faster than in-app translation. Ratings on Cyprus delivery platforms skew high; anything below 4.3 stars usually indicates a real consistency problem. The photo of the dish is often aspirational rather than literal — this is not unique to Cyprus, but the gap between photo and plate seems wider at local Cypriot restaurants than at chain restaurants.",
      },
    ],
  },
  {
    slug: "cypriot-cuisine-guide",
    title: "Cypriot Food Culture — A Relocator's Guide to Eating Like a Local",
    description:
      "What to order, how to eat it, where to find it, and the food customs that define Cypriot dining — from meze to kafeneion to seasonal produce.",
    sections: [
      {
        heading: "Meze: the Cypriot way of eating",
        body: "The defining structure of Cypriot restaurant dining is meze — a shared feast, not an individual meal. When a Cypriot restaurant says they serve meze, they mean they will bring 15–25 small plates continuously over 2–3 hours, covering cold starters (hummus, tahini, olives, pickled vegetables), grilled halloumi and loukanika sausages, then grilled and slow-cooked meats (souvlaki, sheftalia, kleftiko), then salads, then dessert and fruit. You do not order meze dishes individually; you agree to the meze, set a rough budget per head (typically €20–30 per person including one drink), and the kitchen decides the sequence. It is slow, social, and almost the opposite of ordering a main course. First-time visitors to Cyprus often sit down in a traditional taverna, ask to see the menu, and receive a handwritten card with three options: fish meze, meat meze, or mixed. Going out for meze is a 3-hour commitment — embracing this rather than resisting it is the first step to eating well in Cyprus.",
      },
      {
        heading: "Key dishes every relocator should know",
        body: "Kleftiko is slow-cooked lamb (sometimes goat) sealed in a clay oven for 6–8 hours until the meat falls off the bone — the word means 'stolen', from the legend of shepherds slow-cooking stolen meat underground to hide the smoke. It is the most distinctively Cypriot dish. Afelia is pork marinated and cooked in red wine and coriander seeds — mild, aromatic, usually served with cracked bulgur wheat. Souvlaki in Cyprus refers specifically to pork skewers grilled over charcoal; what Greeks call souvlaki pita (meat wrapped in flatbread) is sold here as pita souvlaki from fast-food stalls and is the city worker's lunch. Do not conflate the two. Halloumi has moved from table cheese to cultural icon: Cypriots eat it grilled (as meze), fried, in salads, in sandwiches, and — distinctively — alongside watermelon in summer. Loukoumades are honey-drenched doughnuts, typically served at Easter alongside flaounes (semolina-and-halloumi pastries eaten at Easter and nowhere else). Kolokasi is a Cypriot root vegetable like taro, braised with pork, and one of those deeply local dishes that rarely appears on tourist menus but is ubiquitous in homes.",
      },
      {
        heading: "Cypriot versus Greek food — the key differences",
        body: "Cyprus and Greece share a language and much culinary DNA, but the differences are real. Cypriot food is heavier on pork — the pig has been central to the Cypriot food culture since antiquity, and dishes like afelia, loukanika, and zivania-marinated meats have no direct Greek equivalent. Cypriot halloumi and anari (a fresh whey cheese) are island-specific; the salty, firm, grillable halloumi sold internationally is a pale approximation of the fresh halloumi you buy from village shops or market stalls, which is softer, mintier, and sold in brine. Cypriot bread (koulouria and local pita) is different from Greek pita — denser, sometimes with sesame. The Turkish Cypriot food tradition (pre-1974 Cyprus was a mixed community) survives in dishes like halloumi, tava (oven-baked meat and onions), and muhallebi (milk pudding) that you'll find across the whole island regardless of community. Finally, Cypriot cooking uses significantly more coriander seed than Greek, giving it a subtly different aromatic base.",
      },
      {
        heading: "Wine, Commandaria, and Keo beer",
        body: "Commandaria is the world's oldest named wine still in production — a sweet dessert wine made from sun-dried Xynisteri and Mavro grapes in the Troodos foothills villages of Kalo Chorio, Zoopigi, and 13 others that form the legally defined Commandaria appellation. It has been made continuously since the 12th century (the Crusader Knights Templar ran the vineyards). A good bottle runs €8–15 from the producers directly; the mass-market version from KEO (the main Cypriot wine producer) is cheaper but less interesting. KEO Lager is the ubiquitous Cypriot beer — light, 5%, and available everywhere. Local Cypriot wine has improved dramatically in the last decade: the Vasilikon, Tsiakkas, Zambartas, and Kyperounda wineries are producing genuinely good dry whites from the indigenous Xynisteri grape and reds from Maratheftiko. Wine with meze in a traditional taverna is typically house wine by the half-litre — ask for the local variety.",
      },
      {
        heading: "Kafeneion culture and the seasonal produce calendar",
        body: "The kafeneion is the Cypriot village coffeehouse — a male-dominated, card-playing, hours-long institution that has survived modernisation largely intact. In villages, the kafeneion is where opinions are formed and nothing much is hurried; a non-Cypriot is welcome but should understand the social cadence (you wait for an invitation to join a card game, you do not rush your coffee). Seasonal produce drives Cypriot cooking more than supermarket culture: watermelons from July to September (huge, cheap, omnipresent); carobs harvested September; citrus from November to March; strawberries from March; and the spring window of fresh artichokes, broad beans, and courgette blossoms that briefly dominates village market stalls in April. Olive oil: Cyprus produces good extra-virgin olive oil, and the best way to source it is directly from farmers at village markets or through the local agricultural cooperative (EKA). Prices for genuine Cypriot single-estate olive oil run €10–16 per litre — significantly better value than supermarket imported brands and markedly better flavour.",
      },
    ],
  },
  {
    slug: "coffee-culture-guide",
    title: "Coffee Culture in Cyprus — Cypriot Coffee, Freddo, and the Specialty Scene",
    description:
      "From Cypriot mud coffee to iced freddo espresso to the specialty third-wave scene in Limassol and Nicosia — how coffee works in Cyprus and where to find the best cup.",
    sections: [
      {
        heading: "Cypriot coffee: what to order and how",
        body: "Cypriot coffee (kafes Kypriakos) is functionally identical to Greek and Turkish coffee: very finely ground coffee, brewed in a long-handled brass or copper pot (briki) with water and sometimes sugar, then poured unfiltered into a small cup and allowed to settle before drinking. The grounds sink and are not consumed — but do not tap the cup, stir, or drink the last centimetre. Ordering system: sketo means no sugar (bitter), metrio means medium sugar (most common), glyko means sweet, and very glyko means very sweet; the sugar is dissolved during the brewing, not added after. The important nuance: you specify sweetness at the time of ordering because it affects preparation, not serving. Most traditional kafeneions and many village cafes still default to this style when you say 'ena kafe'. It is not espresso — it is a different brewing method that produces a thicker, more intense result with no crema. Served with a glass of cold water, always.",
      },
      {
        heading: "The kafeneion as a social institution",
        body: "The kafeneion (plural: kafeneia) is the Cypriot and Greek equivalent of the French café de quartier or the British village pub — but slower, older, and more explicitly male in its traditional form. In villages, the kafeneion opens at 6am and is full of farmers and retirees playing tavli (backgammon) or cards within the hour. A coffee here costs €1–1.50 and lasts as long as you want to sit. In Nicosia's old city and in Limassol's historic quarter, urban kafeneia blend into the general cafe landscape, but the slower pace and card tables distinguish them. For a relocator, the kafeneion is worth experiencing specifically because it is the clearest window into Cypriot social life that exists in public — conversations are long, opinions are strong, and the hospitality towards a stranger who sits down and orders properly (in Greek ideally, though English is fine) is genuine. The kafeneion in the village of Omodos or Lefkara, near the main square, is the archetype.",
      },
      {
        heading: "Freddo espresso and cappuccino: the Greek/Cypriot iced coffee standard",
        body: "The freddo is the dominant iced coffee drink in Cyprus and one of the things Cypriots and Greeks are quietly proud of inventing. A freddo espresso is two shots of espresso, blended with ice in a small cocktail shaker or milk frother until cold and frothed, then poured over ice. It is not a cold brew, not an americano, and not the Italian freddo espresso (which is just chilled espresso without froth). A freddo cappuccino adds cold frothed milk. Both cost €2.50–4 depending on the venue. The froth is the point — without the aeration the drink is just iced espresso, and Cypriots will notice and consider it wrong. You will see freddo machines in virtually every cafe in Cyprus; many staff serve dozens per hour in summer. The freddo is the default summer drink of working Cypriots the way an afternoon tea is a cultural anchor in Britain. Order one, drink it slowly in the shade, and you will understand why air conditioning has not replaced it.",
      },
      {
        heading: "Frappe, Nescafé, and the older generation's preferences",
        body: "Before the freddo displaced it, the Cypriot iced coffee was the frappe — instant Nescafé blended with cold water, ice, and sugar. It still exists and is still widely drunk, particularly by the over-50 generation. It tastes exactly like what it is (instant coffee over ice) but is extremely cheap (€1–1.50) and is not going anywhere. If you order 'a cold coffee' at a kafeneion or a rural cafe, you may receive a frappe; specify freddo if you want the espresso version. The distinction matters to Cypriots. Greek Cypriots who moved to Cyprus from the UK often continue to drink the British-style builder's tea from cafes that stock it; you will find Tetley's and Yorkshire Tea at the better-stocked supermarkets (Sklavenitis and Metro carry both). The younger generation is increasingly interested in specialty coffee and the distinction between espresso varieties, which has produced a small but growing third-wave scene in the major cities.",
      },
      {
        heading: "Specialty coffee in Limassol and Nicosia",
        body: "The specialty coffee scene in Cyprus is small but genuine. Limassol's Old Town — specifically the area around Anexartisias Street and Episkopou Leontiou — has 3–5 third-wave cafes that source single-origin beans, use calibrated espresso machines, and employ baristas who understand extraction. Names worth knowing: Neon Espresso Bar and Forty Winks Coffee (Limassol) are among the best-reviewed in the city. Nicosia has a parallel cluster around the Ledra Street pedestrian zone and the revitalised areas inside the walls near Faneromeni Square. Prices at specialty cafes are higher than the Cypriot norm — expect €3.50–5 for an espresso-based drink — but comparable to London or Amsterdam rather than inflated beyond them. Cyprus has not yet produced significant domestic coffee roasters; most specialty cafes import their beans from UK, Dutch, or Greek roasters. The specialty scene is worth knowing about because it is also where young, internationally-connected Cypriots and expats cluster — good networking territory in a small country where many professional relationships begin informally.",
      },
    ],
  },
  {
    slug: "home-cooking-ingredients",
    title: "Sourcing International Cooking Ingredients in Cyprus",
    description:
      "Where to find international cooking ingredients in Cyprus — from Asian and Indian spices to Middle Eastern staples and online delivery — plus what is genuinely abundant and cheap locally.",
    sections: [
      {
        heading: "What is abundantly local and excellent",
        body: "Before surveying the international options, it is worth cataloguing what Cyprus produces well and cheaply — because a significant part of cooking well in Cyprus is leaning into this. Halloumi, obviously: buy from the village cooperative or a market stall rather than a supermarket shelf if you can; the texture and saltiness of fresh-from-brine halloumi is materially different. Anari (fresh whey cheese) is exceptional and essentially unavailable outside Cyprus. Tomatoes, courgettes, aubergines, bell peppers, and cucumbers are inexpensive, flavourful, and local from April through October. Citrus — lemons, oranges, and the Cypriot bergamot used for preserved fruit — are abundant from November to March. Local olive oil from cooperatives runs €8–14 per litre for genuine Cypriot single-estate oil. Fresh herbs — rosemary, thyme, sage, coriander — grow semi-wild and are sold cheaply at markets; dried coriander seed and sumac are staple spices in Cypriot cooking and are widely available. Fresh fish (sea bream, sea bass, snapper) is excellent at seafront fish markets in Limassol and Larnaca. Building a cooking routine around Cypriot local produce first reduces both cost and dependency on specialty sourcing.",
      },
      {
        heading: "Mainstream supermarkets: Sklavenitis, Alphamega, and Metro",
        body: "Sklavenitis is the largest supermarket chain in Cyprus and carries the widest international range — it entered the market by acquiring the former Orphanides chain and has been expanding its imported goods section steadily. A well-stocked Sklavenitis (the Limassol and Nicosia flagship stores are most complete) will carry reasonable selections of Japanese sauces (soy, mirin, miso), Thai curry pastes, Italian pasta and preserved goods, French cheeses, and most standard European baking ingredients. Alphamega is locally owned and strong on Cypriot produce; international selection is narrower. Metro (rebranded from Carrefour) carries the most consistent range of French and European produce due to historical supply-chain links. Lidl Cyprus follows the standard Lidl formula: excellent occasional imports (Iberian week, Asian week, etc.) but you cannot rely on them being in stock. For everyday international cooking, Sklavenitis is the practical default; budget €15–30 extra per weekly shop versus what you'd spend on an equivalent basket in northern Europe.",
      },
      {
        heading: "Asian ingredients: Chinese, Thai, and Japanese sourcing",
        body: "Asian grocery sourcing in Cyprus is primarily centred on Limassol, which has a small but established Chinese and South-East Asian community. There are 2–3 specialist Chinese/Asian grocery stores in Limassol (in the Omonia and tourist strip areas) that stock: rice varieties (jasmine, glutinous, basmati), noodle types (rice noodles, egg noodles, vermicelli), Asian sauces (fish sauce, oyster sauce, dark and light soy, black bean, hoisin, Shaoxing wine), fresh tofu and firm tofu, frozen dim sum, Korean and Japanese snacks, and some fresh vegetables (daikon, bok choy, Thai basil). Stock turnover is slower than a major city so check expiry dates. Nicosia has one or two comparable stores but smaller selection. Larnaca and Paphos have almost no dedicated Asian grocery; occasional items appear in Sklavenitis but the selection is thin. If you are moving to Paphos and cook Asian food regularly, plan a monthly Limassol shop or use online delivery options.",
      },
      {
        heading: "Middle Eastern and Indian ingredients",
        body: "Larnaca and Nicosia are the best cities for Middle Eastern ingredients, reflecting the established Arab expat communities (particularly Lebanese, Syrian, and Jordanian) in both cities. Several Lebanese and Middle Eastern groceries near the Larnaca seafront and in central Nicosia stock: tahini (local and imported), pomegranate molasses, dried limes, za'atar blends, bulgur in multiple grades, freekeh, halal meats, and a range of Lebanese pickles and preserved vegetables. Prices are often lower than supermarkets for these categories. Indian spices present a different challenge: whole and ground spices beyond the basics (turmeric, cumin, coriander) require specialist stores. Limassol has 2–3 Indian grocery stores or sections within Middle Eastern shops that stock: curry leaf (dried), asafoetida, fenugreek, dried chillies (Kashmiri, arbol), mustard seeds, curry pastes, dal varieties, and Indian basmati. The Indian expat community in Limassol is the island's largest, and the sourcing network reflects this. Nicosia has one or two comparable options; Paphos and Larnaca are weaker for Indian specifics.",
      },
      {
        heading: "Online delivery and frozen meat services",
        body: "For items not available locally, Cyprus has a developing online grocery infrastructure. Agora.cy is the main online grocery marketplace and aggregates products from multiple retailers including Sklavenitis, with next-day delivery in the main cities. Papa.cy is a rapid-delivery service (30–60 minutes) for grocery essentials including some specialty items. Neither platform matches the catalogue depth of Ocado or a large European online grocer, but both are useful for staple replenishment and occasional specialty items. For meat specifically, several online services offer frozen or chilled delivery: Loullis Food Market and some specialist butchers in Limassol offer home delivery of halal meat, pork-free options, wagyu cuts, and specialty items. For specific dietary requirements (strictly kosher, certain halal certifications), the sourcing is limited — plan to import some items or build relationships with specific butchers. Limassol also has a weekly open-air market (the Saturday market near the old port area) where local producers, organic vegetable growers, and occasional specialty food importers sell directly — worth visiting on arrival to orient yourself to what is genuinely good locally.",
      },
    ],
  },
  {
    slug: "restaurant-reservations",
    title: "Booking Restaurants in Cyprus — How the System Actually Works",
    description:
      "How to book restaurants in Cyprus, when you actually need to book versus walk in, which platforms work, and the social customs around dining that new residents often get wrong.",
    sections: [
      {
        heading: "Peak season vs shoulder season: when booking is mandatory",
        body: "The most important variable in Cyprus restaurant booking is the time of year. June through August is peak season — the island's population roughly doubles with tourists, and popular restaurants in Limassol, Paphos, and Ayia Napa fill completely. For the top 10–15 restaurants in any given city during this period, booking 2–4 weeks ahead is not excessive; the most sought-after spots in Limassol's Old Town and Paphos harbour area are genuinely difficult to get into on a Saturday night in July without a reservation. September begins the taper: from mid-September through October, a week's notice is usually enough. November through April, most restaurants welcome walk-ins enthusiastically and you can often walk in that evening; this is one of the underappreciated advantages of living in Cyprus year-round versus visiting as a tourist. The exception is Christmas and New Year week, Easter weekend, and Cypriot public holidays (particularly the Clean Monday feasting tradition) — these are peak booking periods regardless of month.",
      },
      {
        heading: "How Cypriot restaurants actually take bookings",
        body: "The Cypriot restaurant booking infrastructure is approximately ten years behind northern Europe. TheFork (formerly La Fourchette) has a Cyprus presence but the number of Cypriot restaurants listed on it is small — perhaps 40–60 restaurants across the whole island, concentrated in Limassol and Nicosia. Resy has negligible presence. OpenTable is essentially absent. The vast majority of Cypriot restaurants take bookings by one of three methods: a direct phone call, a WhatsApp message, or walking in and booking in person for a future date. WhatsApp is genuinely the dominant method and is universally understood — a message saying 'Table for 2, Saturday 8pm, name Papadopoulos' is a completely normal and accepted booking. Response times vary from immediate to same-day. If you message and hear nothing after 4 hours during business hours, call. Many restaurants do not check WhatsApp obsessively. Having a Greek-language message template (easily Google-translated) is appreciated but English is understood everywhere that tourists visit.",
      },
      {
        heading: "Language, confirmation, and the no-show culture",
        body: "English is spoken at virtually every restaurant that tourists visit in Cyprus, and booking in English is never a problem in Limassol, Paphos, Nicosia, or Ayia Napa. The language question only arises at village tavernas that are genuinely local — in those cases, a few words of Greek or pointing at the chalkboard menu is standard and charming rather than awkward. Confirmation culture is looser than northern Europe: having made a booking does not mean anyone will call to confirm it the day before, and a no-show culture exists on both sides — restaurants know some bookings will not show up, and some restaurants will give away your table if you are 15+ minutes late without calling. If you have made a booking for a large group (6+) during peak season, a confirmation message the day before is standard and appreciated. Some high-end Limassol restaurants have started taking credit card details to hold peak-season bookings — this is spreading slowly but is not yet widespread.",
      },
      {
        heading: "Tipping etiquette across venue types",
        body: "Tipping norms in Cyprus are loose but present. At a traditional kafeneion or village taverna, no tip is expected; rounding up (leaving small change on a €12 bill) is fine. At a mid-range restaurant (meze taverna, seafood restaurant, city bistro), 10% is the informal expectation and appreciated but not policed. At upscale Limassol restaurants and hotel restaurants, 10–15% is standard and some add a service charge (check the bill). For delivery, €0.50–1 cash tip directly to the rider is common though not universal; in-app tipping is available on Wolt and Bolt Food but rarely used. A practically important note: Cypriot restaurant bills often add a couvert (table bread and olive oil charge) of €0.50–2 per person automatically; this is standard and not negotiable in most establishments. The bill in Cyprus arrives when you ask for it — restaurants do not bring it unsolicited and will leave you at the table for as long as you want to sit. If you have a reservation after you, the restaurant will usually mention this diplomatically but will not pressure you.",
      },
      {
        heading: "Practical tips for navigating the system as a newcomer",
        body: "Three practical shortcuts for a new resident. First, save the WhatsApp contact of any restaurant you enjoy immediately after dining — the next time you want to go back, messaging via WhatsApp is faster and more reliable than calling. Second, for peak-season planning of a significant dinner (birthday, business meal), call or message during the restaurant's quietest hours — weekday afternoon between 3–5pm, when the kitchen is in prep mode and someone is available to answer properly. Third, Google Maps restaurant listings in Cyprus are increasingly reliable for checking opening hours but should not be trusted for table availability; the listing may say 'popular' or 'usually a wait' but this is algorithmic inference, not actual table data. The most reliable signal that a restaurant is worth booking is word-of-mouth from other residents — the expat WhatsApp groups in Limassol and Nicosia are the best source of up-to-date dining recommendations and often include direct links to preferred booking contacts.",
      },
    ],
  },
  {
    slug: "utilities-setup-guide",
    title: "Setting Up Utilities After Moving Into Your Cyprus Home",
    description:
      "How to get electricity, water, broadband, and gas connected after moving into a Cyprus property — with realistic timelines, costs, and the paperwork each utility requires.",
    sections: [
      {
        heading: "EAC electricity: connection process and costs",
        body: "The Electricity Authority of Cyprus (EAC) is a state monopoly — there is no supplier choice in Cyprus, unlike most EU member states. To set up electricity at a new address, you need to apply for a new account, which can now be done online at the EAC website (eac.com.cy) or in person at any EAC district office. Required documents: a signed rental contract or property title deed, your passport or ARC/Yellow Slip, and your mobile number. If the property has been occupied before, the transfer is straightforward: give EAC the account number from the previous occupant (your landlord can provide this) and request a transfer. For a brand new connection (newly built property with no prior account), the process involves a technical inspection and connection fee — the standard connection fee is approximately €20 for a residential single-phase connection, with additional costs if works are required at the meter. Processing time is 2–5 working days for transfers; up to 10 working days for brand new connections. EAC bills bimonthly; your first bill arrives 6–8 weeks after connection.",
      },
      {
        heading: "Water: municipality boards and the application process",
        body: "Water supply in Cyprus is not a single national utility — it is managed by municipality water boards that vary by city. Limassol has the Limassol Water Board (LWB), Nicosia has a separate municipal service, Larnaca has its own, and Paphos similarly. The application process is broadly similar across municipalities: apply in person or online to the relevant water board, provide your rental contract or property deed, your passport or ARC/Yellow Slip, and in some cases a utility bill to confirm the address. Limassol Water Board requires an in-person visit to their office on Gladstonos Street for new tenant registrations; the process takes 1–3 working days and has no connection fee for existing connections (the charge for new connections varies by municipality, typically €10–30). Water billing is quarterly in most municipalities and is inexpensive by EU standards — most 2-bedroom apartments pay €15–25 per quarter. Note: in villages, water supply may be managed by the village authority (Koinotis) rather than the main municipality board; your landlord should clarify the correct body to contact.",
      },
      {
        heading: "Broadband: choosing between Cablenet, Epic, Primetel, and Cyta",
        body: "Order broadband on your first day in the apartment, not after you have sorted other things. Installation typically takes 5–10 working days, and the gap period without reliable home internet is uncomfortable if you are working remotely. Four main providers operate across Cyprus: Cyta (state-owned, widest coverage including rural areas, 500Mbps–1Gbps packages for €40–55/month), Cablenet (privately owned, strong in Limassol and Nicosia, highly regarded for connection stability, 500Mbps–1Gbps for €45–60/month), Epic (Limassol-based, similar pricing to Cablenet, good customer service reputation), and Primetel (smaller network, occasionally more competitive on pricing for introductory offers). For a relocator moving to Limassol, Cablenet is the most consistently recommended by long-term residents — particularly for remote workers who need reliable upload speeds. Cyta is the practical choice in rural areas and smaller towns where Cablenet and Epic do not have infrastructure. All four providers require a signed rental contract or property deed and your ARC/Yellow Slip to process the application. Contracts are typically 12–24 months; shorter contracts carry a higher monthly fee.",
      },
      {
        heading: "Gas: LPG cylinders and the absence of mains gas",
        body: "There is no mains gas network in Cyprus. Natural gas pipeline infrastructure is in early development stages and is not available to residential customers as of 2026. All residential gas use — for cooking hobs and standalone gas heaters — uses bottled LPG (liquefied petroleum gas). Cylinders come in standard 13kg and 5kg sizes and are available at petrol stations, hardware stores, and some supermarkets. A 13kg cylinder costs €22–28 depending on the supplier (Primagas, Petrogaz, and Esso are the main brands); a full cylinder lasts a typical family roughly 4–6 weeks for cooking only, or 2–3 weeks if also used for portable heaters. Exchange is simple: take your empty cylinder to any petrol station, pay the refill price, and take a full one. No deposits or paperwork are required once you have the cylinder. For a new property, your first cylinder purchase includes the cylinder cost (€12–18) plus the gas fill; subsequent exchanges cost gas only. Rented properties typically come with a gas setup already installed; if not, a plumber can fit a standard gas hob connection for €80–150 including the regulator and flexible hose.",
      },
      {
        heading: "Waste collection and municipality rates",
        body: "Residential waste collection in Cyprus is a municipal service funded through municipality rates (a property tax collected by the local authority). In practice, this means you do not pay a separate waste collection bill — it is included in the municipality rates that your landlord or property manager pays as part of ownership. As a tenant, you may be billed separately by your landlord for your share of municipality rates (typicaly €150–350 per year for a 2-bedroom apartment depending on the municipality), or this may be included in your rent — check your rental contract. Bin collection in urban areas is typically 2–3 times per week for general waste. Recycling is present but inconsistent: most Cypriot cities have roadside yellow recycling bins (paper, plastics, metals) and green glass banks, but coverage and frequency of collection are patchier than in northern Europe. Limassol has the most developed municipal recycling programme; rural areas are weakest. Bulky waste (old furniture, appliances) requires arranging a separate collection through the municipality — your landlord or a local neighbour can advise on the specific process for your area, as procedures vary.",
      },
    ],
  },
];
