/**
 * Guides batch G4 — family, healthcare, and transport topics.
 * Consumed alongside GUIDES in lib/guides.ts.
 */

import type { GuideInfo } from "./guides";

export const GUIDES_G4: ReadonlyArray<GuideInfo> = [
  {
    slug: "family-neighborhoods-guide",
    title:
      "Best Family-Friendly Neighborhoods in Cyprus — District by District",
    description:
      "Which specific neighborhoods in Limassol, Paphos, Larnaca, Nicosia, and Ayia Napa actually work for families — covering safety, green space, international school proximity, community character, and price ranges.",
    sections: [
      {
        heading: "Limassol: Germasogeia and Agios Athanasios",
        body: "Germasogeia is the default landing zone for English-speaking families moving to Limassol. It runs along the B1 highway east of the city center and offers a well-established suburban feel: wide pavements, multiple supermarkets, several pharmacies, and direct routes to the private school cluster (Heritage Private School, The Grammar School, PASCAL) which are all within a 10–15 minute drive or school bus route. Rents for a three-bedroom villa with a small garden run €2,000–€3,500 per month; apartments in the €1,500–€2,200 range are plentiful. Agios Athanasios, directly south and slightly more elevated, is quieter and marginally cheaper. Its tree-lined streets and lower traffic density make it popular with families with young children. Both areas are safe by any European standard — street crime is rare and the expat-to-local ratio is high enough that English is spoken everywhere. The downside of both: you need a car for almost everything, and Limassol's summer heat means the nearby Dasoudi forest park and seafront promenade become the main outdoor activity zones.",
      },
      {
        heading: "Paphos: Chlorakas and Peyia",
        body: "Paphos is significantly more relaxed than Limassol in pace and price, which makes it popular with families who want lower costs without sacrificing an international community. Chlorakas is the closest suburb to central Paphos, about 4 km north of the old town, and has grown considerably in the last decade — it now has several supermarkets, a growing restaurant strip, and easy access to Paphos International Airport (15 minutes). Rents are €1,200–€2,000 for a three-bedroom house, and property purchase prices are among the most accessible in Cyprus. The local international school scene is anchored by The International School of Paphos and Falcon School, both well-regarded and charging €5,000–€8,000 per year — meaningfully cheaper than Limassol equivalents. Peyia, higher up the hills above Coral Bay, attracts families who want space and cooler summers; it's a 20-minute drive from the city but properties are bigger and gardens are standard. The trade-off is that Peyia is a British-expat village more than an integrated community — your children will be immersed in English culture rather than Cypriot culture, which matters for some families.",
      },
      {
        heading: "Larnaca: Mackenzie and Drosia",
        body: "Larnaca is underrated as a family destination and noticeably cheaper than Limassol for equivalent space. Mackenzie, named after the beach strip south of the old town, has become significantly more polished since 2020 — the seafront promenade is walkable, new restaurants have replaced old tavernas, and several apartment complexes in the €1,100–€1,700 range are within walking distance of the beach. For families with school-age children, the draw is proximity to The English School Larnaca and Pascal Institute Larnaca (both international, €5,000–€8,000 per year). Drosia, 3–4 km inland along the B1, is the more established suburban choice — quieter, slightly lower crime even by Cyprus standards, and popular with Cypriot middle-class families, meaning your children will mix with locals more naturally than in the tourist-facing neighborhoods. A three-bedroom house in Drosia rents for €1,100–€1,800. Larnaca Airport being 5 km away is genuinely convenient for frequent travellers but produces noticeable flight noise under the approach path.",
      },
      {
        heading: "Nicosia: Strovolos and Engomi",
        body: "Nicosia is the capital and the city most Cypriots actually live in, which gives it a different character from the coastal cities — fewer tourists, more authentic daily life, and the widest range of private schools of any district. Strovolos is the largest suburb and a genuine family neighborhood: it has parks, playgrounds, wide residential streets, and multiple international schools including The American Academy, The Grammar School Nicosia, and Falcon School Nicosia, all within the suburb or immediately adjacent. Rents for a three-bedroom apartment run €1,100–€1,800. Engomi, just north and near the University of Cyprus campus, is slightly more upscale and walkable — the neighborhood around the Makedonitissa reservoir has green space and a calmer pace. The practical disadvantage of Nicosia for many families: it is landlocked, the summer heat is more intense (temperatures regularly hit 40°C versus coastal highs of 34–36°C), and the sea requires a 45-minute drive to Larnaca or the Latchi coast. Families who work primarily in Nicosia and prioritise school choice over beach access tend to love it; families who moved to Cyprus partly for the coastal lifestyle find it frustrating.",
      },
      {
        heading: "Ayia Napa: Protaras and Paralimni",
        body: "Ayia Napa itself is a party town and not a practical family base outside the winter months. The residential family choice in the eastern district is Protaras and the municipality of Paralimni, about 8–10 km north of Ayia Napa. Protaras blends holiday infrastructure with a growing year-round residential community — the beaches (Fig Tree Bay is one of the best in Cyprus) are genuinely excellent, the area is safe, and property prices remain lower than Limassol or Paphos for comparable quality. Paralimni is the administrative center and more authentically Cypriot in character — it has a full supermarket offering, the main government offices for the district, and a quieter residential feel. The school situation is the main constraint: there is no major international private school in the Famagusta district, meaning families typically choose between the local Greek-Cypriot public system (increasingly English-medium at secondary level but still primarily Greek) or boarding/daily commute to Larnaca. For families with young children, this is manageable; for secondary-age children, it becomes the deciding factor.",
      },
    ],
  },
  {
    slug: "maternity-paternity-rights",
    title:
      "Maternity and Paternity Rights in Cyprus — What Employed Parents Are Entitled To",
    description:
      "What employed and self-employed parents in Cyprus are actually entitled to — maternity leave duration, benefit rates, paternity leave, parental leave, and how Social Insurance calculates the payments. Prices and rules change — verify with official Cyprus sources before acting.",
    sections: [
      {
        heading: "Maternity leave: the 18-week structure",
        body: "Employed women in Cyprus are entitled to 18 weeks of maternity leave under the Maternity Protection Law. Two weeks of that leave are compulsory and must be taken before the expected birth date — this is a legal minimum, not a recommendation. Of the 18 weeks total, the first 9 weeks after birth are paid by the Social Insurance Services at a rate of 75% of the mother's insurable earnings (subject to a weekly cap that is revised periodically — currently around €1,000 per week of benefit, meaning high earners are capped). The remaining weeks — weeks 10 through 18 — are paid by the employer, provided the employee has been on the payroll for at least 6 months continuously prior to the maternity leave start date. Employees who have been employed for fewer than 6 months are still entitled to the Social Insurance-funded portion; the employer top-up for the final 9 weeks is the part that requires 6 months of continuous employment. Dismissal of a pregnant employee or a woman on maternity leave is illegal in Cyprus; it is one of the most clearly protected labour rights in Cypriot employment law.",
      },
      {
        heading: "Maternity benefit calculation",
        body: "The Social Insurance maternity benefit is calculated as 75% of the mother's average insurable earnings during the relevant contribution period — specifically the earnings in the contribution year two years prior to the benefit year. Cyprus Social Insurance uses 'insurable earnings' rather than gross salary, and insurable earnings are subject to an annual ceiling (approximately €54,864 per year as of recent rates). In practice, this means a mother earning €30,000 per year gross will receive approximately €433 per week during the Social Insurance-funded period (€30,000 ÷ 52 × 75%). A mother earning €60,000 per year — above the insurable ceiling — will receive the same capped amount as a mother earning at the ceiling. The benefit is paid directly by Social Insurance Services and is separate from any employer-paid salary continuation. To claim, you submit Form M1 to the Social Insurance Services office at least 3 months before the expected due date, along with your employer's certificate of employment.",
      },
      {
        heading: "Paternity leave: the 2-week entitlement",
        body: "Employed fathers in Cyprus are entitled to 2 weeks (10 working days) of paternity leave, which must be taken within 16 weeks of the birth. Unlike maternity leave, paternity leave is funded directly by Social Insurance Services — not by the employer — at 72% of insurable earnings using the same calculation methodology as maternity benefit. This means paternity leave is not dependent on the employer's goodwill or payroll policies; it is a statutory right with Social Insurance funding. The practical process: the father notifies the employer, submits the birth certificate and Form M4 to Social Insurance, and the benefit is paid to his bank account. Paternity leave in Cyprus is still relatively short compared to Scandinavian standards, but it is properly funded and enforced. An important point: paternity leave is distinct from parental leave — the 2 weeks are specifically linked to the birth event.",
      },
      {
        heading: "Parental leave: 18 weeks per parent",
        body: "In addition to maternity and paternity leave, each parent is entitled to 18 weeks of parental leave per child (the same 18 weeks cannot be shared — each parent has their own 18-week entitlement). Parental leave in Cyprus is currently unpaid — unlike the maternity benefit, there is no Social Insurance payment during parental leave. It can be taken at any point until the child's 8th birthday, and it can be taken all at once or in separate blocks. The employer cannot refuse the request but can ask for it to be scheduled in a way that does not disrupt operations — they can defer it by up to a month in certain circumstances. For families where one partner earns significantly more than the other, the practical use of parental leave tends to fall to the lower earner since there is no income replacement. Calls to make parental leave paid (following EU Parental Leave Directive requirements) have been discussed in Cypriot parliament; the position as of 2025 is unpaid, but this is worth verifying if you are planning leave more than 12 months out.",
      },
      {
        heading: "Self-employed maternity benefit",
        body: "Self-employed mothers in Cyprus are entitled to maternity benefit from Social Insurance under the same 18-week framework, provided they have made sufficient Social Insurance contributions. The self-employed rate is calculated on the basis of declared insurable earnings rather than payslips — specifically, the self-employed person's insurable earnings from the contribution year two years prior. The practical implication: if you have under-declared insurable earnings (a common situation for self-employed people in Cyprus who want to minimize contributions), your maternity benefit will be proportionally reduced. The Social Insurance contribution for self-employed individuals is 15.6% of insurable earnings as of current rates, covering both the employee and employer portions. Self-employed mothers should request Form M1SE from Social Insurance and submit it at least 3 months before expected delivery. There is no employer top-up for self-employed mothers — the full 18 weeks of benefit, if any, comes from Social Insurance at the 75% rate, subject to the usual caps.",
      },
    ],
  },
  {
    slug: "gesy-registration-guide",
    title: "How to Register with GeSY — Cyprus Public Health System Step-by-Step",
    description:
      "Who must register, how to complete the process on the HIO portal, choosing a personal GP, contribution rates for employed and self-employed residents, and what is and is not covered. Prices and rules change — verify with official Cyprus sources before acting.",
    sections: [
      {
        heading: "Who must register and why it matters",
        body: "GeSY (General Healthcare System, from the Greek Γενικό Σύστημα Υγείας) launched in June 2019 and became fully operational for all services in June 2020. Every legal resident of Cyprus — EU citizens, non-EU residents with ARC, and Cypriot nationals — is required to register and contribute. Registration is also mandatory for employers, self-employed individuals, and pensioners. Unlike the old system where public healthcare was free but largely inaccessible to non-citizens and of highly variable quality, GeSY creates a single-payer insurance model where all registered residents have equal access to GPs, specialists, and public hospitals. The practical reason to register immediately upon arrival: without a registered personal doctor (GeSY uses the term 'personal doctor'), you cannot get GP referrals or prescription coverage, and attending a public hospital A&E without a GeSY card results in higher co-payments. Registration takes about 20 minutes online if you have your documents ready.",
      },
      {
        heading: "Registration process on hio.org.cy",
        body: "The Health Insurance Organisation (HIO) portal at hio.org.cy is the registration entry point. You will need your ARC number (for non-EU residents) or Yellow Slip registration number (for EU residents), your passport, a valid email address, and a Cypriot mobile number for the SMS verification step. Navigate to the 'Beneficiaries' section, select 'New Registration', and complete the identity verification. You will be asked to confirm your residential address in Cyprus, your employment status (employed, self-employed, pensioner, unemployed), and your preferred language. After completing registration, the system assigns you a GeSY beneficiary number, which is your permanent reference. The physical HIO card — a blue card with a magnetic strip — is posted to your registered address within 2–4 weeks; in the meantime your beneficiary number and the HIO app (iOS and Android) serve as your credential. Keep the beneficiary number written down separately: you will need it the first time you visit a doctor before the card arrives.",
      },
      {
        heading: "Choosing your personal doctor",
        body: "After registering as a beneficiary, you must choose a personal doctor (GeSY-contracted GP) within 30 days. The HIO portal lists all GPs who accept GeSY patients; you can search by city, language spoken, and gender. In Limassol, Nicosia, and Paphos, finding an English-speaking GeSY GP is straightforward — most clinics in expat areas have at least one English-fluent doctor. In rural areas or smaller towns, language can be a constraint. Your personal doctor is the gatekeeper for specialist referrals: without a referral from your GeSY GP, specialist visits are either not covered or attract a higher co-payment. You can change your personal doctor once every six months via the HIO portal. The practical tip: visit your chosen GP once for a routine check in your first month, even if you have no medical needs — it establishes the relationship and ensures you know how the system works before you actually need it.",
      },
      {
        heading: "Contribution rates and what they cover",
        body: "GeSY is funded through payroll contributions. For employed individuals: the employee contributes 2.65% of gross salary, the employer contributes 2.90%, and the state contributes an additional 4.70% for the beneficiary pool. For self-employed individuals: the contribution is 4.00% of insurable income. For pensioners: 2.65% of pension income. Contributions are deducted automatically for employees; self-employed individuals pay via tax return. What is covered: visits to your personal doctor (free, no co-payment), specialist visits via referral (€6 co-payment per visit), prescription medications (€1 co-payment for generics, higher for branded drugs), accident and emergency, most public hospital procedures and admissions, physiotherapy (limited sessions), mental health services (limited sessions). Dental is covered in a limited way — see the Dental Care guide for specifics. Items not covered include aesthetic procedures, elective cosmetic surgery, and some specialist procedures that exceed GeSY's reference pricing schedule.",
      },
      {
        heading: "GeSY for self-employed and non-standard residents",
        body: "Self-employed residents register under the 'self-employed' beneficiary category and pay 4.00% of declared insurable income rather than the employed rate. The minimum GeSY contribution for self-employed individuals is based on the statutory minimum insurable income, which means even if your declared income is very low, there is a floor contribution — currently approximately €180–€200 per year. For non-EU residents on a Digital Nomad Visa whose income is from foreign sources: you are still required to register for GeSY as a legal resident, and the contribution is treated as 4.00% of your declared income in Cyprus (which for a pure DNV holder may be zero — in that case, the HIO assesses contributions at minimum rates). If you hold both private health insurance and GeSY, you are still legally required to make GeSY contributions — opting out of the public system is not permitted. Most long-term residents keep both, using GeSY for routine care and private insurance for faster specialist access and private hospital admissions.",
      },
    ],
  },
  {
    slug: "pharmacies-medication",
    title: "Pharmacies and Prescription Medication in Cyprus",
    description:
      "How Cyprus pharmacies work, the after-hours duty rota, GeSY prescription coverage, transferring a foreign prescription, and what you can bring into Cyprus from abroad.",
    sections: [
      {
        heading: "How the pharmacy system works",
        body: "Cyprus has a dense network of pharmacies (farmakeio in Greek) identified by the standard green cross sign. In Limassol, Nicosia, Paphos, and Larnaca, there is typically a pharmacy within a 5–10 minute walk in any suburban area. Unlike supermarket pharmacy counters in the UK or US, Cypriot pharmacies are standalone businesses staffed by qualified pharmacists, and they are genuinely consultative — it is normal to describe symptoms and receive a recommendation without a GP visit for straightforward ailments. Pharmacy hours are generally 8:00–13:00 and 15:30–19:30 on weekdays, and 8:00–13:00 on Saturdays. Outside these hours, a rotating after-hours duty pharmacy (efimeria) is open in each district. The on-duty pharmacy is signposted on the door of any closed pharmacy in the area, and the list is published daily in the local newspapers and on the Cyprus Pharmaceutical Services website (phs.moh.gov.cy). In the main cities, at least one pharmacy in each area is typically on duty at any given evening or weekend.",
      },
      {
        heading: "GeSY prescription coverage and co-payments",
        body: "With a GeSY-registered personal doctor and a GeSY prescription, medications are dispensed at a co-payment of €1 for generic drugs. Branded medications that have a generic equivalent are dispensed at the generic price plus the difference if you specifically request the brand — pharmacists are required to offer the generic substitute and inform you of the price difference. Medications with no generic equivalent are covered at GeSY's reference price, which may be less than the pharmacist's retail price; the patient pays the gap. Chronic disease medications for conditions on the GeSY approved list (diabetes, hypertension, thyroid conditions, and others) are available with zero co-payment for GeSY beneficiaries. To use GeSY at a pharmacy, present your HIO card or beneficiary number; the pharmacist scans the prescription in the GeSY system directly. Pharmacies that accept GeSY display the GeSY logo — not all private pharmacies in Cyprus are contracted with GeSY, though the majority in urban areas are.",
      },
      {
        heading: "Transferring a foreign prescription to Cyprus",
        body: "Cyprus does not accept foreign prescriptions directly — a prescription from a UK GP, Israeli doctor, German physician, or any other non-Cypriot medical authority cannot be dispensed at a Cypriot pharmacy without being rewritten by a Cyprus-registered doctor. This applies even within the EU (there is a theoretical EU cross-border prescription framework, but practical implementation at Cypriot pharmacies is inconsistent at best). The process in practice: bring your foreign prescription and, ideally, a recent medical letter from your doctor to a GeSY GP or private doctor in Cyprus, explain your treatment, and they will issue a Cypriot prescription. For routine chronic medications (blood pressure, diabetes, thyroid, antidepressants), most GPs will rewrite the prescription at the first visit without requiring extensive investigation, provided you have documentation of the diagnosis and current dosage. Allow at least one week between arrival and running out of a critical medication — booking the GP appointment takes a few days, and some medications may need to be ordered if the pharmacy does not stock them.",
      },
      {
        heading: "Medications available OTC in Cyprus",
        body: "Cyprus is slightly more liberal than some northern EU countries in what is available over the counter. Strong codeine-combination painkillers (e.g. co-codamol 30/500) are available without prescription from pharmacists in Cyprus, whereas the same product requires a prescription in the UK and Germany. Several antifungal treatments, eye antibiotics, and oral contraceptives that require prescriptions elsewhere in the EU can be obtained from Cypriot pharmacists after a brief consultation. Pharmacists in Cyprus are trained and legally permitted to make these dispensing decisions under the Pharmacy and Poison Law. Conversely, benzodiazepines, strong opioids, and Schedule 1 controlled substances are tightly controlled and require a specific controlled-drug prescription form; the regulations here match or exceed EU norms. If you are accustomed to a medication being available OTC in your home country and it appears to be prescription-only in Cyprus, it is worth asking the pharmacist directly — the answer may be different from what you expect.",
      },
      {
        heading: "Bringing personal medication supply into Cyprus",
        body: "You may bring up to a 90-day personal supply of most medications into Cyprus when travelling. For controlled substances (opioids, benzodiazepines, stimulants for ADHD), you must carry either a letter from your prescribing doctor specifying the medication, dosage, and duration of treatment, or an official medical certificate from your country's health authority. The 90-day rule is enforced at Customs and applies to all prescription medications — carrying more than 90 days' supply of any prescription medication without prior import authorisation from the Cyprus Ministry of Health is technically illegal, though enforcement at the personal-use level is rare for non-controlled drugs. For ADHD medications (methylphenidate, amphetamines), Cypriot prescribing practices are more restrictive than in the US or UK — local psychiatrists do prescribe these, but the process takes longer, typically involving a fresh assessment rather than simply continuing a prior prescription. If this affects you, arrange a psychiatrist appointment as early as possible after arrival.",
      },
    ],
  },
  {
    slug: "dental-care-guide",
    title: "Dental Care in Cyprus — Cost, Quality, and Finding a Good Dentist",
    description:
      "What GeSY covers for dental, typical private dental costs, how Cyprus compares to the UK and Germany, how to find an English-speaking dentist, and dental insurance options.",
    sections: [
      {
        heading: "GeSY dental coverage: what is and is not included",
        body: "GeSY dental coverage is limited compared to general medical coverage. As of 2025, GeSY covers emergency dental care (emergency extractions, urgent pain treatment, emergency temporary fillings) and basic preventive care for children up to age 18. Routine adult check-ups, professional cleaning, composite fillings, crowns, bridges, implants, and orthodontic work are not covered by GeSY — these are entirely private costs for adults. This is an area of ongoing political discussion in Cyprus, with broader dental coverage regularly debated in parliament, but the current situation means most adults budget entirely privately for dental care. The practical consequence for relocators: do not expect GeSY to cover your dental needs the way it covers your GP visits and hospital care. Factor a separate dental budget or dental insurance policy into your planning.",
      },
      {
        heading: "Private dental costs in Cyprus",
        body: "Cyprus is meaningfully cheaper than western Europe for private dental work. Typical costs across Limassol, Nicosia, Paphos, and Larnaca: professional clean and scale (€60–€80), dental X-rays (€20–€40 for a full set of 4), composite filling (€80–€120 depending on size and surface), root canal treatment (€300–€500 per tooth), ceramic crown (€400–€600), dental implant including crown (€800–€1,200 for standard cases), Invisalign clear aligners (€2,500–€4,000 for a full course), and porcelain veneers (€400–€600 per tooth). These prices are 40–60% below comparable UK private rates and 30–50% below German rates. Quality is generally high — Cyprus has several hundred registered dentists trained in European universities, and the dental schools in Nicosia have raised the overall standard in recent years. Prices at tourist-area clinics (Ayia Napa, tourist strip in Paphos) can be 20–30% higher than equivalent care in residential areas.",
      },
      {
        heading: "How to find an English-speaking dentist",
        body: "Finding an English-speaking dentist in Cyprus is straightforward in the four main cities — the majority of dentists trained either in the UK, Greece, or other EU countries with strong English fluency, and English is effectively the default language of Cypriot dentistry for non-Greek speakers. The most reliable methods: ask in the main expat Facebook groups for your city (Expats in Cyprus, Limassol Expats, Paphos Expats — each has tens of thousands of members and produces well-sourced recommendations), check Google Maps reviews filtered to English reviews, and ask your GeSY personal doctor for a referral to a colleague. The HIO portal does not provide a searchable dentist directory in the same way as GPs, since dentists are largely outside the GeSY referral system. Walk-in bookings are generally possible for new patients, though popular clinics in Limassol fill up quickly — booking a week ahead is typical. Ask about pricing before the appointment, not after; reputable clinics are transparent about costs.",
      },
      {
        heading: "Private dental insurance options",
        body: "Private dental insurance in Cyprus is available but relatively limited compared to the UK market. Most local insurance providers (CNP Asfalistiki, AXA Cyprus, Interamerican) offer dental rider packages as add-ons to general health insurance rather than standalone dental policies. A typical add-on covers 50–80% of routine care costs up to an annual limit of €500–€1,000 per person, with an excess of €50–€100. Given that a clean, two fillings, and a check-up totals roughly €200–€250 per year, the insurance arithmetic only makes sense if you are expecting significant work (crowns, implants). An alternative approach used by many Limassol and Paphos residents: a dental savings plan offered directly by some larger dental clinics — you pay €200–€400 per year and receive discounted rates on all treatments plus two free check-ups. For anyone planning significant dental work, getting quotes from 2–3 clinics before committing is standard practice.",
      },
      {
        heading: "Dental tourism context: Cyprus as a destination",
        body: "Cyprus's combination of low costs, English language, and EU healthcare standards has made it a minor dental tourism destination, with clinics in Limassol and Paphos that specifically market to UK, German, and Scandinavian patients who come for multi-day implant or cosmetic work. For relocators this is relevant in two ways: first, these clinics are often the most internationally experienced and English-fluent options; second, availability at popular implant clinics can be tighter than at general practices. If you are planning major restorative work — full arch implants, significant cosmetic treatment — the total cost including flights and accommodation from the UK typically saves £1,500–£3,000 versus UK private rates even for a dedicated trip, which gives a sense of the scale of the price differential. Once resident in Cyprus, the same work is available at the same prices without the travel element, making Cyprus a compelling place to catch up on deferred dental work.",
      },
    ],
  },
  {
    slug: "emergency-services-guide",
    title: "Emergency Services in Cyprus — 112, A&E, and What to Expect",
    description:
      "The single emergency number, which hospitals have 24-hour A&E, ambulance response times, what to bring, and the difference between public and private A&E for non-critical situations.",
    sections: [
      {
        heading: "112: the single emergency number",
        body: "Cyprus uses 112 as the unified emergency number for police, fire, and ambulance. Calls are answered in Greek and English; if you speak neither, the operator can typically connect a translator for major languages within a minute or two. 112 also accepts SMS for hearing-impaired callers. The call-handling centre in each district dispatches the appropriate service — police (Astynomia), fire brigade (Pyrosvestiki Ypiresia), or EKAB ambulance service — depending on the nature of the call. In practice, for medical emergencies the most important information to have ready: your exact address (include landmark references since rural addresses can be difficult to locate by number alone), the nature of the emergency, the patient's approximate age, and whether they are conscious and breathing. Cyprus police response times for non-emergency incidents have been criticized, but for genuine emergencies the dispatch system is reliable.",
      },
      {
        heading: "Ambulance response times and coverage",
        body: "EKAB (Emergency Medical Service) operates Cyprus's ambulance service with a fleet covering all districts. In urban areas — Limassol city, Nicosia center, Paphos town, and Larnaca city — average response times run 8–12 minutes for Priority 1 (life-threatening) calls. In rural and semi-rural areas, response times extend to 15–25 minutes, and in remote mountain villages (Troodos area, Marathasa valley) response can take 30–45 minutes. Every ambulance carries defibrillators, basic resuscitation equipment, and paramedic-level drug packs. For cardiac arrest, trauma, and stroke, Cyprus's protocol is to stabilize and transport directly to the nearest A&E capable of definitive treatment — the Nicosia General Hospital for central cases, Mediterranean Hospital or Limassol General for Limassol cases. If you live in a rural area, it is worth knowing where your nearest A&E is and having the address ready to give to the 112 operator, who can direct the ambulance rather than having it navigate independently.",
      },
      {
        heading: "Which hospitals have 24-hour A&E",
        body: "Each major district has at least one 24-hour A&E, and the coverage between public and private hospitals overlaps in most areas. Public hospital A&E departments: Nicosia General Hospital (Λευκωσία), Limassol General Hospital (Limassol city), Larnaca General Hospital (Larnaca city), Paphos General Hospital (Paphos town), and Famagusta General Hospital (Paralimni — serving the eastern Famagusta district). Private hospitals with 24-hour A&E capability include Mediterranean Hospital in Limassol (the largest private hospital in Cyprus, trauma-capable), Apollonion Hospital in Nicosia, and St. George's Hospital in Larnaca. The private hospitals have shorter waiting times for non-critical A&E presentations but charge significantly more — expect €150–€300 for an A&E attendance fee alone at a private hospital before treatment costs. For genuine emergencies, go to the nearest A&E regardless of public or private; for non-critical urgent care that is not appropriate for a GP, private A&E or an urgent-care clinic is typically faster and more comfortable.",
      },
      {
        heading: "What to bring and what to expect",
        body: "For any A&E visit in Cyprus, bring: your ARC or Yellow Slip, your GeSY HIO card or beneficiary number, any relevant private health insurance card or policy number, and a list of your current medications. Public A&E operates on triage — genuine emergencies are seen immediately, non-critical presentations wait. Public hospital A&E waiting times for non-critical cases can reach 3–5 hours on busy evenings and weekends, which is comparable to UK NHS experience. If you have GeSY coverage, the public A&E co-payment is €10–€15 for the visit. If you do not yet have GeSY (new arrivals in their first weeks), public A&E charges a flat fee that varies by treatment — typically €50–€150 for a non-admission A&E visit. The clinical standard at the major public hospitals has improved substantially since GeSY's introduction, which brought performance incentives. For children: Makarios Hospital in Nicosia is the main pediatric facility, with Limassol and Paphos General hospitals also having pediatric departments.",
      },
      {
        heading: "Air ambulance and serious trauma",
        body: "For life-threatening trauma — major road accidents, serious falls, severe cardiac events in rural areas — Cyprus operates an air ambulance service coordinated through the Joint Rescue Coordination Centre (JRCC). The helicopter fleet, operated in conjunction with the Cyprus Police Air Wing, can reach most parts of the island within 15–20 minutes from the Nicosia base. Air ambulance is activated by the 112 dispatcher for appropriate cases; it is not user-initiated. For international medical evacuation — if a patient requires treatment that is not available in Cyprus (specialized neurosurgery, severe burns requiring a specialist unit) — the standard destination is Athens or Tel Aviv (both under 1.5 hours by air), and the coordination goes through the GeSY emergency services or private medical evacuation insurance. Private medical evacuation insurance covering repatriation to your home country is sold by most Cyprus insurance brokers for €200–€400 per year per person and is worth considering if you have a pre-existing condition that might require specialist care not available in Cyprus.",
      },
    ],
  },
  {
    slug: "air-quality-allergens",
    title: "Air Quality and Allergens in Cyprus — A Relocator's Guide",
    description:
      "Saharan dust events, pollen seasons, wildfire smoke, where to find AQI data, and practical steps for relocators who suffer from hay fever or respiratory conditions.",
    sections: [
      {
        heading: "Cyprus's overall air quality baseline",
        body: "Cyprus's background air quality is generally good by European standards — no heavy industry, low traffic density outside Nicosia and Limassol, and prevailing Mediterranean winds that flush the atmosphere regularly. The AQI (Air Quality Index) on a typical day in Limassol, Paphos, or Larnaca sits in the 'Good' to 'Moderate' range (US AQI 0–75). Nicosia, being landlocked and surrounded by hills on three sides, has slightly more concentrated traffic pollution than the coastal cities — PM2.5 and NOx levels in the Nicosia basin during calm winter mornings can reach 'Unhealthy for Sensitive Groups'. The exceptions to the good baseline are episodic: Saharan dust events, high pollen periods in spring, and wildfire smoke in late summer. These episodes are predictable by season and manageable with preparation. Cyprus does not have the chronic air quality issues of northern European industrial areas or major Asian cities; it is not a place where an asthmatic would be worse off than in the UK or Germany on a typical day.",
      },
      {
        heading: "Saharan dust events: timing and impact",
        body: "Saharan dust (khamsin or scirocco events) crosses Cyprus primarily in two windows: March–April and September–October. These events bring significant PM10 spikes — levels can reach 200–400 μg/m³ during strong events, well above the WHO guideline of 45 μg/m³ for 24-hour average. During a strong dust event, the sky turns orange-brown, cars acquire a layer of reddish dust overnight, and outdoor exercise is genuinely inadvisable for anyone with respiratory conditions. Events typically last 1–4 days. The forecast is usually reliable 24–48 hours in advance; the Cyprus Department of Labour Inspection publishes real-time air quality data and dust alerts at airquality.gov.cy. The practical response: close windows, run an air purifier if you have one, reschedule intense outdoor exercise, and keep inhalers accessible if relevant. Strong dust events are memorable the first time you experience one; after that they are a normal part of the Cyprus seasonal calendar.",
      },
      {
        heading: "Pollen seasons: the major offenders",
        body: "Cyprus has two pollen seasons that affect a significant proportion of hay fever sufferers: the cypress tree season (February–March) and the olive tree season (March–May). Cypress pollen is considered one of the most allergenic in the Mediterranean region — the density of Italian and Leyland cypress planted as windbreaks and ornamental trees throughout Cyprus creates genuinely high airborne concentrations during peak season. Allergists see a significant increase in new diagnoses among relocators who had no prior hay fever symptoms in northern Europe; Cyprus cypress pollen appears to sensitise many people who were previously asymptomatic. Olive tree pollen follows in March and peaks through May — olive groves are widespread inland and the pollen is light enough to travel significant distances. If you are already a hay fever sufferer, consult an allergist in your first year to identify your specific triggers; skin-prick testing in Cyprus is available privately and costs €80–€150. Cetirizine and loratadine antihistamines are available OTC without prescription at all pharmacies.",
      },
      {
        heading: "Wildfire smoke: July to August",
        body: "Cyprus experiences wildfires most years, predominantly in July and August when vegetation is at maximum dryness and temperatures are highest. The 2021 Moni wildfire (one of the deadliest in Cyprus's history) and the 2023 Paphos district fires demonstrated that smoke from significant fires can blanket large areas for several days, with AQI spiking into the 'Unhealthy' range (US AQI 150+) for populated areas downwind. The risk is highest in areas adjacent to pine forest — the Troodos foothills around Moniatis, the area between Paphos and Polis, and parts of the Larnaca hinterland. Coastal city centers typically experience lighter smoke exposure since sea breezes provide some dilution. During active fire events, the Cyprus Fire Service (cyprusfire.gov.cy) updates the public on risk zones; the JRC European Forest Fire Information System (effis.jrc.ec.europa.eu) provides a wider regional picture. For households near fire-risk areas, having N95 masks available and knowing the nearest shelter-in-place advice is practical preparedness.",
      },
      {
        heading: "Monitoring tools and air purifier recommendations",
        body: "For real-time air quality data, the primary source is airquality.gov.cy (Cyprus Department of Labour Inspection) which provides hourly PM2.5, PM10, NO2, O3, and SO2 data from monitoring stations in Nicosia, Limassol, Larnaca, and Paphos. For pollen-specific forecasting, the European Aeroallergen Network (polleninfo.org) covers Cyprus with daily pollen forecasts. For daily practical use, the IQAir app and PurpleAir map include Cyprus sensors and provide hyperlocal readings. For air purifiers: a HEPA-filter unit sized appropriately for your living space is effective for both PM2.5 and pollen. Units from Blueair, Coway, or Levoit in the €150–€400 range are appropriate for a standard apartment room (25–40 m²). Given Cyprus dust events and the pollen season overlap in March–April, a unit in the bedroom is the highest-impact placement. Replacement HEPA filters are available from electronics retailers in Cyprus (MediaMarkt Nicosia and Limassol) and online via Amazon.de with 3–5 day delivery.",
      },
    ],
  },
  {
    slug: "driving-licence-conversion",
    title: "Converting Your Driving Licence to a Cyprus Licence",
    description:
      "EU licences, reciprocal-agreement countries, non-reciprocal countries that require a test, documents required, Traffic Department offices, timeline, and cost. Prices and rules change — verify with official Cyprus sources before acting.",
    sections: [
      {
        heading: "EU licences: no exchange required",
        body: "If you hold a driving licence issued by any EU or EEA member state, you do not need to exchange it for a Cyprus licence. Your EU licence is valid for driving in Cyprus indefinitely — there is no legal requirement to convert it to a Cyprus licence simply because you are now a Cyprus resident. However, there is one practical exception: if your EU licence is due to expire, you should renew it. An expired EU licence is not valid in Cyprus, and the renewal must be handled by the issuing country's authority (you cannot renew a German or French licence at the Cyprus Traffic Department). The Cyprus Traffic Department can register your EU licence on the Cypriot system — a voluntary step that creates a Cyprus record and can simplify administrative processes (e.g., traffic fines, insurance documentation) — but registration is not the same as mandatory exchange, and the practical benefit is minor for most people. If your EU licence categories do not include driving categories you need (motorcycle, HGV), those additions require tests in Cyprus at normal rates.",
      },
      {
        heading: "Non-EU countries with reciprocal agreements",
        body: "Cyprus has bilateral driving licence exchange agreements with a number of non-EU countries, allowing direct conversion without a test. The countries with reciprocal arrangements as of 2025 include: the United Kingdom, the United States, Canada, Australia, Switzerland, and South Africa. Under a reciprocal agreement, you surrender your foreign licence and the Cyprus Traffic Department issues a Cyprus licence in exchange — no written test, no driving test. This is a genuine exchange: your original foreign licence is typically retained by the Traffic Department (or returned cancelled), so you cannot hold both simultaneously. Verify the current list at the Traffic Department's official page (mcw.gov.cy) before assuming your country is included — agreements can be added or the specific terms can change. The UK's inclusion post-Brexit (the reciprocal agreement survived the UK's EU exit) is confirmed for UK residents, making the exchange process smooth for the large British community in Cyprus.",
      },
      {
        heading: "Non-reciprocal countries: the test route",
        body: "If your home country does not have a reciprocal agreement with Cyprus (examples include Israel, the UAE, India, Russia, China, and most African and Asian countries not listed above), you cannot convert directly — you must pass the Cyprus driving theory test and the practical driving test to obtain a Cyprus licence. The theory test is administered by the Cyprus Traffic Department in multiple languages including English, Greek, Russian, and Arabic. The test covers 30 questions on the Highway Code and road signs, with a pass mark of 27/30; most well-prepared candidates pass first time. The practical test is a 25-minute on-road assessment with a Traffic Department examiner. A Cyprus-registered driving school can provide preparation lessons (typically €25–€40 per hour) and their cars are used for the test. Theory test booking is done online; practical tests are typically booked 2–4 weeks ahead. Total cost including preparation and fees: approximately €150–€300. While you are preparing for the test, your foreign licence is valid in Cyprus for 6 months after you become a resident — do not let this window expire before you have booked your tests.",
      },
      {
        heading: "Documents required for the exchange",
        body: "For a reciprocal-agreement exchange, bring to the Traffic Department: your original foreign driving licence, your ARC (Alien Registration Certificate) or Yellow Slip, your passport, two recent passport-sized photographs (35mm x 45mm, white background), and a completed application form (available at the office). For the full test route (non-reciprocal countries), the same documents are required plus a medical certificate from a Cyprus GP confirming fitness to drive (a standard document that most GPs issue at a check-up visit for €20–€30). The medical certificate requirement applies to all applicants over 65 regardless of nationality. A certified translation of your foreign licence is required if it is not in Greek, English, or a Latin alphabet — translations cost €30–€50 at certified translation agencies; the Traffic Department maintains a list of approved translators. Do not arrive without all documents: the Traffic Department will not process partial applications and a second visit resets the queue.",
      },
      {
        heading: "Traffic Department offices, timeline, and cost",
        body: "Traffic Department offices that handle driving licence applications are located in all five district capitals: Nicosia (main office, Athalassa Avenue), Limassol (Omonia Avenue office), Larnaca (Artemidos Avenue), Paphos (Neofytou Nikolaidi Street), and Famagusta (Paralimni office serving the eastern district). Appointments can be booked online via the Cyprus e-Government portal (eservices.gov.cy) or by phone; walk-in availability exists but is limited in peak periods. For a reciprocal exchange, the processing time from application submission to receiving the Cyprus licence is typically 4–8 weeks — the licence is printed centrally and posted to your registered address. For the test route, add the testing period to this timeline. Cost breakdown for a reciprocal exchange: application fee approximately €50–€70 (fees are reviewed annually), plus document translation if needed. There is no additional fee for the physical licence card. Keep a copy of your application receipt — the Traffic Department receipt serves as temporary proof of an in-progress application if you are stopped by police before the new licence arrives.",
      },
    ],
  },
];
