import type { GuideInfo } from "./guides";

/**
 * SEO content batch 5 (July 2026) — research-backed guides.
 * Employment, marriage and school-fees guides for relocating families.
 */
export const GUIDES_BATCH5: GuideInfo[] = [
	{
		slug: "working-in-cyprus-employee-rights",
		datePublished: "2026-07-14",
		dateModified: "2026-07-14",
		category: "business",
		title: "Employee Rights in Cyprus (2026 Guide)",
		description:
			"Minimum wage, annual leave, notice periods, social insurance and the 13th salary — a plain-English guide to Cyprus employment law for expats.",
		sections: [
			{
				heading: "Your Employment Contract and Minimum Terms",
				body: "Under the Transparent and Predictable Working Conditions Law of 2023, every employer in Cyprus must provide a written statement of employment terms within seven days of your start date. For EU nationals this is a straightforward administrative step; if you are arriving from outside the EU, it sits alongside your immigration documentation — see the yellow-slip-meu1-guide for details on the registration certificate you will need.\n\nYour written contract must specify at minimum: the names of both parties, your start date, place of work, job title or description, pay and pay frequency, working hours, and applicable notice periods. It should also identify any relevant collective agreement, because certain sectors — banking, retail, the semi-government sector — operate under collective agreements that grant benefits beyond the statutory floor.\n\nCyprus law draws a clear line between what parties can and cannot negotiate away. Any contractual term that gives you fewer rights than the statutory minimum is void; the statutory minimum applies automatically in its place. This covers annual leave, notice periods, and minimum pay — all addressed in the sections below.\n\nIf anything in your contract is unclear or appears to conflict with what you were told verbally, the Department of Labour Relations (part of the Ministry of Labour and Social Insurance) offers free guidance and handles formal complaints. Keep signed copies of every version of your contract and any written variation. Before you sign, ask whether a collective agreement applies in your sector — it may improve significantly on the statutory floor for pay, hours, or leave.",
			},
			{
				heading: "Pay, Minimum Wage and the 13th Salary",
				body: "From 1 January 2026, Cyprus operates a two-tier national minimum wage. Employees in their first six months with an employer are entitled to at least €979 gross per month for full-time work. After completing six months of continuous service with the same employer, the minimum rises to €1,088 gross per month. These rates were set by a Council of Ministers decree in December 2025.\n\nImportant exclusions apply: workers in hotels and catering, domestic employment, agriculture, and maritime work fall outside this regime and are governed instead by sector-specific legislation or collective agreements. If your role falls into one of these categories, verify the applicable minimum with the Department of Labour Relations or your sector union.\n\nThe 13th salary is not mandated by statute for the private sector as a whole — but in practice a large majority of full-time employees in Cyprus receive one. It becomes legally obligatory in three situations: your employment contract explicitly provides for it; your sector collective agreement requires it; or your employer has paid it consistently enough to create an implied contractual right under the Protection of Wages Law. Cyprus labour courts have repeatedly upheld this implied-right principle.\n\nWhen paid, the 13th salary typically amounts to one month of base pay, split in two halves — roughly half before the summer holidays (often June) and half before Christmas (typically mid-to-late December). A small minority of employers, chiefly in banking and the unionised semi-government sector, also pay a 14th salary. Clarify the position in writing before you accept any job offer.",
			},
			{
				heading: "Working Hours, Overtime and Annual Leave",
				body: "The Organisation of Working Time Law implements the EU Working Time Directive in Cyprus and sets a hard ceiling of 48 hours per week — including overtime — averaged over a four-month reference period. This means that while busier weeks are permissible, your average over any four-month window must not exceed 48 hours. Most full-time contracts specify 38 to 40 hours; 40 hours per week is the de facto standard across private-sector employment.\n\nOvertime — work beyond your contracted hours — is generally compensated at a premium on your normal hourly rate, and work on Sundays and public holidays typically attracts a higher rate again; exact terms depend on your contract or the applicable collective agreement. You are also entitled to a minimum of 11 consecutive hours of rest in every 24-hour period and at least one uninterrupted 24-hour rest period each week.\n\nOn annual leave, the Annual Holidays with Pay Law entitles every employee to at least 20 working days of paid leave per year on a five-day-week pattern, or 24 working days on a six-day-week pattern. Leave begins to accrue after a qualifying period of continuous employment with the same employer. By mutual agreement, unused leave may be carried over — it cannot simply be forfeited or paid out in lieu while employment continues. Cyprus also observes roughly 14 public holidays per year (the precise count can vary slightly with government proclamations); these are paid days off that sit outside your annual leave entitlement.\n\nFor a net-pay breakdown on your salary, use the social-insurance-calculator at /tools/social-insurance-calculator alongside the taxes-for-expats guide.",
			},
			{
				heading: "Social Insurance and GHS Deductions",
				body: "Every employed person in Cyprus must contribute to two statutory schemes, and both appear on your payslip as deductions.\n\nFirst, the Social Insurance Fund: employees pay 8.8% of gross salary, matched by an equal 8.8% from the employer. Second, the General Health System (GHS/GeSY): employees pay 2.65% of gross salary, with employers paying 2.9%. Your combined statutory employee deduction is therefore approximately 11.45% of gross pay.\n\nBoth schemes apply to capped earnings. For Social Insurance, the maximum insurable earnings cap for 2026 is in the region of €68,900 per year (around €5,740 per month) — confirm the current-year figure with the Social Insurance Services, as it is revised annually. Once your earnings exceed this cap in a calendar year, no further Social Insurance is deducted for the remainder of that year. The GHS cap is €180,000 per year, which the vast majority of employees will not reach.\n\nYour employer also pays additional contributions that do not appear as deductions on your payslip but form part of your total employment cost: a Social Cohesion Fund levy, a Redundancy Fund contribution, and a Human Resource Development levy. These are the employer's cost, not yours, but they explain why your total cost to the company is higher than your gross salary.\n\nIncome tax is calculated separately; non-domiciled residents may qualify for significant exemptions — see the taxes-for-expats guide. If you are considering self-employment rather than employment, contribution rates and rules differ substantially — see the self-employed-tax-cyprus guide. For a live take-home pay calculation on any gross salary, use the social-insurance-calculator at /tools/social-insurance-calculator.",
			},
			{
				heading: "Notice Periods, Probation and Termination",
				body: "The Transparent and Predictable Working Conditions Law of 2023 introduced a general rule that probationary periods should not exceed six months. During a valid probationary period, an employer may dismiss you without giving a reason and without serving a notice period — but dismissal remains unlawful if it is discriminatory, retaliatory, or in breach of other mandatory protections such as those covering pregnancy.\n\nOnce you have completed 26 weeks of continuous employment, you gain statutory protection against unfair dismissal. After that threshold, minimum statutory notice scales with your length of service under the Termination of Employment Law:\n\n26–51 weeks of service: 1 week\n52–103 weeks (1–2 years): 2 weeks\n104–155 weeks (2–3 years): 4 weeks\n156–207 weeks (3–4 years): 5 weeks\n208–259 weeks (4–5 years): 6 weeks\n260–311 weeks (5–6 years): 7 weeks\n312 weeks or more (6+ years): 8 weeks\n\nYour contract may specify longer notice periods, which take precedence; no contract may reduce the statutory minimums. Employers may offer payment in lieu of notice rather than requiring you to work the full period. Unfair dismissal claims must be filed with the Industrial Disputes Tribunal within a limited window (commonly cited as 12 months) of the termination date.\n\nIf you are made redundant after at least 104 weeks (two years) of continuous employment, you may be entitled to a redundancy payment from the state Redundancy Fund rather than directly from your employer. Compensation scales with tenure and is subject to statutory weekly wage limits. Consult the Department of Labour Relations or a qualified employment lawyer to confirm your eligibility and the applicable amount.",
			},
			{
				heading: "Maternity, Paternity and Other Leave",
				body: "Cyprus provides statutory leave well beyond annual holidays.\n\nMaternity leave lasts 18 weeks in total, with a compulsory portion around the birth. Part of the leave may be taken before your expected due date. Maternity benefit is funded by the Social Insurance Fund rather than your employer, and is subject to your contributions history and statutory rate limits. Pregnant employees and those on maternity leave are strongly protected from dismissal; redundancy during this period is unlawful except in very limited circumstances. In the case of multiple births, premature delivery, or medical complications, additional leave may be granted on production of a medical certificate.\n\nPaternity leave entitles fathers to two consecutive weeks of paid leave, to be taken around the child's birth. Eligibility generally requires a period of continuous employment with the current employer. Paternity benefit is also paid through the Social Insurance Fund.\n\nParental leave allows each parent a block of unpaid leave per child for children under eight years of age (or older where the child has a disability), with a cap on how much may be taken in any single year. This leave is unpaid at the statutory level, though some collective agreements or individual contracts provide for partial pay — check your contract and any applicable collective agreement.\n\nOn sick leave, your employer is typically responsible for the first days of any absence, after which the Social Insurance Fund pays sickness benefit (subject to medical certification and contribution requirements) up to a statutory maximum per illness.\n\nFor day-to-day healthcare access under the General Health System, ensure your GHS registration is in order — the yellow-slip-meu1-guide covers the registration process for EU and non-EU arrivals alike.",
			},
		],
		faqs: [
			{
				q: "Is the 13th salary mandatory in Cyprus?",
				a: "Not by statute for most private-sector workers. It becomes legally obligatory in three situations: your employment contract explicitly provides for it; your sector collective agreement requires it; or your employer has paid it consistently enough over the years to create an implied contractual right under the Protection of Wages Law. Cyprus labour courts have upheld this implied-right principle repeatedly. Before accepting a job offer, ask in writing whether a 13th salary is paid, on what basis, and when — and get the answer included in your contract.",
			},
			{
				q: "When do I gain unfair dismissal protection?",
				a: "Statutory protection under the Termination of Employment Law begins after 26 weeks (approximately six months) of continuous employment with the same employer. The 2023 Transparent and Predictable Working Conditions Law also set a general six-month cap on probationary periods. During a valid probationary period, an employer may dismiss you without giving a reason or serving notice — but dismissal that is discriminatory or retaliatory is unlawful at any stage of employment. Claims are filed with the Industrial Disputes Tribunal within the statutory time limit from the termination date.",
			},
			{
				q: "How much will be deducted from my salary for social insurance and health?",
				a: "Employees pay 8.8% of gross salary to the Social Insurance Fund and 2.65% to the General Health System (GHS/GeSY), totalling approximately 11.45% combined. The Social Insurance deduction applies only up to a maximum insurable earnings cap (in the region of €68,900 per year for 2026) — once you pass this annual cap, no further Social Insurance is deducted for the rest of that calendar year. The GHS deduction applies up to €180,000 per year. Income tax is calculated separately. Use the social-insurance-calculator at /tools/social-insurance-calculator for a live net-pay breakdown on any gross figure.",
			},
			{
				q: "What is the national minimum wage in Cyprus in 2026?",
				a: "From 1 January 2026, the minimum is €979 gross per month for employees in their first six months with an employer, rising to €1,088 gross per month after six months of continuous service with that employer. These rates were set by a Council of Ministers decree in December 2025. Workers in hotels and catering, domestic service, agriculture, and maritime employment are excluded from this regime and covered by sector-specific rules or collective agreements. The figures apply to full-time employment; part-time minimum pay is pro-rated.",
			},
		],
	},
	{
		slug: "getting-married-in-cyprus",
		datePublished: "2026-07-14",
		dateModified: "2026-07-14",
		category: "family",
		title: "Getting Married in Cyprus (2026 Guide)",
		description:
			"How to get married in Cyprus in 2026: civil ceremony steps, required documents, ordinary vs special licence, fees and same-sex civil partnerships.",
		sections: [
			{
				heading: "Why Couples Choose Cyprus — and Who Can Marry There",
				body: "Cyprus is one of Europe's most popular wedding destinations, and it is easy to understand the appeal. The island offers a warm Mediterranean climate, photogenic settings ranging from clifftop sea views to whitewashed village squares, and — crucially — a legal framework that is genuinely open to couples from anywhere in the world. Unlike many countries, Cyprus imposes no minimum residency requirement for a civil marriage: neither party needs to have lived on the island beforehand. All that is required is that both partners are physically present in Cyprus when they attend the Marriage Officer at their chosen municipality.\n\nAny two people aged 18 or over who are not closely related, not already married, and are capable of giving free consent may marry in Cyprus under the Marriage Law of 2003. Those aged 16 or 17 may also marry with the written consent of a parent or legal guardian. Couples need not be Cypriot citizens, EU nationals, or even long-term residents — tourists on a short holiday may apply. Foreign nationals are free to choose any municipality on the island, and ceremonies can be conducted in English or Greek.\n\nFor those wishing to marry in a Greek Orthodox church, at least one partner must be a baptised Orthodox Christian; contact the relevant parish or the Church of Cyprus well in advance, as the church has its own documentation requirements separate from the civil procedure. This guide focuses on the civil route, which is by far the most popular choice among international couples and expat residents alike — whether they have just arrived on the island or are long-settled.",
			},
			{
				heading: "Ordinary vs Special (Express) Marriage Licence",
				body: "Once you and your partner have arrived in Cyprus and submitted your Notice of Marriage to the Marriage Officer at your chosen municipality, the Marriage Law offers two procedural pathways: the ordinary (standard) route and the special (express) licence route.\n\nUnder the ordinary procedure, a minimum of 15 clear days must pass between the submission of your Notice of Marriage and the date of the ceremony. This public notice period is a statutory safeguard giving any person who knows of a lawful impediment the opportunity to come forward. The ceremony may take place any time from day 16 up to three months after the notice is lodged; if the three-month window lapses without a ceremony, you must reapply from the beginning. The government fee for the ordinary procedure is approximately €128.\n\nUnder the special (express) licence procedure, couples may apply to the Marriage Officer for an abbreviated process that can allow the ceremony to take place as soon as the next working day, and typically within two to three working days. This is the most popular choice for destination couples with limited time on the island. The government fee for the special licence is approximately €282, reflecting the additional administrative steps involved.\n\nBoth figures are subject to change and can vary between municipalities. An additional surcharge (commonly cited at around €130) may apply for ceremonies held on Saturdays or outside normal working hours. Always confirm the exact current fee schedule directly with the municipal office you choose before finalising your plans.",
			},
			{
				heading: "Documents You Need — Apostille and Translation",
				body: "Gathering the correct documentation well in advance is the most time-consuming part of the process, particularly for couples coming from outside Cyprus. Both parties must present original documents; photocopies are not accepted. The core requirements are as follows.\n\nValid passports: both parties need a valid passport — the same one used to enter Cyprus. Ensure your passport remains valid well beyond your ceremony date; check the specific requirement with your municipality.\n\nFull birth certificates: these must name both parents. Any birth certificate issued outside Cyprus must be apostilled (authenticated under the 1961 Hague Convention) by the issuing country and, in most cases, officially translated into Greek by a certified translator in Cyprus.\n\nCertificate of No Impediment (CNI) or single-status certificate: each party must provide an official document from their home country confirming they are free to marry. British nationals typically obtain a statutory declaration sworn before a UK solicitor, or a CNI issued through the General Register Office. CNIs are generally valid for a limited period (often cited as around twelve weeks) from the date of issue, so time your application carefully. These documents must also be apostilled and translated where required.\n\nDivorce decree or death certificate: if either party has previously been married, you must present the document legally ending that marriage — a decree absolute in the case of divorce, or a death certificate in the case of widowhood — again with apostille and certified translation.\n\nIt is advisable to engage a Cyprus-based wedding planner or legal professional to verify your document pack meets the requirements of your chosen municipality before you travel, as individual offices occasionally request additional supporting material.",
			},
			{
				heading: "The Step-by-Step Process and Fees",
				body: "With your documents prepared, here is how the civil marriage process unfolds in practice.\n\nStep 1 — Prepare documents at home (six to twelve weeks before the ceremony). Obtain apostilled and translated versions of all required certificates. Allow generous lead time: apostille services and certified translations can each take several weeks, and your Certificate of No Impediment may only be valid for a limited window.\n\nStep 2 — Arrive in Cyprus. Both parties must be physically present on the island before any application can be made. There is no prescribed waiting period between your arrival and lodging the notice.\n\nStep 3 — Attend the Marriage Officer together. Go in person to the municipal offices of your chosen town. Popular choices include Limassol, Paphos, and Larnaca, each of which has dedicated civil-wedding arrangements. Both of you must attend, present all original documents, and sign the joint Notice of Marriage, making a sworn declaration that no lawful impediment exists.\n\nStep 4 — Wait out the notice period. For the ordinary procedure, this is a minimum of 15 clear days. For the special licence, the ceremony can typically proceed within one to three working days — confirm the precise timeline with your municipality.\n\nStep 5 — The ceremony. The civil ceremony is brief — typically ten to fifteen minutes — and can be conducted in English or Greek. At least two adult witnesses must be present to sign the marriage register.\n\nStep 6 — Collect your marriage certificate. The Marriage Officer issues this on or shortly after the ceremony. Certified copies can also be obtained from the authorities at a later date for a small fee.",
			},
			{
				heading: "Same-Sex Civil Partnerships in Cyprus",
				body: "Cyprus was the first country in the Eastern Mediterranean to formalise same-sex unions in law. The Civil Partnership (Civil Union) Law came into force in December 2015 and applies equally to same-sex and opposite-sex couples who choose civil partnership as the legal form of their union.\n\nUnder the law, civil partners enjoy rights broadly equivalent to those of married couples. Any law referring to spouses is generally to be interpreted as extending to registered partners. Rights covered include inheritance, pension and social security entitlements, hospital visitation, and recognition in tax and housing matters, among others. The principal statutory exception is adoption: civil partners in Cyprus do not currently hold the same joint-adoption rights as married couples.\n\nThe registration procedure for a civil partnership follows a similar administrative pathway to civil marriage but is typically handled at District Offices rather than municipalities. Both parties must appear in person, present valid passports, birth certificates, a certificate confirming single status (apostilled and translated where required), and any relevant divorce or death documentation.\n\nThere is no minimum residency requirement: tourists visiting Cyprus may also register a civil partnership. It is worth noting that Cyprus does not currently recognise same-sex marriage itself, and civil partnerships registered in other countries are not automatically treated as a Cyprus civil partnership. Couples should take legal advice in their home jurisdiction to understand how a Cyprus civil partnership will be recognised there.",
			},
			{
				heading:
					"After the Wedding — Certificate, Recognition Abroad and Name Change",
				body: "The Marriage Officer will issue your official Cyprus marriage certificate at or shortly after the ceremony. The certificate is issued in Greek; if you need an English translation — for example, to register the marriage in your home country — commission a certified translation from a sworn translator in Cyprus before you leave the island.\n\nA Cyprus civil marriage is a legally valid marriage under the law of the Republic of Cyprus, an EU member state. It is generally recognised throughout the European Union and in most countries worldwide. However, recognition is not automatic everywhere. Many countries require you to register or notify a local civil registry, consulate, or government authority on your return. British nationals should consult the General Register Office and the Foreign, Commonwealth and Development Office for guidance on registering an overseas marriage; US nationals should contact the State Department or their nearest embassy. Obtaining an apostille on your Cyprus marriage certificate before leaving the island can simplify this process considerably.\n\nFor those relocating to Cyprus after the ceremony and needing to understand how married status affects residency documentation, the yellow-slip-meu1-guide covers registration for EU nationals, and the moving-to-cyprus-from-uk guide addresses documentation for British nationals specifically.\n\nFor name changes, the procedure varies by nationality. You will typically need certified copies of your marriage certificate — and in some cases an apostilled, translated version — to update your passport, driving licence, bank accounts, and employer records. If you hold a private health insurance policy on the island, the private-health-insurance-cyprus guide is a useful reference when notifying your insurer of a name or marital-status change.",
			},
		],
		faqs: [
			{
				q: "Do I need to live in Cyprus before I can get married there?",
				a: "No. Cyprus has no minimum residency requirement for a civil marriage. Both parties simply need to be physically present in Cyprus to attend the Marriage Officer together and submit the Notice of Marriage. Tourists on a short holiday may apply.",
			},
			{
				q: "How long do I need to stay in Cyprus for the whole process?",
				a: "It depends on the procedure. With the ordinary notice, a minimum of 15 clear days must pass between submitting your Notice of Marriage and the ceremony — so allow around three weeks in total. With the special (express) licence, the ceremony can often proceed within one to three working days of lodging the notice, making a stay of roughly one week sufficient. Confirm the exact timeline with your chosen municipality.",
			},
			{
				q: "Can I skip the 15-day waiting period?",
				a: "Yes, by applying for the special (express) licence at the time you submit your Notice of Marriage. This typically allows the ceremony to proceed within one to three working days rather than after 15 clear days. The government fee is approximately €282 for the special licence, compared with approximately €128 for the ordinary procedure. Confirm current fees directly with the municipality, as they are subject to change.",
			},
			{
				q: "What is a Certificate of No Impediment and where do I get one?",
				a: "A Certificate of No Impediment (CNI) — also called a single-status certificate or freedom-to-marry certificate — is an official document from your home country confirming you are legally free to marry. British nationals can obtain one from the General Register Office or by swearing a statutory declaration before a UK solicitor. The CNI must be apostilled and, if not in English or Greek, officially translated by a certified translator. CNIs are typically valid for a limited period from the date of issue, so plan your application timeline accordingly.",
			},
			{
				q: "Do both partners need to attend in person to give notice?",
				a: "Yes. Both parties must appear together in person before the Marriage Officer at the chosen municipality to sign the joint Notice of Marriage and make their sworn declarations. This step cannot be completed by a representative or proxy.",
			},
			{
				q: "Can same-sex couples marry or form a civil partnership in Cyprus?",
				a: "Cyprus does not currently recognise same-sex marriage. However, same-sex couples may register a civil partnership under the Civil Partnership Law. This confers rights broadly equivalent to marriage — including in inheritance, social security, and tax matters — with the exception of joint adoption rights. Both residents and tourists may register a civil partnership, and the process is typically handled at District Offices rather than municipalities.",
			},
			{
				q: "Will my Cyprus marriage be recognised in my home country?",
				a: "In most cases, yes. A Cyprus civil marriage is valid under EU law and is widely recognised internationally. However, your home country may require you to register the marriage with a local civil registry or government authority on your return. British nationals should check with the General Register Office; US nationals should consult the State Department or their nearest embassy. Obtaining an apostille on your Cyprus marriage certificate before you leave the island will make this registration process easier.",
			},
		],
	},
	{
		slug: "international-school-fees-cyprus",
		datePublished: "2026-07-14",
		dateModified: "2026-07-14",
		category: "family",
		title: "International School Fees in Cyprus (2026)",
		description:
			"Annual tuition ranges, hidden extras and city-by-city costs for expat families choosing a private or international school in Cyprus in 2026.",
		sections: [
			{
				heading: "What International School Really Costs",
				body: "The headline figure most parents ask about is annual tuition, and in Cyprus it varies enormously — from roughly €4,000 in nursery at a modestly priced English-medium school to well over €19,000 at a senior International Baccalaureate school. As a broad planning guide, indicative annual tuition bands are: early years (nursery and kindergarten) roughly €4,000–€7,500; primary (ages 6–11) approximately €5,500–€10,000, rising year by year; lower secondary approximately €7,500–€12,000; and upper secondary or sixth form approximately €9,000–€14,000, or significantly higher at full IB-continuum schools.\n\nThese bands have risen noticeably since 2022, driven in large part by a substantial wave of relocating families from Russia, Ukraine, Israel, and Western Europe, which has expanded demand sharply across the island. Limassol has felt this most acutely, but Paphos has also seen increased competition for places and upward pressure on fees.\n\nEvery school sets its own fee schedule, updates it each year, and charges different rates by year group. The figures above are deliberately broad indicative ranges, not quoted prices, and fees change annually. Before committing to any school, always request the current published fee schedule directly from the admissions office — do not rely on third-party listings, which may be out of date.\n\nPublic school is free and covers school-age children, but instruction is predominantly in Greek; the international-vs-public-school guide explains when the state system is a realistic option for expat children. The school-finder tool at /tools/school-finder lets you filter by city and school stage to build a shortlist before you begin approaching schools.",
			},
			{
				heading: "Fees by City: Limassol, Larnaca and Paphos",
				body: "Limassol has the island's densest cluster of English-medium private schools. Heritage Private School (Palodia) is indicatively €7,000–€13,500 depending on stage. Foley's (Agios Athanasios) sits broadly in the €7,500–€12,600 range. The Grammar School Limassol is approximately €7,500–€9,500. Logos School of English Education is among the more affordable options, broadly €3,000–€7,500. The Island Private School — a leading full IB Continuum school — charges significantly more, with senior fees rising to around €16,000–€19,000.\n\nIn Paphos, the International School of Paphos is the most established option, known for competitive fees relative to quality. Lumio Private School, which opened recently and holds IB authorisation, is indicatively €8,500–€14,000. TLC Private School (Peyia) is broadly €4,000–€8,500. In Larnaca, the American Academy and PASCAL serve the expat community. All figures above are approximate — contact each school directly for its current fee schedule.",
			},
			{
				heading: "Beyond Tuition: The Hidden Extras",
				body: "Tuition is the starting point, not the full bill. Families regularly discover several layers of additional cost once they receive a complete fee schedule, and the gap between headline tuition and actual annual spend can be substantial.\n\nRegistration and deposits: most schools charge a non-refundable application or assessment fee (typically in the low tens to low hundreds of euros depending on year group), followed by an enrolment deposit on acceptance (often several hundred euros). Deposits may be recoverable at the end of schooling but are commonly forfeited if you withdraw without adequate notice — always read the withdrawal and notice policy carefully before paying a deposit or signing any agreement.\n\nUniforms: most English-medium private schools require a full branded uniform including sports kit. First-year outlay can easily be €200–€500 or more, with items needing replacement as children grow. Some schools supply uniforms in-house; others use approved external suppliers.\n\nSchool transport: a school bus pass typically costs in the range of €800–€2,000 a year depending on route and provider, and is a significant fixed cost for families not within walking distance.\n\nLunches and canteen: some schools include canteen access in the fee structure; others charge separately at a few euros per day.\n\nExternal examination entries: at IGCSE, A-level, or IB level, families typically pay a per-subject entry fee. A student sitting eight to ten subjects can face several hundred to a couple of thousand euros in examination costs in an exam year.\n\nSchool trips, residential visits, and after-school clubs are charged on top. When these are added up, total annual spend routinely runs 15–30% above the headline tuition figure — a material difference that should be factored into any budget from the outset.",
			},
			{
				heading: "Curricula and What You Are Paying For",
				body: "The curriculum on offer is a key driver of both fees and school culture. Understanding what you are buying explains why two schools in the same city can differ by several thousand euros a year.\n\nThe British Cambridge pathway — IGCSEs in Years 10 and 11 followed by A-levels in Years 12 and 13 — is by far the most common model in Cyprus. Schools following this route prepare students well for UK universities and are understood by admissions offices across Europe and internationally. Most of the schools named in this guide follow this pathway, either via Cambridge International or Edexcel as the examining board.\n\nThe International Baccalaureate (IB) is available at a smaller number of authorised schools, including The Island Private School in Limassol, PASCAL International Education, and Lumio Private School in Paphos. The IB Diploma is globally recognised and particularly valued by North American universities, but it carries a meaningful premium — schools commonly add a specific IB surcharge on top of regular sixth-form tuition for the Diploma years.\n\nAmerican curricula are offered at American Academy branches in Limassol and Larnaca — a good fit for families on the US college-preparation track.\n\nSeveral schools combine the British pathway with the Cypriot Apolytirion certificate, which is required for entry to local universities, and add Greek and local subjects to the timetable. The schools-in-cyprus guide covers individual school characteristics and admissions processes in further detail.",
			},
			{
				heading: "Waiting Lists, Capacity and Applying Early",
				body: "Demand for English-medium private schooling in Cyprus — particularly in Limassol — has outpaced the supply of places in recent years, and families who arrive without a confirmed school offer can face weeks or months of uncertainty.\n\nLimassol is where competition is fiercest. The city absorbed the largest share of the post-2022 relocation wave, and popular year groups — particularly early secondary years at well-regarded schools — can fill rapidly. Heritage, Foley's, and The Grammar School Limassol have all seen pressure in sought-after year groups. Some smaller, lower-fee schools are traditionally oversubscribed to such a degree that very early registration is the norm; long waiting lists in certain year groups are well documented, and one newer school reportedly had a queue of parents seeking enrolment within its first year of opening.\n\nNewer schools and expanded campuses have added capacity across the island, but demand continues to run ahead of supply, particularly at secondary level.\n\nThe advice from admissions offices and relocation specialists is consistent: apply as early as possible, ideally nine to twelve months before your target September entry. If you are relocating to Limassol, apply before you have confirmed housing — schools generally accept applications based on intended area of residence. Apply to two or three schools simultaneously, as you can only accept one offer.\n\nFor mid-year moves, places are harder still; mid-year admission is at each school's discretion. The school-finder tool at /tools/school-finder, alongside the best-areas-to-live-cyprus guide, can help you align neighbourhood choice with school availability from the outset.",
			},
			{
				heading: "Budgeting and Paying Fees",
				body: "Most English-medium private schools in Cyprus offer structured payment options rather than requiring full annual tuition upfront. Common arrangements include payment in two instalments (typically September and January), three instalments (September, December, and March), or monthly payments across the nine-month school year. Some schools extend this to twelve equal monthly payments. Many schools grant a modest early-payment discount — often around 2–3% — for full annual settlement by a deadline in late summer.\n\nSibling discounts are widespread: a second child typically attracts a reduction on tuition and a third child a larger reduction again, though policies vary between schools. It is worth asking the admissions office for the full sibling discount schedule before committing, particularly if you have two or more children of school age.\n\nTo build a realistic first-year budget, start with annual tuition and add: registration and assessment fees (one-off), the enrolment deposit, annual transport, uniform (front-loaded in year one), canteen lunches, after-school clubs and activities, and — from secondary level — external examination entry fees. A family with a secondary-aged child at a mid-range Limassol school might realistically budget €12,000–€16,000 all-in for year one (including one-off enrolment costs), and somewhat less in subsequent years. Higher-priced IB schools, or families with multiple children, should budget considerably more.\n\nScholarships and bursaries exist at a small number of schools but are limited in number and competitive. Ask each school directly about merit-based or means-tested support. For help comparing options by location and stage before requesting fee schedules, use the school-finder tool at /tools/school-finder.",
			},
		],
		faqs: [
			{
				q: "How much does it cost to send a child to an international school in Cyprus?",
				a: "Annual tuition at English-medium private schools in Cyprus ranges indicatively from about €4,000 in early years at a modestly priced school to over €19,000 at a senior IB school. Primary typically falls in the €5,500–€10,000 range; secondary €7,500–€14,000 or higher. Every school sets its own fees and updates them annually, so always request the current schedule directly from the admissions office rather than relying on third-party listings.",
			},
			{
				q: "Which city in Cyprus has the most affordable international school fees?",
				a: "Paphos tends to offer competitive fees — the International School of Paphos is among the more affordable well-regarded English-medium options on the island, and TLC Private School in Peyia also offers reasonable rates. Larnaca has options at the lower end of the mid-range too. Limassol schools generally carry fees that reflect the city's popularity and higher cost of living, though more modestly priced options such as Logos School of English Education do exist there.",
			},
			{
				q: "Is there a waiting list for international schools in Limassol?",
				a: "Yes, and it is a genuine constraint. Popular year groups at Heritage, Foley's, and the Grammar School Limassol can fill well ahead of September. Some lower-fee schools have traditionally had waiting lists stretching several years. Families should aim to apply nine to twelve months before the September start they are targeting and should apply to more than one school simultaneously. The school-finder tool at /tools/school-finder can help you identify all viable options in your area.",
			},
			{
				q: "What costs should I budget for on top of tuition?",
				a: "Key additional costs include: an application or assessment fee, an enrolment deposit on acceptance (sometimes non-refundable), branded school uniform (€200–€500 or more in year one), school bus transport (roughly €800–€2,000 a year), canteen lunches where not included, external IGCSE or A-level exam entry fees, school trips, and after-school clubs and activities. Total additional costs routinely add 15–30% on top of the headline tuition figure.",
			},
			{
				q: "Can private school fees in Cyprus be paid in monthly instalments?",
				a: "Yes. Most Cyprus private schools offer structured payment plans — commonly two or three instalments per year, or monthly payments across the school year. Some schools offer twelve equal monthly payments. Settling the full annual fee upfront by the late-summer deadline usually earns a small discount of around 2–3%. Confirm the available payment options with the admissions office when you receive the fee schedule, as terms differ between schools.",
			},
			{
				q: "What curriculum do most international schools in Cyprus offer?",
				a: "The British Cambridge pathway — IGCSEs followed by A-levels — is by far the most common. A smaller number of schools hold IB authorisation, including The Island Private School in Limassol, PASCAL International Education, and Lumio Private School in Paphos. American-curriculum schools operate in Limassol and Larnaca. The schools-in-cyprus guide and the international-vs-public-school guide both cover curriculum options in detail.",
			},
		],
	},
];
