/**
 * Guides batch G2 — immigration depth and tax guides.
 * Covers work permits, citizenship, non-dom status, IP box, VAT,
 * crypto tax, company structures, and corporate banking.
 *
 * Disclaimer: this is general information, not legal or tax advice.
 * Thresholds, deadlines and fees change frequently — verify with the
 * Cyprus Tax Department, Civil Registry & Migration Department, and a
 * local accountant or lawyer before acting.
 */

import type { GuideInfo } from "./guides";

export const GUIDES_G2: ReadonlyArray<GuideInfo> = [
  {
    slug: "work-permits-non-eu",
    title: "Work Permits for Non-EU Nationals Employed in Cyprus (2026)",
    description:
      "How the Cyprus employer-sponsored work permit system operates — quota rules, required documents, the critical permit, fast-track tech scheme, and renewal. Prices and rules change — verify with official Cyprus sources before acting.",
    sections: [
      {
        heading: "Employer obligations and the quota system",
        body: "Cyprus applies a quota-based system for third-country national (TCN) workers under the Ministry of Labour and Social Insurance (MLSI). Before sponsoring a foreign hire, a Cypriot employer must first demonstrate that the position cannot reasonably be filled by a Cypriot or EU/EEA national — a requirement enforced through the '30% rule': across the employer's workforce, no more than 30% may be TCN employees in most sectors (the cap rises to 70% for registered companies in specific high-demand sectors). In practice, the employer must advertise the role through the CYSTAT Public Employment Service (PES) for a minimum of three weeks and receive written confirmation from MLSI that no suitable local candidate was referred. The National Employment Action Plan sets annual sector-level quotas; breaching a quota attracts administrative fines and can bar the employer from future TCN hiring for up to 12 months. Tourism, construction, and domestic care are historically the tightest sectors; software development and financial services are the most accommodating.",
      },
      {
        heading: "Required documents for the work permit application",
        body: "The application is submitted jointly by the employer and the employee to MLSI's Migration Department. Core documents: a valid passport (minimum six months remaining validity beyond the intended permit period), a signed employment contract specifying salary, role, and duration, a certified copy of relevant professional qualifications or degree, a clean criminal record certificate from the applicant's country of habitual residence (apostilled where required), a medical certificate confirming fitness to work, two recent passport-size photographs, proof of accommodation in Cyprus (a tenancy agreement or landlord declaration), and the employer's completed form for TCN hiring (available from mlsi.gov.cy). The employer also submits: company registration documents, recent payroll records showing current employee composition (to verify the quota calculation), and the PES 'no suitable candidate' confirmation letter. Application fees vary by permit category and duration but typically run €80–€150 for the initial permit.",
      },
      {
        heading: "The Critical Permit — entering and working while processing",
        body: "The standard work permit typically takes 8–14 weeks to process, which creates a practical problem for employers who need someone on-site urgently. Cyprus addresses this with the Critical Employment Permit (informally: the 'critical permit'), a temporary three-month work authorisation issued within roughly three weeks of application. To qualify, the employer must already have submitted the full work permit file to MLSI and must demonstrate that the role is genuinely time-sensitive — a standard declaration in the application form. The critical permit allows the employee to enter Cyprus, work for the sponsor, and remain legally while the main permit processes. It is not renewable; by the time it expires the main permit should be issued or the employer must demonstrate progress on the file. Employees who arrive and work before a critical or main permit is issued are in breach of Cypriot immigration law, which carries fines for both the employer and the employee.",
      },
      {
        heading: "Fast-track for the technology sector",
        body: "In 2022 Cyprus introduced a Fast-Track Business Activation Mechanism specifically for technology companies, with a dedicated work-permit stream administered through the Deputy Ministry of Research, Innovation and Digital Policy (RIDP). Companies registered under the scheme — broadly, firms whose primary activity is software development, digital services, R&D, or fintech — can hire TCN nationals in qualifying roles (developers, engineers, data scientists, product managers, senior designers) with processing targets of 20–30 working days rather than 8–14 weeks. The salary minimum for fast-track tech permits is currently €2,500 gross per month. The employer must be registered with the RIDP scheme before submitting fast-track applications; registration takes 4–6 weeks and involves a business plan submission. The quota system still applies, but the ratio for registered tech companies is the more generous 70% TCN ceiling. This scheme has significantly improved Cyprus's ability to attract engineering talent; it is the mechanism most technology founders use when relocating their team.",
      },
      {
        heading: "Permit renewal and long-term residence",
        body: "Initial work permits are typically granted for one year, occasionally two for senior roles, and are tied to the specific employer. An employee who changes employer must apply for a new permit under the new employer — there is no blanket transfer mechanism, and working for a non-sponsoring employer (even temporarily) is a breach. Renewal applications should be submitted at least 60 days before expiry; late submissions can create a legal grey zone where the employee is technically resident but their work authorisation has lapsed. After five years of continuous legal residence in Cyprus on work permits, a TCN can apply for Long-term Residence status under EU Directive 2003/109/EC, which removes the employer-specific restriction and grants near-permanent status including the right to seek work independently. The five-year clock requires physical presence; extended absences (more than six consecutive months or ten months in aggregate) can reset it.",
      },
    ],
  },
  {
    slug: "citizenship-naturalization",
    title: "Cypriot Citizenship Through Naturalization — The 7-Year Route",
    description:
      "The requirements, timeline, and practical realities of becoming a Cypriot citizen through the standard naturalization track — residency period, language test, and what dual nationality rules apply. Prices and rules change — verify with official Cyprus sources before acting.",
    sections: [
      {
        heading: "The seven-year residence requirement",
        body: "The standard path to Cypriot citizenship is naturalization under Article 111A of the Civil Registry Laws. The core requirement is seven years of continuous lawful residence in Cyprus immediately preceding the application. 'Continuous' has specific meaning: applicants must not have been absent for more than 90 days in any one of those seven years, and must not have any single absence exceeding 90 consecutive days. The calculation is strict and the Interior Ministry verifies it against passport stamps and entry/exit records held by the Civil Registry and Migration Department. The seven-year clock begins from the date your first valid residency permit was issued — not from the date you first entered Cyprus, not from the date you registered with the Civil Registry, but from the permit issue date. For EU citizens who registered an MEU1/Yellow Slip, the clock runs from that registration date. Getting the start date wrong is the most common reason applications are returned for insufficient evidence.",
      },
      {
        heading: "Minimum days per year and presence tracking",
        body: "Within each of the seven years, applicants must have been physically present in Cyprus for a minimum of 183 days. This is in addition to the 90-day absence cap — in other words, you must be present at least 183 days AND absent no more than 90 days per year, not one or the other. Cyprus does not stamp passports at its own borders for EU citizens (and for non-EU, records are held electronically from airport systems), so applicants are expected to maintain their own contemporaneous travel log and submit it with the application. Bank statements showing Cyprus card transactions, utility bills, GeSY medical visit records, children's school attendance records, and landlord/employer declarations are all used as corroborating evidence. The Interior Ministry has tightened scrutiny considerably since 2021 following the EU's concerns about the former CIP scheme; applications that rely on minimal supporting evidence are routinely returned.",
      },
      {
        heading: "Greek language proficiency — the A2 requirement",
        body: "Applicants must demonstrate Greek language proficiency at A2 level on the Common European Framework of Reference (CEFR). This is the second-lowest level — roughly equivalent to 'basic conversational Greek, can understand simple phrases and common expressions'. The approved examination providers are the Greek Language Certification body (KPG) administered through Cyprus's Ministry of Education, and certain accredited private language schools on the island. The exam covers reading, writing, speaking, and listening at A2 standard; most people with basic conversational Greek acquired during seven years of residence manage A2 comfortably. However, preparation time matters — there are only a few official exam sittings per year (typically March, May, and November), so applicants should register for a sitting well before the application date rather than leaving it to the last step. Exemptions: applicants over 65 years of age, and applicants who hold a degree taught in Greek, are exempt from the language test.",
      },
      {
        heading: "The application process and criminal clearance",
        body: "The naturalization application is submitted to the Civil Registry and Migration Department (CRMD) and then reviewed by a committee that makes a recommendation to the Minister of Interior, who has final discretion. The file includes: a completed application form (M127), certified copies of all passports held during the residence period, the civil registry registration documents (Yellow Slip/ARC for all years), a clean criminal record certificate from Cyprus Police (the applicant requests this via the CRMD), clean criminal record certificates from any other country of citizenship or previous long-term residence (apostilled), the A2 Greek language certificate, evidence of continuous residence (bank statements, utility bills, employer letters, CRMD registration updates), a completed financial declaration, and the application fee — currently €500. The Minister's discretion means that even complete files can be declined for reasons not explicitly specified in the law; applicants with any criminal history, even minor matters resolved years ago, should take legal advice before applying.",
      },
      {
        heading: "Timeline, dual nationality, and what citizenship gives you",
        body: "Once a complete application is submitted, the processing time is officially 18–24 months but varies significantly; some applications complete in 15 months, others take 30 months if the committee requests additional evidence or the Interior Ministry's workload is high. There is no expedited track. On approval, the applicant is invited to take the Oath of Allegiance and is issued a Cypriot identity card and passport. Cyprus is an EU member state, so Cypriot citizenship gives you EU citizenship and the right to live and work freely across all 27 EU member states. On dual nationality: Cyprus permits it. The country you are naturalising from determines whether you can retain your existing citizenship — Cyprus itself raises no objection to dual or even triple citizenship, but your birth-country laws apply separately. UK, US, Israeli, Indian, and most EU citizenship rules allow dual nationality with Cyprus without restriction; check the rules of your existing citizenship before assuming.",
      },
    ],
  },
  {
    slug: "non-dom-status-guide",
    title: "Cyprus Non-Dom Status — What It Actually Covers and Who Qualifies",
    description:
      "The precise scope of the Special Defence Contribution exemption, which income types it covers, how long it lasts, common misconceptions, and the GESY contribution that catches non-doms off guard. Prices and rules change — verify with official Cyprus sources before acting.",
    sections: [
      {
        heading: "What non-dom status is and is not",
        body: "Non-dom (non-domiciled) status in Cyprus is a designation within the income tax system that exempts qualifying residents from the Special Defence Contribution (SDC) — a levy that would otherwise apply to dividends, interest, and rental income received by Cyprus tax residents. It is not a tax holiday, not an investment visa, and not a separate residency permit. You can be a Cyprus tax resident without being non-dom (if you are long-term domiciled in Cyprus), and you can be non-dom without holding any special residency permit (an EU citizen registered on a Yellow Slip qualifies on day one of tax residency). The confusion arises because the marketing around Cyprus relocation often conflates non-dom status with other features of the tax system — such as the 0% rate on the first €19,500 of income, or the capital gains exemption on shares — which exist independently of non-dom and apply to all Cyprus residents. Non-dom status specifically addresses SDC, and SDC specifically applies to investment and passive income.",
      },
      {
        heading: "Income types exempt under non-dom — and those that are not",
        body: "For a Cyprus tax resident with non-dom status, the following income categories carry zero SDC: dividends received from any company anywhere in the world (SDC rate for domiciled residents is 17%), interest income from any source (SDC rate otherwise 30%), and rental income from properties located outside Cyprus (SDC rate otherwise 3%). This is the core non-dom benefit: a new resident receiving significant dividend income from a foreign company, or interest from a bond portfolio, pays zero SDC on that income. What non-dom does not exempt: employment income earned in Cyprus (which is subject to normal income tax at progressive rates up to 35%), self-employment income earned in Cyprus (same), rental income from properties inside Cyprus (SDC applies regardless of non-dom status for Cypriot-source rental income), and capital gains on Cypriot real estate (which falls under the Capital Gains Tax Law, not SDC). The practical test: if the income would otherwise attract SDC, non-dom removes it. If the income is subject to income tax only (not SDC), non-dom has no effect.",
      },
      {
        heading: "Who gets non-dom status and the 17-year clock",
        body: "Non-dom status is available to any individual who is not 'domiciled' in Cyprus for the purposes of the SDC law. Domicile is defined by Cypriot law using an English common-law concept: broadly, if you were not born to a Cypriot-domiciled parent and have not lived in Cyprus with the intention of remaining permanently for the majority of your adult life, you are not domiciled in Cyprus. In practice, virtually every relocating foreign national qualifies as non-dom automatically from their first day as a Cyprus tax resident — there is no application process, no certificate, and no fee. You simply declare your non-dom status on your annual tax return (Form TD1) by confirming that you are not domiciled in Cyprus. The clock matters: if you have been tax resident in Cyprus for 17 or more of the 20 consecutive tax years ending with the current year, you are deemed domicile-of-choice in Cyprus and lose non-dom status. This is a long runway — someone who first became Cyprus tax resident in 2015 would not lose non-dom status until 2032 at the earliest under the 17-of-20 rule.",
      },
      {
        heading: "GESY contribution on passive income — the number everyone misses",
        body: "Non-dom status does not exempt passive income from the General Health System (GESY) contribution. Since 2019, GESY contributions apply to all income received by Cyprus residents, including dividends, interest and rental income that are otherwise completely SDC-exempt. The GESY rate on passive income (dividends, interest, rents) is 2.65% of the gross amount, capped at a total annual contribution of €4,770 per year per individual (based on the €180,000 income cap). This is not a large figure in the context of significant investment income, but it is frequently omitted from non-dom planning discussions. A person receiving €500,000 in dividends annually pays zero SDC (saving €85,000 at the domiciled rate) but still pays €4,770 in GESY contributions — the cap means it does not scale beyond that. GESY contributions give you access to Cyprus's public healthcare system, which has real value, but the contribution is compulsory regardless of whether you use the system.",
      },
      {
        heading: "Common misconceptions and planning pitfalls",
        body: "Misconception one: 'non-dom means I pay no tax in Cyprus.' False. Non-dom specifically removes SDC on dividends and interest. Employment income, self-employment income, and Cypriot-source rental income are taxed as normal. Misconception two: 'I need to stay below 183 days to keep non-dom.' Wrong logic. Staying below 183 days means you are not a Cyprus tax resident at all — and non-dom is a status that exists only for Cyprus tax residents. The 60-day rule (which can make you a Cyprus tax resident with fewer than 183 days) is separate. Misconception three: 'I can receive a salary from my own Cyprus company and it will be tax-free.' Partially false. The salary is employment income subject to normal progressive income tax. However, if the same company pays you dividends rather than salary, the dividends are SDC-free under non-dom. The director/shareholder structure matters materially. Misconception four: 'Non-dom is permanent.' It lasts for up to 17 of 20 years of tax residency, which is long, but not infinite. Founders planning to use Cyprus as a long-term base should model the 17-year expiry into their long-term planning.",
      },
    ],
  },
  {
    slug: "ip-box-regime",
    title: "Cyprus IP Box Regime — 2.5% Effective Tax on Qualifying Intellectual Property",
    description:
      "How Cyprus's IP Box works, which types of IP qualify, how the nexus fraction determines the effective rate, practical structuring considerations, and a worked example. Prices and rules change — verify with official Cyprus sources before acting.",
    sections: [
      {
        heading: "What the IP Box is and why Cyprus built it",
        body: "Cyprus's IP Box (formally the Intellectual Property scheme under Section 9(1)(l) of the Income Tax Law as amended) is an 80% income tax exemption applied to qualifying profits derived from qualifying intellectual property. Since Cyprus's standard corporate tax rate is 12.5%, an 80% exemption leaves an effective rate of 2.5% on IP-derived income. Cyprus introduced its first IP Box in 2012, revised it in 2016 to comply with the OECD's BEPS Action 5 'nexus approach', and the current version is a fully BEPS-compliant 'modified nexus' regime. What this means in practice: the benefit is not unlimited. It applies in proportion to the ratio of qualifying R&D expenditure the company (or its related parties) incurred to create the IP, relative to total acquisition and development costs. The regime is designed for companies that genuinely create IP in Cyprus, not purely for holding companies that acquire IP from related parties abroad.",
      },
      {
        heading: "Qualifying and non-qualifying IP",
        body: "Qualifying IP under the Cyprus regime: patents (registered in any jurisdiction, including USPTO, EPO, UK IPO, and equivalent foreign offices), utility models, supplementary protection certificates, plant variety protections, orphan drug designations, and computer software copyright. Computer software copyright is the most widely used category for tech companies — it does not require patent registration, it covers the source code and compiled software directly, and it is sufficient that the software is original and protected by copyright law (which is automatic on creation in all Berne Convention jurisdictions). What does not qualify: trademarks, service marks, brand names, domain names, marketing-related IP, business processes that are not patented, customer databases, and other 'marketing intangibles'. This exclusion is deliberate: the OECD nexus approach targets R&D-intensive IP, not brand-building. A software company using the IP Box to shelter profits from a proprietary application: qualifies. A consumer brand using the same regime to shelter trademark royalties: does not qualify.",
      },
      {
        heading: "The nexus fraction calculation",
        body: "The percentage of qualifying IP income that receives the 80% exemption is determined by the nexus fraction: (qualifying expenditure × 130%) / overall expenditure. Qualifying expenditure means R&D costs incurred directly by the Cyprus company (or outsourced to unrelated third parties). The 130% uplift is an OECD-approved adjustment that rewards companies maintaining some related-party R&D. Overall expenditure is the total cost base for developing the IP, including amounts paid to related parties and acquisition costs. Example: a Cyprus software company spent €400,000 developing an application using its own team, and paid a related Irish company €100,000 for additional development. Qualifying expenditure = €400,000 × 1.30 = €520,000 (capped at overall expenditure). Overall expenditure = €500,000. Nexus fraction = €500,000 / €500,000 = 100%. The entire IP profit qualifies. If the related-party spend was €300,000 instead: qualifying = min(€400,000 × 1.30, €700,000) = €520,000. Overall = €700,000. Nexus fraction = 74%. 74% of IP profit gets the 80% exemption; the remaining 26% is taxed at 12.5%.",
      },
      {
        heading: "Structuring an IP holding company",
        body: "The IP Box works most cleanly when the Cyprus company genuinely develops IP in Cyprus — meaning real staff doing real R&D work in Cyprus. A substance-light holding company that merely receives royalties from operating subsidiaries is increasingly difficult to defend under BEPS and is subject to enhanced scrutiny by the Cyprus Tax Department and foreign tax authorities under DAC6 reporting obligations. A practical structure for a tech founder relocating to Cyprus: establish a Cyprus Limited Company; employ the founding team (or a meaningful proportion of them) in Cyprus; have the company be the registered copyright owner of the software; the company licenses the software to customers or related operating entities and books the licence fees in Cyprus under the IP Box. The more R&D work that genuinely happens in Cyprus, the higher the nexus fraction and the cleaner the position. 'Management and control' in Cyprus is necessary for the company to be Cyprus tax resident, and for a small team of founders physically relocating to Cyprus, that substance exists naturally.",
      },
      {
        heading: "Practical example and what to expect from advisers",
        body: "A SaaS company with one founder in Cyprus and a two-person development team relocates the IP-holding entity to Cyprus. Annual licence fees received from operating entities: €1,000,000. R&D costs incurred in Cyprus: €250,000 (salaries + infrastructure). No related-party outsourcing. Nexus fraction: 100%. Qualifying IP profit: €750,000 (revenue minus costs). 80% exemption: €600,000 exempt. Taxable at 12.5%: €150,000. Tax: €18,750. Effective rate on IP profit: 2.5%. A Cyprus accounting firm experienced with IP Box will maintain a 'qualifying expenditure tracker' year by year, as the nexus fraction must be recalculated at each tax year end. They will also document that the IP is owned by the Cyprus company (via assignment agreements, copyright notices, and development agreements), and that the R&D is genuinely conducted in Cyprus (time records, project documentation). Without this documentation, the IP Box position is difficult to defend in an audit. Expect annual accounting fees for an IP Box company to run €3,000–€8,000 per year depending on complexity.",
      },
    ],
  },
  {
    slug: "vat-registration-guide",
    title: "VAT Registration in Cyprus — Thresholds, Filing, and the OSS Scheme",
    description:
      "When you must register for VAT in Cyprus, how to register via TaxisNet, quarterly filing obligations, the VAT rules for new property, and how the EU OSS scheme works for e-commerce sellers. Prices and rules change — verify with official Cyprus sources before acting.",
    sections: [
      {
        heading: "The €15,600 threshold and when registration is mandatory",
        body: "Cyprus's VAT system is administered by the Tax Department under the VAT Law of 2000 (as amended), which transposes EU Directive 2006/112/EC. The compulsory registration threshold is €15,600 of taxable supplies in any rolling 12-month period. Once your cumulative taxable turnover exceeds this amount, you must register within 30 days and begin charging VAT from the date you were required to register. The standard VAT rate is 19%; the reduced rate is 9% (applying to restaurant and hospitality services, passenger transport, and certain other services); the super-reduced rate is 5% (applying to specific goods including books, newspapers, and importantly, new residential property under certain conditions — more on this below). Zero-rated supplies include most exported goods and services sold to VAT-registered EU businesses (B2B intra-EU). Non-taxable supplies that do not count towards the €15,600 threshold include certain financial services, education, medical services, and insurance.",
      },
      {
        heading: "Voluntary registration and the practical case for it",
        body: "You can register for VAT voluntarily even below the €15,600 threshold — and there are real reasons to do so. Voluntary registration lets you reclaim input VAT on business expenses immediately: if you are setting up an office, buying equipment, or incurring professional fees before your revenue kicks in, those costs carry 19% VAT that you can only recover if you are registered. For a company establishing itself in Cyprus with significant upfront costs, voluntary registration in month one can recover several thousand euros in input VAT within 30 days. The trade-off: once registered, you must file quarterly VAT returns, maintain VAT-compliant invoices, and charge output VAT on all taxable supplies. For B2C businesses serving Cypriot or EU consumers, this adds administrative overhead and a potential pricing impact. For B2B businesses (where your customers are VAT-registered and can reclaim the VAT you charge), it is usually neutral.",
      },
      {
        heading: "Registering via TaxisNet and quarterly filing",
        body: "VAT registration in Cyprus is done electronically through the Tax Department's TaxisNet portal (taxisnet.mof.gov.cy). You will need a Tax Identification Number (TIC) before registering for VAT. The VAT registration form (VAT F1) requires business details, expected turnover, bank account information, and a description of your taxable activities. Once processed (typically 3–5 business days), you receive a VAT registration number in the format CY + 8 digits + letter. Quarterly VAT returns (Form VAT 4) must be filed and any tax due paid within 40 days of the end of each quarter. Filing is online through TaxisNet. Late filing carries a fixed penalty of €51 per late return plus interest on unpaid tax at 1.75% per annum. VIES (VAT Information Exchange System) declarations are required quarterly if you have intra-EU B2B transactions — these report the total value of goods and services supplied to VAT-registered customers in other EU member states and are separate from the VAT return itself.",
      },
      {
        heading: "OSS for e-commerce: selling to EU consumers from Cyprus",
        body: "If you run an e-commerce business selling digital services, goods, or other B2C supplies to consumers in multiple EU member states, the One-Stop Shop (OSS) scheme replaces the requirement to register for VAT separately in each country where you have customers. Registered in Cyprus for OSS through TaxisNet, you file a single quarterly OSS return reporting all cross-border B2C EU sales, broken down by member state and applicable local rate. The Tax Department then distributes the collected tax to the relevant member states. The EU-wide threshold for OSS registration is €10,000 of cross-border sales per year; below that, you can apply Cyprus VAT to all EU sales. Above it, OSS is effectively mandatory if you want to avoid multi-country VAT registrations. Most SaaS companies, digital product sellers, and online service businesses with a pan-EU customer base use OSS as their primary compliance mechanism from day one of exceeding the €10,000 threshold.",
      },
      {
        heading: "VAT on new property — the 5% reduced rate conditions",
        body: "The 5% reduced VAT rate on new residential property purchases is one of the more significant practical features of Cyprus's VAT system and directly affects relocators buying homes. The conditions for the 5% rate: the property must be new (first transfer — second-hand properties are not subject to VAT at all, only transfer tax), the buyer must be an individual (not a company) purchasing for use as their primary and permanent place of residence, the buyer must not have previously used the 5% rate on another Cyprus property, and the reduced rate applies to the first 200 square metres of buildable area (above 200 sqm, the excess is taxed at 19%). Before 2023, the threshold was 130 sqm; it was expanded to 200 sqm as part of housing affordability measures. The buyer must sign a statutory declaration confirming their intent to use the property as a primary residence for at least 10 years; transferring or letting the property within 10 years triggers a VAT clawback obligation of the difference between the 5% and 19% rates on the full purchase price.",
      },
    ],
  },
  {
    slug: "crypto-tax-cyprus",
    title: "Cryptocurrency Tax Treatment in Cyprus (2026)",
    description:
      "How Cyprus currently taxes cryptocurrency gains, where the investing-versus-trading line is drawn, VAT on crypto services, documentation best practices for non-dom filers, and what local accountants currently recommend.",
    sections: [
      {
        heading: "The current position: no formal guidance, but a working consensus",
        body: "Cyprus has not published formal binding guidance on the taxation of cryptocurrency as of 2026 — there is no equivalent to HMRC's 'Cryptoassets Manual' or the IRS's Notice 2014-21. The Cyprus Tax Department has confirmed informally that it views crypto disposals through the lens of the existing tax framework rather than a new regime, and on that basis the working consensus among Cypriot tax practitioners is as follows: gains from selling or exchanging cryptocurrency by an individual investor are treated as capital gains on movable property; capital gains tax in Cyprus applies only to gains from Cypriot real estate and shares in companies holding Cypriot real estate; therefore, capital gains on cryptocurrency are not subject to Cyprus capital gains tax. This would place individual crypto gains in the same category as gains on listed shares or foreign property — wholly exempt. The critical caveat: this is a position, not a ruling. The Tax Department has discretion to characterise frequent trading as a business activity.",
      },
      {
        heading: "Investing versus trading — where the line is drawn",
        body: "The distinction between capital gains (exempt) and trading income (taxable as self-employment income at progressive rates up to 35%) is fact-specific and contested. Factors that courts and tax authorities in common-law jurisdictions (which Cyprus closely follows for this analysis, given the absence of local caselaw) use to draw the line: frequency of transactions (a few per year suggests investment; dozens per week suggests trade), holding period (months or years suggests investment; hours or days suggests trade), source of the assets (earned via mining or staking, then sold, can look like a business), use of leverage or derivatives (typically marks trading intent), whether this is your primary occupation and income source, and whether you hold yourself out as providing trading services to others. A founder who relocated to Cyprus with an existing crypto portfolio, holds positions for months, and sells occasionally: almost certainly treated as capital gains and exempt. A person who day-trades altcoins as their primary occupation, turning over the entire portfolio weekly: almost certainly treated as a business and taxed as self-employment income. The grey zone is large and growing as more crypto activities (staking rewards, liquidity provision, yield farming) generate regular income that looks increasingly like interest or operating income.",
      },
      {
        heading: "VAT treatment of crypto services",
        body: "The EU Court of Justice's 2015 Hedqvist ruling (C-264/14) established that exchanging fiat currency for Bitcoin or other cryptocurrencies is a VAT-exempt financial service under Article 135(1)(e) of the VAT Directive. Cyprus follows this ruling: exchange services, custody services, and straightforward crypto-to-fiat or crypto-to-crypto exchange transactions are VAT-exempt. However, the exemption is narrow. Services that are not 'exchange' — crypto consulting, portfolio management services, NFT creation and sale, running a node for transaction fees, software development for blockchain protocols — may be standard-rated at 19% if they constitute a taxable supply of services to a Cypriot or EU consumer. For a Cyprus-based crypto business, the VAT treatment of each revenue stream needs to be mapped individually; bundling exchange with advisory services without clear invoicing separation creates VAT exposure. If you provide crypto-related services to non-EU clients only, those are zero-rated exports regardless of the specific activity type.",
      },
      {
        heading: "Documenting crypto holdings for non-dom filing",
        body: "Non-dom status exempts Cyprus tax residents from SDC on dividends and interest — and while the Tax Department has not confirmed that staking rewards are 'interest' for SDC purposes, many practitioners treat them as potentially SDC-exempt under non-dom pending formal clarification. Whatever the ultimate treatment, detailed records are essential. The Tax Department expects Cyprus tax residents to be able to produce, on request, a record of all crypto holdings at year-end, a transaction history for the year (acquisitions, disposals, swaps, staking rewards, airdrops), the cost base for each acquisition, the value at disposal in EUR, and any exchange or wallet addresses used. Portfolio tracking tools such as Koinly, CoinTracking, or Accointing can export these records in formats that accountants can work with. The practical problem is wallet-level aggregation: if your portfolio spans a hardware wallet, three CEX accounts, and two DeFi protocols, manual reconciliation is time-consuming. Start year-by-year tracking from the day you become a Cyprus tax resident, not retrospectively.",
      },
      {
        heading: "What accountants currently recommend",
        body: "Based on the practices of Cypriot accounting firms with active crypto clients in 2025–2026: first, file a Cyprus tax return each year even if you believe all your crypto income is exempt — the non-dom and capital gains exemptions both require an affirmative declaration, and failing to file is a separate risk from getting the tax position wrong. Second, if your crypto activity looks like trading (high frequency, leverage, primary income source), engage an accountant before year-end rather than after — there may be structuring options that reclassify the activity or manage the timing of recognition. Third, for significant holdings (over €100,000), obtain a written opinion from your accountant or tax lawyer on your specific position; this constitutes 'reasonable care' and provides some protection against penalties if the Tax Department later takes a different view. Fourth, watch the 2024–2026 EU legislative calendar: the DAC8 directive (effective from 2026) requires all EU crypto asset service providers to report transaction data to tax authorities, which will significantly increase the Tax Department's ability to cross-reference declared positions against exchange records.",
      },
    ],
  },
  {
    slug: "company-types-comparison",
    title: "Cyprus Ltd vs Sole Trader vs Partnership — Choosing the Right Structure",
    description:
      "A frank comparison of the main business structures available in Cyprus — formation costs, tax treatment, liability exposure, audit requirements, and when each makes sense for a relocating founder.",
    sections: [
      {
        heading: "The four structures available to a relocating founder",
        body: "Cyprus company law provides four main structures for running a business: a Private Limited Company (Ltd), a sole proprietorship (self-employment registration with the Tax Department), a partnership (general or limited, regulated by the Partnership Law), and a branch of a foreign company. A fifth option — the Cyprus SE (Societas Europaea, the EU public company form) — exists but is impractical for most small businesses. The choice between these structures affects personal liability, how profit is taxed, administrative overhead, access to Cyprus's corporate tax rate and IP Box, and how the business looks to banks and counterparties. The vast majority of relocating founders who intend to run a commercial business use the Private Limited Company, and for good reason: the combination of the 12.5% corporate tax rate, non-dom dividend exemption, and IP Box makes the corporate form exceptionally efficient for most business types. However, sole trader registration has genuine advantages for service businesses with low liability exposure and simple finances.",
      },
      {
        heading: "Cyprus Private Limited Company — the full picture",
        body: "Incorporating a Cyprus Limited Company involves filing a Memorandum and Articles of Association with the Registrar of Companies, appointing at least one director and one shareholder, and registering a local registered office address. Incorporation costs through a registered agent run €1,500–€2,500 all-in, including Registrar fees (currently €105 for online incorporation) and agent fees. The company must have a local registered office address (a registered agent service costs €300–€600 per year if you do not have permanent Cyprus premises). Tax: the company pays 12.5% corporate tax on net profits. Salary paid to directors is deductible from corporate profit, reducing CT, but salary is subject to income tax and social insurance (8.3% employee + 8.8% employer for employees, different rates for directors depending on classification). After-tax profits distributed as dividends to a non-dom shareholder carry 0% SDC and 0% income tax — the dividend is simply exempt. Annual obligations: audited financial statements are mandatory for all Cyprus companies regardless of size (this is a common surprise for founders used to small-company audit exemptions in the UK or US — in Cyprus there is no exemption); audit costs run €1,000–€3,000 per year for a simple company. Annual return filing fee: currently €350.",
      },
      {
        heading: "Sole trader — when simpler is better",
        body: "Registering as a self-employed sole trader (freelancer/epangelmativas in Greek) involves registering with the Tax Department and Social Insurance Services, with no company formation required. There is no separate legal entity — the individual is the business. Tax: profits are taxed at personal income tax rates (0% on the first €19,500, then 20%–35% progressively). Social insurance: a self-employed person contributes 16.6% of their income (before deductions, based on a declared income that may not be lower than a minimum threshold set annually by the Social Insurance Services — currently around €22,000 per year minimum basis). The Social Insurance contribution is a real cost that often surprises founders: on €50,000 of self-employment income, the SI contribution alone is approximately €8,300 per year. There is no mandatory audit, no annual return, and no Registrar fees. This structure works well for: consultants and service professionals who do not need the liability protection of a company, freelancers with modest turnover (below the threshold where the CT rate advantage outweighs SI savings), and people testing a business concept before formalising it.",
      },
      {
        heading: "Partnership and branch office — niche uses",
        body: "General and limited partnerships are registered with the Registrar of Companies and are taxed transparently — each partner is taxed on their share of profit at personal income tax rates. They have limited practical use for most relocating founders: they offer no liability advantage over a company (general partners have unlimited liability), they are taxed less efficiently than a corporate structure for significant profits, and they are unusual enough that banks and institutional counterparties sometimes ask questions. The main use case is professional firms (law, accounting, architecture) where partnership form is traditional or required by the relevant professional body. A branch office is a registration of a foreign company's operations in Cyprus — it is not a separate legal entity, meaning the parent company remains fully liable for the branch's obligations. Branches are used primarily by multinational corporations establishing a presence in Cyprus without wanting to create a separate subsidiary; for founders, the liability exposure and administrative complexity of running a dual-entity structure makes this almost never the right choice.",
      },
      {
        heading: "Making the choice: a decision framework",
        body: "If your annual revenue is above approximately €50,000, you plan to build a team, or your income includes IP licensing, dividends from a holding company, or profits you want to reinvest: Cyprus Ltd is almost always the right answer. The 12.5% corporate tax rate, IP Box availability, and efficient dividend extraction via non-dom exemption produce a materially lower total tax burden than sole trader once profits exceed that threshold. If your revenue is below €50,000 and your business is a straightforward service with minimal liability risk, the simpler sole trader structure avoids the €1,000–€3,000 annual audit cost and reduces administrative burden without a significant tax disadvantage at low profit levels. If you are incorporated elsewhere (UK, US, Netherlands) and want to test Cyprus before committing: maintain your existing company but register as a Cyprus tax resident and director — the management-and-control rules mean a foreign company whose sole director is based in Cyprus may be treated as Cyprus tax resident, so take advice before assuming your UK Ltd remains UK-taxed after you move. Do not let this consideration remain unresolved for your first full tax year.",
      },
    ],
  },
  {
    slug: "corporate-bank-account-guide",
    title: "Opening a Cyprus Corporate Bank Account as a Foreign Director",
    description:
      "Which banks take foreign-director applications, what documents the KYC process actually requires, realistic timelines post-2022, and when an EMI is the right bridge or alternative.",
    sections: [
      {
        heading: "The reality of corporate banking in Cyprus post-2022",
        body: "Opening a corporate bank account in Cyprus has become materially harder since 2021–2022. The combined effect of the Central Bank of Cyprus's de-risking directives following the 2022 sanctions environment, the aftermath of the FinCEN files scrutiny, and Hellenic Bank's aggressive clean-up of its corporate book has left the Cypriot corporate banking sector with a smaller but more cautious set of providers. For a company with a Cypriot director physically resident in Cyprus, a clear business model, and locally-sourced income, account opening is still achievable in 4–8 weeks. For a company with a foreign-only director, offshore-facing income, or complex ownership structures, expect resistance, longer timelines, and possible outright decline from the main banks. The realistic path starts with understanding that banks are making commercial decisions based on their compliance cost and risk appetite — there is no regulatory entitlement to a bank account, and the banks know it.",
      },
      {
        heading: "Which banks accept foreign-director applications",
        body: "Bank of Cyprus remains the largest retail and corporate bank and accepts foreign-director applications, but the process is the most document-intensive of the three main options. Hellenic Bank accepts corporate accounts but has significantly tightened its criteria post-2022; the Limassol Makarios Avenue branch has the most experienced team for international corporate applications. AstroBank has historically been the most accommodating for companies with non-EU ownership, MENA or CIS-connected structures, or non-standard source-of-funds profiles — it has a smaller branch network but meaningfully higher acceptance rates for profiles that the larger banks decline. The Alpha Bank Cyprus corporate team (part of Greece's Alpha Bank) is a less-frequently-mentioned option that handles regional Eastern European and Israeli-connected corporate structures with more flexibility than Bank of Cyprus's standard compliance process. Cooperative banks and smaller regional institutions are generally not equipped for foreign-director corporate applications and are not worth pursuing in parallel.",
      },
      {
        heading: "Required documents — what the KYC process actually needs",
        body: "All three banks will require, as a minimum: certified copies of passports for all directors and beneficial owners (UBOs), a copy of the Certificate of Incorporation, Certificate of Directors and Secretary, and Certificate of Shareholders (all issued by the Cyprus Registrar of Companies, and must be recent — typically within the last three months), the company's Memorandum and Articles of Association (certified), a corporate bank account application form specific to each bank, a source of funds declaration for the company explaining where the initial capital came from and where ongoing revenues will come from, a business plan or activity description (a two-page document covering what the company does, who its customers are, and the expected transaction volumes), bank statements from any existing company accounts (typically 6–12 months) to evidence trading history, and professional reference letters (optional but helpful). For beneficial owners who are non-EU nationals from higher-risk jurisdictions under EU AML classifications, the bank will additionally request enhanced due diligence documentation: evidence of the person's tax status in their home country, previous corporate history, and sometimes source-of-wealth evidence at a personal level.",
      },
      {
        heading: "Typical timeline and what slows it down",
        body: "From submitting a complete initial document pack to having a functioning account with online banking access, the realistic timeline at all three major banks is 4–8 weeks. The most common causes of delays: incomplete initial documents (a missing certificate, an expired document, or a certification that the bank's compliance team deems insufficient) — this resets the clock by 2–3 weeks each time it happens; compliance queries that require additional information beyond the initial pack (common for companies with multi-jurisdiction structures or historical companies with ownership changes); and internal credit committee reviews for companies planning high transaction volumes or complex currency arrangements. Submitting a complete, pre-organised document bundle — ideally with a covering letter summarising the business, ownership structure, and expected account usage — cuts the average timeline meaningfully. Some business introducers and law firms in Limassol offer bank-introduction services (€500–€1,500) that pre-screen applications and handle the initial bank liaison; for complex profiles, this is often worth the cost.",
      },
      {
        heading: "EMI alternatives: Revolut Business, Wise Business, and when they make sense",
        body: "Electronic Money Institutions (EMIs) are not banks, but for many corporate use cases they function as a practical alternative or bridge. Revolut Business (Lithuania-licensed) and Wise Business (Belgium-licensed) both open accounts for Cyprus companies with foreign directors in 1–5 business days with entirely online processes; the KYC is stricter than the consumer versions but far lighter than a traditional bank. Both provide IBAN accounts, SEPA and SWIFT transfers, multi-currency wallets, debit cards, and API integrations. Revolut Business's fees are subscription-based (€0–€100/month depending on plan and features); Wise Business charges per-transfer with no subscription. Limitations: neither provides a CY-prefix IBAN, which means some Cypriot counterparties (utility providers, landlords, certain government payment systems) will not accept them for direct debits or payments. Neither is a regulated bank under the Cyprus Banking Law, meaning they cannot provide loans, guarantees, or letters of credit. The practical recommendation for most new Cyprus companies: open a Revolut Business or Wise Business account immediately for operational spending and incoming payments, and pursue a traditional bank account in parallel. Use the EMI as your working account for months 1–6 while the bank account processes; do not rely on it indefinitely, as both platforms have been known to freeze accounts of companies whose activity pattern changes unexpectedly.",
      },
    ],
  },
];
