import type { GuideInfo } from "./guides";

/**
 * SEO content batch 2 (July 2026) — research-backed tax/finance guides.
 * Each figure web-verified; see commit notes for source list. Kept in a
 * separate file for reviewability; spread into GUIDES in guides.ts.
 */
export const GUIDES_BATCH2: GuideInfo[] = [
	{
		slug: "cyprus-mortgage-foreigners",
		datePublished: "2026-07-05",
		dateModified: "2026-10-02",
		lastChecked: "2026-10-02",
		sources: [
			{
				label: "Advocates Law, Cap. 2 (CyLaw)",
				url: "http://www.cylaw.org/nomoi/enop/non-ind/0_2/full.html",
			},
			{
				label: "Judicare: Cyprus residential purchase pricing",
				url: "https://www.judicaregroup.com/pricing/cyprus-res-purchase-pricing/",
			},
		],
		category: "property",
		title: "Cyprus Mortgages for Foreigners: 2026 Guide",
		description:
			"Can foreigners get a Cyprus mortgage? Yes — which banks lend to non-residents, deposit requirements, rate ranges, and the total buying costs to budget for.",
		sections: [
			{
				heading: "Can Foreigners and Non-Residents Get a Cyprus Mortgage?",
				body: "Foreigners and non-residents can obtain mortgage finance in Cyprus, though the market is meaningfully narrower than it is for Cypriot citizens or permanent residents. Cyprus is an EU member state, so EEA nationals broadly enjoy the same property rights as Cypriot citizens. Non-EU nationals face one additional step: before completing a purchase, they must obtain an Acquisition Permit from the District Administration Office (sometimes referred to as 'Council of Ministers approval'). The permit is routinely granted for straightforward residential purchases and typically takes one to three months depending on the district — start the process early, as it runs in parallel with your mortgage application.\n\nFor mortgage purposes, the distinction banks draw is primarily residency status rather than nationality alone. Non-residents — whether EU or non-EU — face stricter loan-to-value caps, higher deposit requirements, and more thorough income verification than resident borrowers. Some Cypriot banks decline non-resident applications outright, so identifying the right lender is the first practical step.\n\nBefore approaching any bank, use the mortgage calculator at /tools/mortgage-calculator to work out indicative monthly repayments across different deposit sizes and rate scenarios. Knowing your numbers before the first meeting will help you present a stronger application. For a step-by-step overview of how property transactions work in Cyprus, the buying-process guide covers each legal stage from offer to completion.",
			},
			{
				heading:
					"Which Banks Lend to Non-Residents — the Eurobank/Hellenic Context",
				body: "The lending landscape for non-residents changed materially on 1 September 2025, when Hellenic Bank — historically the most active Cypriot lender to foreign buyers — completed its legal merger with Eurobank Cyprus. The merged entity now trades as Eurobank Limited, the second-largest bank in Cyprus by assets. Eurobank Limited has continued Hellenic Bank's policy of offering mortgage finance to non-residents, specifically for holiday-home purchases and buy-to-let investments. Existing Hellenic Bank customers retain the same loan terms and IBANs following the merger.\n\nBeyond Eurobank, the options for non-residents thin out considerably. Bank of Cyprus — the largest Cypriot lender — primarily targets resident borrowers but will consider non-resident applications on a case-by-case basis under stricter conditions. Alpha Bank Cyprus also offers mortgage products to foreign buyers. AstroBank and Ancoria Bank primarily serve resident clients and offer competitive rates in that segment; both may consider non-resident enquiries, but you should contact them directly to confirm their current eligibility criteria before investing time in a full application.\n\nIn practice, most non-resident buyers begin their search with Eurobank Limited. A local property lawyer can often facilitate an introduction to the bank's mortgage team and help ensure your documentation is correctly assembled from the outset — see the property-lawyers-cyprus guide for guidance on finding qualified representation in Cyprus.",
			},
			{
				heading: "Deposit and Loan-to-Value Requirements for Non-Residents",
				body: "The most immediate financial hurdle for non-resident buyers is the deposit. Where a Cypriot permanent resident may access up to 80% loan-to-value (LTV), meaning a minimum 20% deposit, non-residents should budget for significantly more.\n\nFor EU/EEA nationals who are not Cyprus-resident, banks typically offer 60–70% LTV, requiring a deposit of 30–40% of the purchase price. For non-EU nationals, LTV caps are often stricter: some lenders limit lending to 50–60% LTV, implying a deposit of 40–50%. The precise figure depends on the bank, the property type, whether it is a new build or resale, and your overall financial profile. These ranges are indicative: always confirm current terms directly with any lender you approach, as conditions can change.\n\nResale properties are sometimes assessed more conservatively because of the title-deed complexities that can arise in Cyprus. Before committing to a purchase, the title-deed-status-guide on this site explains what to check, and the new-development-buying-guide covers additional considerations specific to new-build and off-plan purchases.\n\nDeposit size also directly affects the interest rate you are offered: a larger deposit typically attracts a lower margin. Borrowers bringing 40% or more, with a strong euro-denominated income, are generally in the strongest negotiating position. Run the numbers across different deposit scenarios using the mortgage calculator at /tools/mortgage-calculator before deciding how much capital to commit upfront versus retaining as a liquidity reserve.",
			},
			{
				heading: "Current Interest Rates: Fixed vs Variable",
				body: "Cyprus mortgage rates have fallen steadily since their 2023 peak, broadly tracking the European Central Bank's rate cycle. According to Central Bank of Cyprus statistics, the average rate on new housing loans was approximately 3.37% in December 2025, edging up to around 3.45–3.70% in early 2026. These averages cover the full borrower population, including resident customers who typically access the most competitive terms.\n\nFor non-residents, the effective rate is higher. Lenders commonly apply a non-residency loading of approximately 0.5–1.0 percentage points above the rates offered to comparable resident customers. As a planning assumption for mid-2026, non-resident borrowers should model variable rates in the approximate range of 4–5% per annum — but rates move with Euribor and ECB decisions, so always request a current, personalised indicative rate from any bank you approach. Do not treat any published figure as a guarantee.\n\nFixed-rate products are available and suit buyers who want payment certainty in the early years. Introductory fixed periods of three to five years can start from roughly 2.95–3.10%, after which the loan typically reverts to a variable rate. Longer fixed terms carry higher initial rates. A small number of banks also offer a green-home discount of roughly 0.15–0.25% for properties meeting specific energy-efficiency standards — worth enquiring about if you are buying a newer, well-rated property.\n\nWhen comparing offers, use the Annual Percentage Rate (APR) rather than the headline rate, as the APR incorporates arrangement fees and other charges. The mortgage calculator at /tools/mortgage-calculator lets you stress-test repayments at different rate levels — particularly useful given that rates will shift over a 20- to 25-year term.",
			},
			{
				heading: "Income Documentation and Affordability Assessment",
				body: "Cyprus banks assess mortgage affordability through two lenses: income documentation and the debt-to-income (DTI) ratio. Non-residents face more extensive requirements because banks must verify income generated outside Cyprus.\n\nStandard documentation expected from non-resident applicants includes: six to twelve months of personal bank statements; three to six months of payslips for salaried employees, or two to three years of audited accounts and tax returns for the self-employed; the most recent two years of tax returns from your country of residence; an employment contract or employer's letter confirming salary and role; and a credit report from your home country where one is available. All documents not already in English or Greek must be certified translated — factor in the cost and lead time when planning your application timeline.\n\nOn affordability, the Central Bank of Cyprus sets macro-prudential guidelines that lenders use as a reference. As a broad rule, total monthly debt obligations — including the proposed mortgage payment — should not exceed 33–40% of your verified gross monthly income. Different banks apply this somewhat differently; some use net income as the calculation base, so confirm the method with each lender. All existing liabilities — credit cards, car loans, personal loans, other mortgages — count towards the DTI.\n\nThere is no single published minimum income threshold, but in practice a monthly net income of at least €2,000–€2,500 is often an informal lower bound for a standard application. A euro-denominated salary simplifies the assessment considerably; foreign-currency income is generally accepted but may be assessed at a conservative exchange rate to account for currency risk.",
			},
			{
				heading: "Total Buying Costs and the Mortgage Process",
				body: "Budgeting for a Cyprus property purchase means setting aside considerably more than just the deposit. The additional costs differ substantially depending on whether you are buying a new build or a resale property.\n\nFor new-build properties, VAT is the dominant cost. The standard rate is 19%, but a reduced rate of 5% applies where the property will serve as your primary residence, subject to detailed area and value conditions. Property transfer fees are waived entirely on new builds where VAT has been paid.\n\nFor resale properties, VAT does not apply, but property transfer fees are payable on a progressive scale: 3% on the first €85,000 of assessed value, 5% on the portion between €85,001 and €170,000, and 8% above €170,000. A statutory 50% reduction applies, halving the effective rates. Stamp duty was abolished from 1 January 2026: contracts signed from that date carry no stamp duty charge, removing a cost that previously ran to around 0.15–0.20% of the purchase price.\n\nLegal fees are not regulated, so they vary: quotes of around 1% to 1.5% of the purchase price plus VAT are common, so get two or three written quotes. The bank will charge a mortgage arrangement fee (commonly around 1% of the loan amount) and a property valuation fee (typically €200–€700), and will require ongoing buildings and life insurance throughout the loan term.\n\nThe full mortgage process from formal application to funds release typically takes one to three months. Most lenders issue an approval-in-principle within two to four weeks of receiving a complete application. Non-EU buyers should factor in Acquisition Permit processing time on top of this. Confirm the current reduced-VAT conditions and any recent changes with your property lawyer before you commit.",
			},
		],
		faqs: [
			{
				q: "Do I need to be a resident of Cyprus to get a mortgage?",
				a: "No, but your residency status significantly affects the terms you will be offered. Non-residents are typically restricted to a lower loan-to-value ratio — around 60–70% LTV for EU nationals, and often 50–60% for non-EU nationals — and face higher interest rates and more rigorous documentation requirements than resident borrowers. Eurobank Limited (the entity that Hellenic Bank became on 1 September 2025) is currently the most active lender to non-residents. Becoming a Cyprus tax resident before applying will widen your lender options and generally improve your rate and LTV terms.",
			},
			{
				q: "I am a non-EU national — can I buy and mortgage property in Cyprus?",
				a: "Yes. Non-EU nationals can buy property in Cyprus and obtain a mortgage, subject to two additional requirements. First, you must apply for an Acquisition Permit from the District Administration Office before the sale is completed. The permit is routinely granted for genuine residential purchases and generally takes one to three months depending on the district. Second, your mortgage options are more restricted: LTV caps tend to be stricter (around 50–60%) and fewer banks will lend to non-resident, non-EU applicants. Working with a local property lawyer from the outset is strongly recommended.",
			},
			{
				q: "How much deposit do I need for a Cyprus mortgage as a non-resident?",
				a: "Budget for considerably more than a resident would. EU/EEA non-residents are typically offered 60–70% LTV, meaning a deposit of 30–40% of the purchase price. Non-EU nationals often face 50–60% LTV, implying a 40–50% deposit. The exact figure depends on the bank, the property, and your financial profile, and a larger deposit usually secures a better interest rate. On top of the deposit, budget for transfer fees or VAT, legal fees (often around 1% to 1.5% plus VAT), and bank arrangement and valuation fees.",
			},
			{
				q: "How long does a Cyprus mortgage application take for a non-resident?",
				a: "From formal application to final approval, the process generally takes one to three months. Most lenders issue an approval-in-principle within two to four weeks of receiving a complete application pack. The slower steps are typically the property valuation, legal due diligence on the title deed, and — for non-EU buyers — Acquisition Permit processing. Having all income documents certified, translated, and ready before you submit will materially reduce delays.",
			},
		],
	},
	{
		slug: "self-employed-tax-cyprus",
		datePublished: "2026-07-05",
		dateModified: "2026-10-02",
		lastChecked: "2026-10-02",
		sources: [
			{
				label: "Tax Department: Individual income tax return",
				url: "https://www.gov.cy/mof-tax/en/documents/forologiki-dilosi-eisodimatos-atomoy/",
			},
		],
		category: "tax",
		title: "Self-Employed Tax in Cyprus: 2026 Guide",
		description:
			"Freelancer or sole trader in Cyprus? This 2026 guide covers social insurance, GHS, VAT, income tax bands, and TD1 filing deadlines in plain English.",
		sections: [
			{
				heading: "Who Counts as Self-Employed, and How to Register",
				body: "In Cyprus, you are treated as self-employed if you work on your own account (as a freelancer, sole trader, consultant, or contractor) rather than under a contract of employment. There is no income floor that excuses you from registration: the obligation begins as soon as you start trading.\n\nThe registration sequence matters and must be followed in order. First, register with the Tax Department to obtain a Tax Identification Code (TIC, also called a TIN) by submitting Form T.D.2001. You can apply in person at your local Tax Department office or, once registered, via the TAXISnet portal. EU citizens with complete documentation typically receive their TIN on the same day. You must register within 60 days of commencing business activity; failure to do so can result in retrospective charges and interest.\n\nSecond, once you have your TIN, register with your local District Social Insurance Office by submitting the relevant self-employed registration form along with a copy of your identity document or passport. A Social Insurance number is typically issued within one to two weeks. Third, if your annual taxable turnover reaches or is expected to reach €15,600 in any rolling 12-month period, you must register for VAT with the Tax Department (see the VAT section below).\n\nIf you are deciding between sole-trader status and incorporating a limited company, the /tools/sole-trader-vs-ltd/ comparison tool can model the after-tax outcome for your expected profit level.",
			},
			{
				heading: "Social Insurance Contributions for the Self-Employed",
				body: "Self-employed individuals in Cyprus pay Social Insurance (SI) contributions at the current rate of 16.6% of their deemed insurable earnings. This rate has applied since 1 January 2024 (raised from 15.6% previously) and is scheduled to rise by roughly one percentage point every five years under the long-term financing plan for the fund.\n\nThe most important distinction for the self-employed is that contributions are not calculated on your actual net profit. Instead, the Social Insurance Services assign you to an occupational category and use a deemed (notional) income figure for that category. Minimum assessed income floors set a baseline below which contributions cannot fall, even if your real earnings are lower. These figures are reviewed and published annually by the Social Insurance Services; you should confirm the minimum and maximum for your specific trade or profession directly with them each year, as the published tables are updated and vary by occupation.\n\nFor 2026, the absolute maximum insurable earnings on which SI is calculated are €68,904 per year (€5,742 per month), raised from €66,612 in 2025. The state also contributes on top of your 16.6%, but only your 16.6% is your direct cost.\n\nSI contributions are paid quarterly. Late payments attract penalty interest. Use the social insurance calculator at /tools/social-insurance-calculator to estimate your quarterly liability based on your occupational category, and confirm the current category minimum with the Social Insurance Services.",
			},
			{
				heading: "GHS (GeSY) Health Contributions",
				body: "Alongside Social Insurance, self-employed individuals must contribute to the General Health System (GHS), known in Greek as GeSY. These contributions fund access to the public health network and cover a range of primary and specialist care.\n\nThe current GHS contribution rate for self-employed persons is 4% of their income, paid entirely by the individual. Unlike employees, there is no employer to share the cost. GHS contributions are capped: only annual income up to €180,000 is subject to the levy, making the maximum annual GHS payment €7,200.\n\nTo illustrate the combined contribution burden: a self-employed person with €40,000 of deemed insurable income pays 16.6% in SI (approximately €6,640) plus 4% GHS on income (€1,600), a combined annual total of roughly €8,240, before any income tax is considered. This contribution load is one of the key financial variables when comparing self-employment against operating through a limited company, where the structure and split of contributions differ. The /tools/sole-trader-vs-ltd/ tool models this comparison in full.\n\nGHS contributions are collected on a schedule alongside Social Insurance and must be kept current to maintain your entitlement to access GeSY services. If you are newly resident in Cyprus and uncertain about your entitlement, see the taxes-for-expats guide for residency-related context.",
			},
			{
				heading: "VAT: Threshold, Registration, and Ongoing Obligations",
				body: "VAT registration in Cyprus is mandatory once your taxable turnover exceeds €15,600 in any rolling 12-month period. The threshold is rolling, not calendar-year-based: it is not reset on 1 January. If your invoices accumulate to €15,600 across any consecutive 12 months, the registration obligation arises at that point. You must notify the Tax Department and register promptly; late registration can result in backdated VAT liability plus fines.\n\nThe standard VAT rate is 19%. A reduced rate of 9% applies to hotel accommodation, restaurant meals, and certain passenger transport; 5% applies to specific food, pharmaceuticals, books, and selected other goods. Most professional, consulting, digital, and IT services supplied to Cyprus-based consumers are subject to the full 19% standard rate.\n\nRegistered businesses must file VAT returns online (typically quarterly) and remit any VAT due by the statutory deadline. Accurate VAT record-keeping from the first day of registration is essential.\n\nVoluntary registration below the €15,600 threshold is permitted. It can be advantageous if you incur significant business expenses carrying input VAT, as registration lets you reclaim that VAT from the outset. However, it commits you to the full filing and record-keeping regime and requires you to charge VAT on your supplies. For the full registration process and required documentation, see the vat-registration-guide.",
			},
			{
				heading: "Income Tax Bands, the 2026 Reform, and Non-Dom Status",
				body: "Cyprus taxes self-employment income on net profit after allowable business expenses, using the same progressive income tax bands as employed individuals.\n\nTwo sets of bands are relevant in 2026. If you are filing your 2025 personal tax return (TD1) this summer, your 2025 income is taxed under the bands that applied to the 2025 tax year: 0% up to €19,500; 20% on €19,501 to €28,000; 25% on €28,001 to €36,300; 30% on €36,301 to €60,000; and 35% above €60,000.\n\nFor income earned in the 2026 tax year itself, reformed bands apply as part of Cyprus's comprehensive tax reform effective 1 January 2026: 0% up to €22,000; 20% on €22,001 to €32,000; 25% on €32,001 to €42,000; 30% on €42,001 to €72,000; and 35% above €72,000. These are widely reported by the major professional firms as enacted, but as with any recent reform you should confirm the position with a qualified Cyprus accountant before relying on it for planning.\n\nIf you hold non-domicile (non-dom) status in Cyprus, you are exempt from Special Defence Contribution (SDC), a levy that otherwise applies to dividends and interest for domiciled residents. Non-dom status can be highly valuable if you also receive foreign investment income alongside self-employment profits. See the /guides/taxes-for-expats/ guide for eligibility criteria.\n\nSelf-employed persons must also pay provisional (advance) income tax during the year, in two equal instalments (by 31 July and 31 December of the current tax year), based on estimated annual liability; underpaying significantly can attract interest on any shortfall when the annual return is filed.",
			},
			{
				heading: "Filing, Deadlines, and Penalties",
				body: "Self-employed individuals who are not required to prepare audited financial statements, broadly, those with annual turnover at or below €70,000, file their personal income tax return using Form TD1, submitted via the TAXISnet online platform. For the 2025 tax year, the Tax Department gives the deadline for submitting the return as 31 October 2026. Check TAXISnet and confirm with your accountant well before that date.\n\nSelf-employed persons with annual turnover above €70,000 whose accounts require an audit are subject to different, later deadlines; professional advice is recommended if this applies to you. Looking ahead, personal tax filing is transitioning from TAXISnet to the new Tax For All (TFA) system, so expect different procedures for the 2026 tax year onwards.\n\nPenalties for non-compliance are meaningful. Late filing of the TD1 attracts a fixed penalty of €100, plus €200 for each calendar month the return remains outstanding, up to a maximum of €17,000. Late payment of tax due attracts interest (recently 5% per annum) on the outstanding balance. Failure to register with the Tax Department or Social Insurance Services within the required window from commencing business results in retrospective contribution charges, accrued interest, and penalties.\n\nGiven the number of quarterly deadlines, the mid-year provisional tax payments, and the ongoing transition to TFA, engaging a Cyprus-qualified accountant from the outset is strongly recommended.",
			},
		],
		faqs: [
			{
				q: "Do I have to register for Social Insurance even if my self-employment income is very low?",
				a: "Yes. Social Insurance registration is mandatory for all self-employed persons in Cyprus regardless of income level — there is no earnings floor that exempts you. Moreover, contributions are calculated on deemed insurable earnings set by the Social Insurance Services for your occupational category, not on your actual net profit. Even in a low-income year you may owe contributions based on the minimum assessed income floor for your trade. Contact the Social Insurance Services directly to confirm the minimum deemed income for your specific occupation.",
			},
			{
				q: "Can I voluntarily register for VAT before my turnover reaches €15,600?",
				a: "Yes. Voluntary VAT registration is permitted in Cyprus below the mandatory €15,600 threshold. It makes financial sense if you have significant business expenses that carry input VAT, as registration allows you to reclaim that VAT. Bear in mind that once registered you must charge the applicable VAT rate (usually 19%) on your taxable supplies, file returns, and maintain proper VAT records. If your clients are VAT-registered businesses, they can generally reclaim the VAT you charge, making voluntary registration cost-neutral for them.",
			},
			{
				q: "What is 'deemed insurable income' and how is my Social Insurance bill calculated?",
				a: "Rather than using your actual net profit, the Social Insurance Services assign each self-employed person to an occupational category and apply a pre-set notional income figure — the deemed insurable income — to that category. Your 16.6% SI contribution is then calculated on that notional figure. Minimum and maximum income floors apply within each category and are revised annually. If your real income differs substantially you can request a reassessment, but you must initiate it. Use the /tools/social-insurance-calculator to estimate contributions and confirm your category minimum with the Social Insurance Services.",
			},
			{
				q: "Do I pay income tax during the year as well as when I file my annual return?",
				a: "Yes. Self-employed persons in Cyprus make provisional (advance) income tax payments in two equal instalments during the tax year: the first by 31 July and the second by 31 December, based on your estimated annual liability. Any balance is settled when you file your annual TD1 return, and if you overpaid you can claim a refund. Significantly underestimating your provisional tax can result in interest being charged on the shortfall, so calculate your estimate carefully.",
			},
		],
	},
	{
		slug: "airbnb-short-term-rental-cyprus",
		datePublished: "2026-07-05",
		dateModified: "2026-07-05",
		category: "property",
		title: "Airbnb & Short-Term Rentals in Cyprus 2026",
		description:
			"Cyprus Airbnb registration, tax, and short-term rental law for 2026 — the Deputy Ministry licence, 9% VAT, the SDC abolition, and the penalties for skipping it.",
		sections: [
			{
				heading: "Is Airbnb Legal in Cyprus?",
				body: "Short-term rentals — including listings on Airbnb, Booking.com, and Vrbo — are fully legal in Cyprus and have operated under a formal regulatory framework since February 2023. The governing legislation is the Regulation of the Establishment and Operation of Hotels and Tourist Accommodations Law (Law 34(I)/2019, as amended). Any individual or company advertising or letting a self-catering accommodation — furnished tourist villas, furnished tourist residences, or apartments — must be registered in the Register of Self-Service Accommodation maintained by the Deputy Ministry of Tourism.\n\nThe regime covers properties offered for rent for periods of fewer than 30 consecutive days. Properties let for 30 or more consecutive days fall under conventional residential tenancy rules, are exempt from the registration requirement, and do not attract the 9% VAT that applies to tourist accommodation.\n\nCyprus introduced this framework to bring short-term rentals into the same oversight regime as hotels and licensed tourist accommodation, and to address housing affordability concerns linked to the rapid growth of holiday lets. Several thousand properties are now formally registered, and enforcement against unregistered operators has intensified, with the Deputy Ministry running active compliance campaigns. If you are buying property in Cyprus specifically to let on Airbnb, factor the registration process and its ongoing obligations into your plans from the outset — see the buying-process guide.",
			},
			{
				heading: "How to Register with the Deputy Ministry of Tourism",
				body: "Registration is completed online through the Deputy Ministry of Tourism portal. You must submit your application before listing or advertising the property on any platform. The required documents are: a copy of your passport or Cyprus ID card (individuals) or certificate of incorporation and director details (legal entities); a Tax Identification Number (TIN) or VAT number issued by the Cyprus Tax Department; and a valid building or town-planning permit confirming the property is legally constructed and zoned for residential or tourist use.\n\nA non-refundable registration fee is payable on application. This is widely reported at €222 per property; however, because fees are set by ministerial regulation and may be revised, confirm the current figure directly with the Deputy Ministry before submitting. Once approved, registration is valid for three years, after which owners must renew and pay the fee again.\n\nOn approval, the Deputy Ministry assigns each property a unique Registration Licence Number (RLN). This number must be displayed prominently in every advertisement and booking-platform listing. Airbnb has provided a dedicated field for the number since January 2023; platforms may suspend or remove listings that do not include a valid one.\n\nNotify the Deputy Ministry of any material changes to the property during the registration period. Where a property is managed by a letting agent or management company, ensure the registration is held by, or formally linked to, the property owner — not the operator.",
			},
			{
				heading: "VAT and the €15,600 Turnover Threshold",
				body: "Short-term letting of residential property for tourist accommodation is treated as a supply of services for VAT purposes and attracts the reduced VAT rate of 9% — the same rate applied to hotels and other tourist lodgings in Cyprus. Long-term rentals of 30 or more consecutive days are exempt from VAT.\n\nYou are required to register for VAT once your annual taxable turnover from short-term letting exceeds €15,600 within any 12-month period. Once registered, you must charge 9% VAT on every booking, file VAT returns (typically quarterly), and remit the tax to the Cyprus Tax Department. You may reclaim input VAT on allowable expenses directly related to the rental activity — such as maintenance, furnishings, and management fees — provided these are properly documented.\n\nIf your turnover is below €15,600, VAT registration is not mandatory but is available voluntarily. Voluntary registration can be advantageous if you have significant start-up or refurbishment costs that generate recoverable input VAT.\n\nPlatforms such as Airbnb may collect and remit certain taxes on hosts' behalf under their tax-collection arrangements, but this does not remove your personal obligation to register and account for VAT once you exceed the €15,600 threshold. Never assume platform-side collection satisfies your statutory obligations — take independent advice from a Cyprus-registered accountant. For a broader view of property-related taxes, see the property-taxes-2026 guide.",
			},
			{
				heading: "Income Tax and the 2026 SDC Abolition",
				body: "Rental income from Cypriot property is pooled with other taxable income and subject to Cyprus's progressive personal income tax rates. Following the comprehensive tax reform passed by parliament on 22 December 2025, with amending laws published in the Official Gazette on 31 December 2025 and effective from 1 January 2026, the bands are: 0% on the first €22,000; 20% on €22,001–€32,000; 25% on €32,001–€42,000; 30% on €42,001–€72,000; and 35% on income above €72,000. A 20% deemed deduction for wear and tear is available against gross rental receipts before applying these rates.\n\nThe most significant 2026 change for landlords is the abolition of the Special Defence Contribution (SDC) on rental income from 1 January 2026. SDC previously applied at 3% on 75% of gross rent — an effective rate of 2.25% — for Cyprus-domiciled tax residents only; non-domiciled residents were already exempt. SDC on rental income is now abolished for all taxpayers, leaving standard income tax as the main charge on rental receipts.\n\nThe General Health System (GeSY) contribution of 2.65% on gross rental income continues to apply for Cyprus tax residents who are individuals, subject to an annual income ceiling across all sources. Legal entities are generally not subject to GeSY on rental income. Confirm your personal GeSY position with a qualified Cyprus accountant.\n\nA further reform point: from 1 July 2026, rent payments above €500 must be settled by traceable electronic means — bank transfer, card, or another recognised method — rather than cash, if the payer wishes to claim the deduction.",
			},
			{
				heading: "Penalties for Operating Without Registration",
				body: "Operating a short-term rental without a valid registration — or continuing to advertise after registration has lapsed — is an offence under Law 34(I)/2019. Reported penalties include a fine of up to €5,000, imprisonment of up to one year, or both, with a continuing daily fine that may additionally be imposed for each day the breach persists after a formal notice. Treat these figures as indicative and confirm the current penalty regime with a Cyprus lawyer.\n\nThe Deputy Ministry of Tourism has been actively pursuing unlicensed operators, with enforcement campaigns resulting in formal notices to property owners and management companies, and the government has stated its intention to tighten controls further. The authorities generally engage cooperatively with those actively seeking to comply, but this cannot be relied upon as informal protection against enforcement.\n\nBeyond regulatory penalties, platforms including Airbnb may suspend or remove listings that lack a valid registration number, cutting off your rental income immediately. That risk compounds the legal exposure.\n\nCritically, operating without registration does not exempt you from tax obligations. Tax authorities can assess income tax, VAT (if turnover exceeds €15,600), and GeSY on revenue earned from an unregistered property. Undeclared rental income may also come to light when you eventually sell, potentially affecting your position and attracting penalties and interest on historic shortfalls. Always seek independent legal advice if you are uncertain whether your property and rental arrangement require registration.",
			},
			{
				heading: "Short-Term vs Long-Term Rental Yield",
				body: "A short-term rental in a popular Cyprus coastal location can generate materially higher gross yields than a typical long-term residential tenancy in peak season. However, the headline gross yield of an Airbnb let is significantly eroded by costs that do not apply to long-term tenancies: the registration fee (renewable every three years), 9% VAT once turnover exceeds €15,600, property management fees that typically run at 15–25% of revenue, higher cleaning and maintenance costs, and significant vacancy outside the June–September peak season.\n\nLong-term rentals are administratively simpler: no tourism registration is required, no VAT applies, and management overhead is lower. Income tax and the 2.65% GeSY contribution apply equally to both rental strategies. From 2026 onwards, the SDC is abolished for both.\n\nBefore committing to a short-term strategy, model both scenarios against realistic occupancy rates and full expense assumptions. The rental yield calculator at /tools/rental-yield-calculator lets you input gross revenue, management fees, maintenance costs, and tax rates to compare net yields side by side — use it before you buy, not after.\n\nLocation matters considerably: coastal areas such as Limassol, Paphos, Ayia Napa, and Protaras command the highest short-term yields, while inland areas often favour long-term letting. For further context, see the property-taxes-2026 guide and the buying-process guide.",
			},
		],
		faqs: [
			{
				q: "Do I need to display my registration number on every Airbnb listing?",
				a: "Yes. Your Registration Licence Number (RLN) must appear in all advertisements and platform listings, including Airbnb, Booking.com, and Vrbo. Airbnb added a dedicated field for it in January 2023. Failure to include a valid number may result in the platform suspending or removing your listing, in addition to potential penalties under Law 34(I)/2019.",
			},
			{
				q: "Was the Special Defence Contribution on rental income abolished in 2026?",
				a: "Yes — for rental income specifically. The SDC on rental income was abolished from 1 January 2026 as part of Cyprus's comprehensive tax reform, passed by parliament on 22 December 2025 and published in the Official Gazette on 31 December 2025. Previously, Cyprus-domiciled tax residents paid SDC at an effective rate of 2.25% on gross rent (3% on 75% of rent); non-domiciled residents were already exempt. Standard income tax and the 2.65% GeSY contribution continue to apply to rental income.",
			},
			{
				q: "Do I have to charge 9% VAT on every short-term rental booking?",
				a: "Only once your total annual turnover from short-term letting exceeds €15,600. Below that threshold, VAT registration is not mandatory (though voluntary registration is available). Once you exceed €15,600 — even midway through the year — you must register for VAT and charge 9% on subsequent bookings. Long-term rentals of 30 or more consecutive days are VAT-exempt regardless of turnover.",
			},
			{
				q: "I am a non-domiciled Cyprus tax resident — does that change my obligations?",
				a: "Primarily in one respect: as a non-dom, you were already exempt from the Special Defence Contribution, so the 2026 abolition simply confirms a benefit you already had. Income tax at progressive rates and the 2.65% GeSY contribution on rental income both apply to non-dom Cyprus tax residents in the same way as to domiciled residents. The registration and VAT obligations under Law 34(I)/2019 apply regardless of domicile status. Seek advice from a Cyprus tax adviser on your overall income position and any applicable double-taxation treaty benefits.",
			},
		],
	},
];
