import type { GuideInfo } from "./guides";

/**
 * SEO content batch 1 (July 2026) — research-backed new guides.
 * Kept in a separate file for reviewability; spread into GUIDES in guides.ts.
 */
export const GUIDES_BATCH1: GuideInfo[] = [
	{
		slug: "yellow-slip-meu1-guide",
		datePublished: "2026-07-05",
		dateModified: "2026-07-05",
		category: "immigration",
		title: "Cyprus Yellow Slip (MEU1): 2026 Complete Guide",
		description:
			"Everything EU citizens need to register for the Cyprus yellow slip (MEU1) in 2026: documents, appointment booking, fees, and the UK biometric deadline.",
		sections: [
			{
				heading: "What the Yellow Slip Is and Why You Need It",
				body: "The yellow slip is the informal name for the Registration Certificate issued to EU, EEA, and Swiss citizens who exercise their right to reside in Cyprus for more than three months. The official application form is the MEU1, and once approved, the certificate is a physical document printed on yellow paper — hence the nickname that has stuck in every expat forum from Limassol to Paphos. Legally, it is your formal declaration of residency under EU Directive 2004/38/EC, which Cyprus has transposed into national law. Without it you exist in a grey area: physically present on the island but lacking the documented status that Cypriot banks, employers, GESY, and government departments will ask for at every turn. Opening a local bank account, registering with GESY (the national health scheme), enrolling children in school, and applying for a Cyprus tax identification number all typically require either the yellow slip itself or evidence that you have already applied. The MEU1 tracker at /tools/meu1-tracker lets you organise your document checklist and keep track of your application status in one place — genuinely useful given how much paperwork the process involves.",
			},
			{
				heading: "Who Must Register — and the Four-Month Deadline",
				body: "Any EU, EEA, or Swiss national who plans to remain in Cyprus for more than three months must register for a yellow slip. This covers employed workers, the self-employed, students, retirees, and financially independent individuals — there is no category exempt from the requirement. Cyprus law sets a four-month window from the date of first entry: if you arrive in January, your MEU1 application must be submitted by the end of April. There is no automatic extension, and the clock starts from arrival, not from the day you decide you are definitely staying. Families apply individually — each adult and registered child requires a separate MEU1, and each pays the application fee independently. EU citizens who are family members of other EU citizens apply on the same MEU1 form; non-EU family members (a non-EU spouse, for example) must instead apply for an MEU2 residence card, which is a longer and more involved process. A practical point worth flagging early: if you are arriving with children and your family documents originate from outside Cyprus, start gathering and apostilling those certificates immediately. Birth certificates and marriage certificates typically require both apostille certification and a certified Greek translation, which can add weeks to your timeline. The arrival-checklist guide at /guides/arrival-checklist covers those first steps in full.",
			},
			{
				heading: "How to Book an Appointment and Where to Apply",
				body: "MEU1 applications are submitted in person at one of five Civil Registry and Migration Department (CRMD) district offices across Cyprus: Nicosia, Limassol, Larnaca, Paphos, and Famagusta/Paralimni. Appointment requirements vary by district — some offices have accepted walk-ins for certain application categories, while others require advance booking — so contact your local office directly before making the trip. As a general rule, booking three to four weeks ahead is sensible, and during busy periods slots can fill faster. The CRMD headquarters can be reached by email at migration@crmd.moi.gov.cy; phone numbers and any updated online booking details for each district are listed on the gov.cy immigration portal. Lawyers and immigration advisers may attend to assist, but the applicant must be physically present — the application cannot be submitted by a representative on your behalf. Bring originals and photocopies of every document on your checklist: offices have been known to turn applicants away for a single missing item, and it is a long way to travel twice. For MEU1 applicants attending the Nicosia office, receipt on the same day is possible in many cases; in other districts, turnaround is typically within a few weeks.",
			},
			{
				heading: "Your Document Checklist, by Applicant Category",
				body: "Every applicant needs the same base set: a valid passport or national ID card (original plus copy), two recent colour passport photographs, a completed MEU1 form (available at the office or on gov.cy), proof of a Cyprus residential address, and the application fee of around €20. For proof of address, district offices typically require a rental agreement stamped by the relevant tax department office and certified by a Muhtar (the local community officer); a minimum one-year lease is the standard requirement. Beyond the base set, additional documents depend on your situation. Employed applicants need a signed employment contract, recent payslips, and confirmation of social insurance registration. Self-employed applicants need company registration documents, a tax identification number, and recent financial statements or tax returns. Financially independent and retired applicants need bank statements demonstrating regular and sufficient income, plus private health insurance with a minimum of €30,000 coverage if you are not contributing to GESY through local employment. Students need an official enrolment letter from their Cypriot institution, plus health insurance meeting the same threshold. For anyone travelling with a spouse or children, apostille-certified and translated marriage and birth certificates are essential — the single most common cause of a delayed or rejected MEU1 application is missing apostille certification on foreign family documents. The /guides/gesy-registration-guide covers health insurance options in detail if you are weighing up private cover versus GESY enrolment before you apply.",
			},
			{
				heading: "MEU1, MEU2, MEU3 — and the UK Biometric Deadline",
				body: "MEU1 is the initial registration certificate, but it sits within a wider family of documents. The MEU2 is a residence card for non-EU nationals who are family members of EU citizens — a third-country national spouse, for example — and it takes considerably longer to process: allow six to seven months. MEU2 holders can re-enter Cyprus during that wait using their submission receipt as evidence of status. After five years of continuous and legal residence in Cyprus, EU citizens and their qualifying EU family members become eligible for the MEU3 Permanent Residence Certificate, which carries stronger legal protections and is considerably harder to lose than the initial registration. MEU3 processing takes four to six months, and holders should be aware that an absence exceeding two consecutive years can forfeit permanent residence rights. For UK nationals, the situation is more specific post-Brexit. Those who were legally resident in Cyprus before 31 December 2020 hold paper MEU1 or MEU3 documents under the Withdrawal Agreement. These must be exchanged for new biometric residence cards — MUKW1 (for those with fewer than five years of residence) or MUKW3 (for those with five or more years). The mandatory deadline for this exchange is 3 August 2026, after which the paper documents will cease to be legally valid. Given that some district offices currently have appointment lead times stretching to several months, UK nationals who have not yet started this process should act without delay.",
			},
			{
				heading: "What Happens If You Miss the Deadline",
				body: "Missing the four-month registration window does not strip you of your underlying EU right to reside in Cyprus, but it does expose you to administrative penalties. Fines for late registration are tiered and, based on practitioner reports, typically start at a modest level for short delays and escalate for longer ones, with Cyprus law setting a substantially higher theoretical maximum. In practice, an unregistered EU citizen will encounter more immediate friction day-to-day: banks will not open accounts without a yellow slip, GESY enrolment becomes complicated, and many employers and landlords ask for the certificate as a matter of routine. If you have already missed the four-month window, the right course of action is to apply as soon as possible rather than waiting further — late applications are accepted, and acting promptly limits both the scale of any fine and the risk of further complications. Book the appointment first; do not wait until you have assembled a perfect document set. As for renewal: the MEU1 for EU citizens does not expire. Once issued, it remains valid indefinitely as long as you retain EU citizenship and your qualifying circumstances of residence continue. You are not required to renew or update it when you move address, though informing the CRMD of a change is sensible practice. The /tools/meu1-tracker is useful for staying on top of your application status and making sure you have the slip in hand before you urgently need it.",
			},
		],
		faqs: [
			{
				q: "Does the Cyprus yellow slip expire?",
				a: "No. For EU, EEA, and Swiss citizens, the MEU1 Registration Certificate has no expiry date and does not need to be renewed as long as you retain EU citizenship and your basis for residence remains the same. Non-EU family members hold an MEU2 residence card, which is valid for five years and must be renewed on expiry.",
			},
			{
				q: "How long does it take to get a yellow slip in Cyprus?",
				a: "For MEU1 (EU citizen) applications, processing at district offices can be as fast as the same day, and is typically completed within a few weeks. Allow up to a month in busier periods or if any of your documents require additional verification — the Nicosia office tends to be fastest.",
			},
			{
				q: "What is the difference between MEU1 and MEU3 in Cyprus?",
				a: "The MEU1 is the initial Registration Certificate for EU citizens who have been resident in Cyprus for more than three months. The MEU3 is the Permanent Residence Certificate, available after five years of continuous and uninterrupted legal residence. Both have indefinite validity, but MEU3 carries stronger legal protections and takes four to six months to process centrally.",
			},
			{
				q: "Do UK nationals in Cyprus still need a yellow slip?",
				a: "UK nationals who were legally resident in Cyprus before 31 December 2020 hold paper MEU1 or MEU3 documents under the Withdrawal Agreement, but must exchange these for new biometric residence cards (MUKW1 or MUKW3) by 3 August 2026 — after that date the paper documents will no longer be legally valid. UK nationals who arrived after 1 January 2021 do not hold EU free-movement rights and must follow a different residency route.",
			},
		],
	},
	{
		slug: "cyprus-schengen-guide",
		datePublished: "2026-07-05",
		dateModified: "2026-07-05",
		category: "immigration",
		title: "Is Cyprus in Schengen? 2026 Guide",
		description:
			"Cyprus is an EU member but remains outside Schengen. What that means for non-EU expats, UK nationals, and your 90/180-day travel planning.",
		sections: [
			{
				heading: "Current Status: Cyprus Is Not in Schengen",
				body: "Cyprus has been a full member of the European Union since 2004, but it remains outside the Schengen Area — the passport-free travel zone that covers most of Europe. As of mid-2026, Cyprus and Ireland are the only EU member states still outside Schengen, after Bulgaria and Romania completed their full accession.\n\nAccession has long been a stated priority for the Cypriot government, and meaningful progress has been made. A critical milestone came in 2023, when Cyprus was connected to the Schengen Information System (SIS) — the shared security and border database used by all member states. By the end of 2025, the government confirmed it had met the technical requirements, and in early 2026 the European Commission completed its formal compliance evaluation, with Cypriot officials stating publicly that the required boxes had been ticked.\n\nWhat remains is a political decision: unanimous approval from the EU Council. Some member states have raised concerns linked to the unresolved Green Line buffer zone that divides the island — a security question without a straightforward answer.\n\nThere is no confirmed accession date. Travellers and expats should plan on the basis that Cyprus remains outside Schengen for the foreseeable future, and verify the latest status before making decisions that depend on it.",
			},
			{
				heading: "What It Means for EU Citizens",
				body: "If you hold an EU passport, the Schengen question is largely irrelevant to your day-to-day life in Cyprus. As a full EU member state, Cyprus is bound by freedom of movement rules under EU Directive 2004/38/EC, which grants EU citizens — and their qualifying family members — the right to live, work, study, and travel throughout the bloc indefinitely. No visa is required and no 90-day cap applies.\n\nThis means you can relocate to Cyprus, stay as long as you wish, travel freely to Spain, Germany, France, or any other EU country, and return without restriction. The only practical inconvenience is at the airport: because Cyprus is not part of Schengen, you will pass through passport control when flying between Cyprus and Schengen countries — even on routes between two EU states. Once Cyprus joins Schengen, those checks will disappear and intra-EU travel from the island will become seamless.\n\nFor EU citizens moving to Cyprus long-term, the key administrative requirements are registering with the local authorities and obtaining a yellow slip (registration certificate) within four months of arrival. These are formalities rather than barriers — Cyprus actively welcomes EU nationals. Our residency-and-visas guide covers the registration process in full, including what documentation to bring and how long it takes.",
			},
			{
				heading: "Non-EU Residents: The 90/180-Day Advantage",
				body: "For non-EU nationals, Cyprus's status outside Schengen is one of its most underappreciated practical advantages. The core rule is straightforward: days spent in Cyprus do not count towards the Schengen 90/180-day limit. Only time spent within the Schengen member states is counted.\n\nThis creates a genuinely powerful base-building opportunity. A US, Australian, or South African citizen holding a Cyprus long-term residence permit can spend months on the island — subject to permit conditions — and still arrive in France, Italy, or Germany with a full 90-day Schengen allowance intact. By contrast, a non-EU person basing themselves in Portugal or Spain consumes that same allowance with every passing week.\n\nThere is one important caveat: a Cyprus residence permit does not grant visa-free access to Schengen countries. You still need either a Schengen visa, or a passport that qualifies for visa-free Schengen entry. The permit establishes your legal right to live in Cyprus — it does not extend that right to the rest of Europe. This is expected to change upon Schengen accession, but for now the two systems operate entirely independently.\n\nFor anyone navigating these options, our visa-pathway-finder tool can match your nationality and lifestyle against the available permit routes, and our digital-nomad-visa-guide covers a popular route for remote workers who want to use precisely this advantage.",
			},
			{
				heading: "UK Nationals Post-Brexit: A Separate Allowance",
				body: "Brexit fundamentally changed the travel equation for British nationals. Since 1 January 2021, UK passport holders are treated as third-country nationals across the EU, subject to the same rules as any non-EU traveller. That means the Schengen 90/180-day rule applies whenever Brits travel to France, Spain, Germany, Greece, or any of the other Schengen countries. Every day counts.\n\nWhere Cyprus stands apart is that it operates a completely separate 90/180-day allowance. British nationals can spend up to 90 days in any 180-day period in Cyprus without a visa, and those days have no impact on their Schengen tally. In practical terms, a British traveller could exhaust their full 90 Schengen days on a trip around southern Europe, then fly directly to Limassol and spend a further 90 days on the island — entirely within the law.\n\nFor British expats establishing long-term residency in Cyprus, the arrangement is even more favourable. A Cyprus residence permit removes the short-stay 90-day cap altogether, allowing indefinite stays on the island while leaving the Schengen allowance fully intact for European travel.\n\nThe dual-allowance structure makes Cyprus arguably the most practical EU base for British nationals post-Brexit. Our residency-and-visas guide walks through the specific permit routes available, including the popular Category F (financially independent person) route that many British retirees and remote workers use.",
			},
			{
				heading: "Counter-Intuitive Travel Planning Advantages",
				body: "Once you understand that Cyprus occupies an EU-but-not-Schengen position, a set of planning advantages emerge that most new expats miss entirely.\n\nThe base effect is the most significant: non-EU residents and UK nationals can treat Cyprus as a permanent anchor, making trips into the Schengen zone as their 90-day allowance allows and returning to reset the clock. This is considerably more flexible than basing yourself anywhere in mainland Europe, where every day of residency erodes the same allowance you need for travel.\n\nThe multi-entry Schengen visa point is also worth knowing. Holders of a valid double or multiple-entry Schengen visa can generally enter Cyprus for a short stay without needing a separate Cyprus visa — a useful simplification for frequent travellers, though some nationalities are excepted and must obtain a Cyprus visa regardless. Always confirm the current rule for your passport before you travel.\n\nEntry and border-technology systems are also evolving across Europe (the EU's Entry/Exit System and the forthcoming ETIAS travel authorisation), and how and when they apply to Cyprus versus the Schengen zone has been changing. Because these rules are in flux, check the current requirements for your nationality and route close to your travel date rather than relying on older guidance — our visa-pathway-finder is a good starting point.",
			},
			{
				heading: "When Accession Happens: What Changes for Expats",
				body: "Cyprus's eventual Schengen accession will bring genuine benefits, but it will also remove some of the advantages that non-EU expats and UK nationals currently enjoy. It is sensible to plan for both scenarios.\n\nOn the upside: once Cyprus joins Schengen, holders of a Cyprus residence permit from non-EU countries will likely gain the right to travel across Schengen states without needing a separate visa. Passport checks on intra-Schengen flights from Cyprus will disappear. The island will become a fully integrated part of the European travel zone, which will simplify movement considerably.\n\nOn the downside for non-EU residents without a long-term permit: days spent in Cyprus will start counting towards the Schengen 90/180-day limit. The separate-allowance advantage that makes Cyprus such an attractive base today will be gone. Non-EU short-stay visitors will no longer be able to treat Cyprus as an unlimited backstop after exhausting their Schengen days.\n\nGiven that final approval requires a unanimous EU Council vote — and at least some member states have raised objections linked to the Green Line — accession is unlikely to arrive without meaningful advance notice. The process moves slowly. Watch official EU Council announcements and the Cypriot Civil Registry and Migration Department for developments, and use our visa-pathway-finder to choose a permit route that works under both the current and any future framework.",
			},
		],
		faqs: [
			{
				q: "Does a Cyprus residence permit let me travel freely in the Schengen zone?",
				a: "No. A Cyprus residence permit is issued under Cypriot national law and entitles you to live in Cyprus — it does not grant visa-free entry to Schengen countries. For Schengen travel, you still need either a Schengen visa or a passport that qualifies for visa-free entry. This is expected to change if Cyprus formally joins Schengen, at which point a Cyprus residence permit would likely confer Schengen travel rights. Until that happens, treat the two systems as entirely separate.",
			},
			{
				q: "Do days spent in Cyprus count towards my 90-day Schengen allowance?",
				a: "No. Because Cyprus is outside the Schengen Area, time spent there is completely separate from the Schengen 90/180-day calculation. You could spend six months in Cyprus without using a single Schengen day. This is one of the most significant practical advantages of establishing residency in Cyprus as a non-EU or UK national: your full Schengen allowance is preserved for European travel.",
			},
			{
				q: "Can I enter Cyprus using a Schengen visa?",
				a: "It depends on the type of visa and your nationality. A single-entry Schengen visa does not grant entry to Cyprus, which operates its own visa regime. Holders of a valid double or multiple-entry Schengen visa can generally enter Cyprus for a short stay without a separate Cyprus visa, but some nationalities are excepted. Always confirm the current rule for your passport before travelling.",
			},
			{
				q: "When will Cyprus join Schengen — is there a confirmed date?",
				a: "There is no confirmed date as of mid-2026. Cyprus has completed the technical requirements, including connection to the Schengen Information System and a European Commission evaluation. The remaining step is unanimous approval from the EU Council — a political decision, not a technical one, with some member states raising concerns about the Green Line dividing the island. Treat accession as a goal rather than a certainty for any specific year, and monitor official EU Council updates.",
			},
		],
	},
	{
		slug: "moving-to-cyprus-from-israel",
		datePublished: "2026-07-05",
		dateModified: "2026-07-05",
		category: "immigration",
		title: "Moving to Cyprus from Israel: 2026 Guide",
		description:
			"Practical guide for Israelis relocating to Cyprus: residency options, tax-exit realities, the Limassol community, pet import rules, and banking.",
		sections: [
			{
				heading: "Why Israelis Choose Cyprus",
				body: "Cyprus is, by some distance, the most accessible European destination for an Israeli national. Ben Gurion International is barely an hour from Larnaca by air: dozens of direct flights operate each week on carriers including El Al, Arkia, Israir, Wizz Air, Aegean, Cyprus Airways, airHaifa, and TUS Airways, with fares that can start very low. The cultural and climatic overlap is considerable: a Mediterranean coastline, dry summers, and an outdoor-centred lifestyle closely mirror what most Israelis already know.\n\nBeyond convenience, Cyprus offers a genuinely competitive tax environment. The island levies a 15% corporate tax rate (raised from 12.5% in the 2026 tax reform), and its non-domicile (non-dom) regime exempts qualifying residents from Special Defence Contribution on passive income — effectively 0% tax on dividends and interest for up to 17 years, subject only to a modest GHS health levy. As an EU member state, Cyprus also opens an eventual path to an EU passport after several years of qualifying residence. The island is actively pursuing Schengen Area membership, though final accession requires unanimous EU Council approval and no date has been confirmed — see our cyprus-schengen-guide for the current picture.\n\nFor many Israelis the most immediate draw is the established community already on the ground. Hebrew-speaking schools, kosher supermarkets, Israeli-run professional firms, and an active social calendar reduce much of the social risk that normally comes with an international move.",
			},
			{
				heading: "Residency Options for Non-EU Israelis",
				body: "As non-EU nationals, Israelis have no automatic right of residence in Cyprus and must apply for a permit. Three routes are most relevant.\n\nPermanent Residency by Investment (sometimes called the Golden Visa) is the fastest permanent option. A minimum purchase of €300,000 in a newly built residential property — bought directly from a developer on the primary market — qualifies the main applicant, spouse, and minor children for lifelong permanent residency. The applicant must also demonstrate secured annual income from abroad (with additional amounts for dependents). Processing currently takes several months, and permit holders must visit Cyprus at least once every two years to maintain status.\n\nThe Digital Nomad Visa suits remote workers and the self-employed earning at least €3,500 net per month from non-Cypriot clients or employers. The permit lasts one year and can be renewed for a maximum of three years, and the government expanded the total permit cap in recent years.\n\nCategory F is a passive-income residency route with a low income bar, but it carries a serious caveat: the current processing backlog can run to several years, and applicants cannot work in Cyprus under this route. It suits those planning well ahead rather than those seeking near-term residency.\n\nOur residency-and-visas guide explains eligibility criteria and documentation for each pathway in full.",
			},
			{
				heading: "The Israeli Tax-Exit Reality",
				body: "This is the aspect that most distinguishes an Israeli relocation from a British or European one, and it demands specialist advice before you move.\n\nIsrael determines tax residency through the 'centre of life' test, a holistic assessment of where your personal, family, economic, and social ties are concentrated. Day-counting matters but is not conclusive: the Israeli Tax Authority can consider you a tax resident even if you spend most of the year outside Israel, if your family, property, business interests, or social connections remain there. Terminating Israeli tax residency requires relocating the real substance of your life, not simply your address.\n\nWhen you do formally exit, an exit tax can apply: assets may be treated as having been sold on the day before you ceased to be an Israeli tax resident, with capital gains on unrealised appreciation assessed at that point. The Tax Authority can scrutinise residency status for years after departure, so maintaining clear documentation of your re-established life in Cyprus is important.\n\nCritically, Israel and Cyprus have not signed a double taxation agreement as of mid-2026. There is no bilateral mechanism to automatically prevent the same income being taxed in both countries. Cyprus's non-dom regime removes most Cyprus-side tax on passive income (see the non-dom section of /guides/taxes-for-expats/), but this does not resolve Israeli-side obligations if residency has not been genuinely severed. Use our double-tax-treaty-finder for related treaty context, and engage an adviser experienced in both Israeli and Cypriot tax law before making any decisions.",
			},
			{
				heading: "The Israeli Community and Daily Life",
				body: "Limassol is the centre of Israeli expat life in Cyprus. The community has grown substantially over recent years, driven by successive waves of relocation linked to security concerns, political uncertainty, and tax planning. The city's beachfront strip — particularly the Germasogeia area — has Hebrew-language schooling options, kosher supermarkets and restaurants, Israeli-run legal and financial firms, and a well-attended calendar of cultural and community events. For many new arrivals the experience is of a familiar, established community transplanted to a slower and sunnier setting.\n\nLarnaca hosts a smaller but well-established Israeli presence, with its international airport sitting minutes from the city — making it the natural first port of call for those who place high value on quick access to Tel Aviv. Multiple daily flights make weekend visits to family or clients in Israel routine rather than exceptional.\n\nPractical daily life is straightforward. Israeli citizens need no visa to enter Cyprus for stays of up to 90 days, and English is widely spoken across business, healthcare, government agencies, and schools. Greek is the official language, and a few phrases are appreciated socially, but you will encounter no barrier to functioning fully in English in any urban area.\n\nOne practical adjustment: Cyprus drives on the left. The Mediterranean climate, fresh produce markets, and outdoor hospitality culture are, by contrast, immediately familiar.",
			},
			{
				heading: "Bringing Your Pets from Israel",
				body: "Cyprus follows EU pet travel rules, which categorise non-EU countries into a simplified route (no titre test) and a fuller-requirements route. Whether Israel qualifies for the simplified route depends on its current classification under EU pet-travel regulations — confirm Israel's status with your Israeli vet or the Cyprus Veterinary Services department before planning your timeline, as classifications can change.\n\nIf a rabies antibody titre test is required, the process runs in strict sequence: have your pet microchipped first (ISO standard 11784 or 11785), then vaccinate against rabies once the animal is old enough. A blood sample for the titre test must be taken at least 30 days after vaccination and sent to an EU-approved laboratory. You must then wait a further period (which can be up to three months) after a satisfactory titre result before entering Cyprus. That waiting period is the critical timeline constraint — it cannot be shortened.\n\nFrom first vaccination to arrival in Cyprus, the full process can take several months. You will also need an official veterinary health certificate, valid for a limited window from its date of issue.\n\nOur moving-to-cyprus-with-pets guide has a full step-by-step checklist, guidance on EU-approved laboratories, and notes on which airlines accept pets on the Tel Aviv–Larnaca route.",
			},
			{
				heading: "Banking and First Steps in Cyprus",
				body: "Cyprus's banking sector operates under EU regulation, and deposits are protected up to €100,000 per depositor per institution under the European Deposit Guarantee Scheme. The main retail banks include Bank of Cyprus, Eurobank Cyprus, Alpha Bank Cyprus, AstroBank, and Ancoria Bank. AstroBank and Ancoria are frequently recommended by the expat community for their more relationship-focused approach with international clients.\n\nOpening an account as a new arrival typically requires: a valid passport, proof of a Cyprus address (a rental agreement or recent utility bill), documentation of your source of funds (payslips, tax returns, dividend statements, or business accounts), and — once registered with the authorities — your Cyprus Tax Identification Number. All banks apply enhanced know-your-customer checks under EU anti-money-laundering rules, so expect detailed questions about the origin of funds, particularly if significant amounts are being transferred internationally.\n\nWhile your account application is in progress, fintech platforms such as Wise or Revolut provide a practical bridge: both issue euro IBANs, support SEPA transfers, and are accepted by many Cypriot landlords and service providers.\n\nA sensible first-steps sequence: confirm and apply for your chosen residency route; sign a rental or purchase contract; register with the Civil Registry and Migration Department; open a local bank account; and register for Cypriot tax. Our banking-in-cyprus guide covers each stage in detail, including what to do if an initial application is delayed.",
			},
		],
		faqs: [
			{
				q: "Do Israelis need a visa to live in Cyprus?",
				a: "Israeli citizens do not require a visa to visit Cyprus for stays of up to 90 days in any 180-day period. To stay longer or establish legal residence, you must hold a valid Cyprus residency permit — the Permanent Residency by Investment, Digital Nomad Visa, or Category F, depending on your circumstances. Purchasing a property or receiving a job offer does not in itself confer the right to reside.",
			},
			{
				q: "Is there a tax treaty between Israel and Cyprus?",
				a: "No. As of mid-2026, Israel and Cyprus have not signed a double taxation agreement. This is a material planning consideration: without a bilateral treaty, income can in principle be assessed in both countries without automatic credit mechanisms. Cyprus's non-dom status removes most Cyprus-side tax on dividends and interest, but Israeli-side obligations depend entirely on whether you have genuinely severed Israeli tax residency under the 'centre of life' test. Engaging a cross-border Israeli–Cypriot tax specialist is strongly recommended before you move.",
			},
			{
				q: "How long does it take to bring a pet from Israel to Cyprus?",
				a: "Allow several months from your pet's first rabies vaccination to the date you arrive in Cyprus. The key bottleneck is a potential waiting period (up to three months) after a satisfactory rabies titre test result — this period cannot be shortened. Whether the titre test is required at all depends on Israel's current EU classification, so confirm with Cyprus Veterinary Services before booking flights. Our moving-to-cyprus-with-pets guide has a full timeline checklist.",
			},
			{
				q: "Where do most Israelis live in Cyprus?",
				a: "The majority are concentrated in Limassol, which has Hebrew-language schooling options, kosher food, Israeli restaurants, and an active professional network serving new arrivals. Larnaca has a smaller but well-established Israeli community and is particularly convenient given its direct airport connection to Tel Aviv.",
			},
		],
	},
];
