import type { GuideInfo } from "./guides";

export const GUIDES_G5: ReadonlyArray<GuideInfo> = [
  {
    slug: "car-import-registration",
    title: "Importing and Registering a Car in Cyprus",
    description:
      "What it actually costs to bring your car to Cyprus — customs duties, registration tax, KTEO roadworthiness testing, and an honest verdict on whether importing beats buying locally. Prices and rules change — verify with official Cyprus sources before acting.",
    sections: [
      {
        heading: "Customs duty: EU vs non-EU origin",
        body: "The first question is where your car was manufactured or last registered. If it originates from an EU member state and you have proof of EU customs clearance (standard for any car purchased new in the EU), no customs import duty applies when bringing it to Cyprus — it enters as intra-EU movement of goods. If the car originates from a non-EU country (Japan, USA, Korea) and has not been previously cleared through EU customs, you face a 10% customs duty on the customs value, plus 19% Cyprus VAT on the combined customs value plus duty. On a car worth €20,000, that math produces roughly €2,000 duty plus €4,180 VAT — a total landing cost of €26,180 before any registration tax. Cars imported by individuals relocating to Cyprus for the first time may qualify for a personal-effects exemption from duty if the car was owned and used abroad for at least six months prior to relocation; this exemption must be applied for at the Customs Department before the car is released.",
      },
      {
        heading: "Registration tax: the biggest surprise cost",
        body: "Registration tax in Cyprus is separate from customs duty and applies to all cars being registered for the first time on the Cyprus vehicle register, regardless of origin. The rate is calculated based on engine size and vehicle age. Broadly: cars up to 1,450cc attract 0–2%, 1,451–1,800cc attract 10–13%, and above 1,800cc attract 15–17%, applied to the taxable value (which is assessed by the Tax Department at the time of registration, not the invoice price). An older vehicle gets a reduction — there are age depreciation tables that reduce the taxable value by 5–25% depending on the age bracket. A 2022 1.6L petrol hatchback with a market value of €15,000 might attract registration tax of approximately €1,500–€2,000. Electric vehicles attract significantly lower registration tax (typically under 2%) as an incentive, which is a meaningful consideration if you are comparing options.",
      },
      {
        heading: "KTEO roadworthiness test and VIN check",
        body: "All imported cars must pass a KTEO (Κέντρο Τεχνικού Ελέγχου Οχημάτων — Cyprus Road Transport Department technical inspection centre) test before they can be registered. The test costs approximately €40–€45 for a private car and checks brakes, lights, emissions, tyre condition, steering, and body integrity. KTEO has centres in all major cities; you can book online at kteo.com.cy. A VIN (Vehicle Identification Number) check through the Transport Department verifies the car's history is not in the stolen vehicle register and that the mileage is consistent. Note that Cyprus drives on the left — cars imported from right-hand-drive countries (UK, Japan, Australia) are immediately usable, while left-hand-drive cars from continental Europe or the US are legal but less practical for daily driving on left-side roads.",
      },
      {
        heading: "Insurance and personalised plates",
        body: "Third-party insurance is compulsory and must be in place before you can register the vehicle. An annual third-party insurance policy for a standard private car runs €200–€400 depending on the driver's age, no-claims history, and car value; comprehensive cover runs €500–€900. Insurance must be arranged through a Cyprus-licensed insurer — your home-country policy does not transfer. After registration, the vehicle receives standard Cyprus registration plates (format: three letters followed by three numbers). Personalised or 'cherished' plates are available through the Traffic Department in Nicosia; a set of personalised plates currently costs €2,000–€4,000 depending on the combination chosen. The process is bureaucratic but straightforward: fill in the application, pay the fee, wait 4–8 weeks for approval.",
      },
      {
        heading: "Is importing worth it? The honest verdict",
        body: "For most relocators, importing a car from outside the EU is not financially rational unless the car is less than three years old and has strong residual value. Add up customs duty (non-EU only), registration tax, KTEO test, shipping costs (€800–€2,500 from Western Europe, €3,000–€6,000 from North America or Asia), and the time investment, and you typically exceed the cost of buying the equivalent car locally from a Cypriot dealer. The local used car market is well-stocked with 2–5 year old European models at reasonable prices: a well-maintained 2020 Toyota Yaris runs €9,000–€12,000, a 2021 VW Golf €14,000–€18,000. Where importing makes sense: UK residents bringing a recent right-hand-drive car (no customs duty, reasonable shipping cost of €300–€600 by RoRo ferry, and they lose no premium by converting the car to a non-UK market). For those driving down from continental Europe and entering as a resident, the personal-effects exemption can make it worthwhile for cars below €25,000.",
      },
    ],
  },
  {
    slug: "car-rental-long-term",
    title: "Long-Term Car Rental in Cyprus — vs Buying Analysis",
    description:
      "Monthly costs for renting a car for 3–12 months in Cyprus, a genuine break-even analysis against buying used, and which rental companies actually offer expat-friendly long-term deals.",
    sections: [
      {
        heading: "What long-term rental actually costs",
        body: "Long-term rental (loosely defined as 1–12 months) in Cyprus occupies the gap between daily hire and car ownership. For a compact car — a Toyota Yaris, Opel Corsa, or similar — monthly rates from established companies run €600–€900 all-in (basic third-party insurance included, unlimited kilometres). For a mid-size SUV like a Toyota RAV4 or Nissan Qashqai, expect €900–€1,400 per month. These figures assume a minimum 3-month commitment; shorter terms push rates up by 20–40%. The pricing includes standard third-party insurance but not comprehensive cover, which is an important distinction — if you damage the car, you are liable for repair costs up to the excess amount, which runs €500–€2,000 depending on the company and car. Full insurance upgrades (CDW — Collision Damage Waiver, plus theft protection) add €80–€200 per month. Factor this in when comparing total costs.",
      },
      {
        heading: "Who offers expat-friendly long-term rentals",
        body: "Not every rental company is comfortable with a 6-month expat arrangement — some are oriented towards tourists and don't want to process monthly billing or manage longer insurance documentation. The companies that reliably handle long-term expat rentals in Cyprus: Europcar Cyprus (offices in Larnaca, Limassol, Paphos, Nicosia) has a dedicated long-term division and will negotiate 3–12 month contracts; rates drop meaningfully at 6+ months. Hertz Cyprus offers similar long-term programmes, particularly from their Limassol and Nicosia branches. Among local operators, Panayides Autocenter in Paphos and Axis Car Rentals in Limassol are well-regarded among the expat community for flexible terms. Budget and Sixt operate in Cyprus but are primarily tourist-focused and less flexible on multi-month arrangements. For the best rate, contact the long-term desk directly rather than booking online — the website rates are tourist rates.",
      },
      {
        heading: "Buying used: the comparison case",
        body: "The alternative anchor is buying a used car outright. A well-maintained 2018–2020 compact (Yaris, Corsa, or Honda Jazz) costs €7,000–€10,000 from a dealer with basic warranty. A 2019–2021 SUV (Nissan Qashqai, Renault Kadjar) runs €12,000–€18,000. Additional annual ownership costs: comprehensive insurance €500–€900, annual road tax €50–€150 depending on engine size, annual KTEO inspection €45, tyres (allow €300–€400 every 3–4 years), maintenance (budget €400–€700 per year for a well-maintained car). Depreciation runs roughly 10–15% per year at current Cyprus used-car values. Selling the car when you leave is possible but adds friction — private sales in Cyprus take 4–8 weeks on average, and dealer buybacks offer 15–20% below market. These are the real costs that the 'just buy a cheap car' advice ignores.",
      },
      {
        heading: "Break-even analysis: the numbers",
        body: "If you rent a compact at €750 per month (mid-range with basic insurance), you spend €9,000 over 12 months with zero residual value. If you buy the equivalent car for €9,000 and sell it for €7,500 a year later (typical 15% depreciation), your net cost is €1,500 plus approximately €1,500 in insurance and running costs — total €3,000 for the year. Buying beats renting financially at 12 months by a large margin. The break-even point — where renting and owning cost the same — is roughly 4–6 months, depending on how efficiently you can sell the car when you leave. For stays under 4 months, rent. For stays over 6 months where you intend to sell on departure, buy. For stays in the 4–6 month grey zone, lean towards buying if you have the administrative capacity and time to manage a private sale; rent if you prefer simplicity.",
      },
      {
        heading: "Practical details: kilometre limits, insurance, and deposits",
        body: "Most long-term rental contracts include unlimited kilometres — this is standard in Cyprus, unlike some southern European markets where monthly caps apply. Verify this explicitly before signing. Insurance excess (your liability in case of an accident) is the critical term to check: basic packages have excess amounts of €1,000–€2,000; upgrading to zero-excess cover adds €100–€180 per month but removes all financial risk from minor damage. Deposits for long-term rentals run €300–€800, typically held on a credit card rather than charged. Foreign credit cards (Visa, Mastercard) are accepted by all major companies; Amex is less reliably accepted. Driving licence requirements: an EU driving licence is accepted directly. Non-EU licences are accepted for 6 months after establishing Cyprus residency, after which you are required to exchange for a Cyprus licence — this is relevant for anyone doing a 9–12 month rental while their residency status settles.",
      },
    ],
  },
  {
    slug: "airport-transfers-guide",
    title: "Getting from Cyprus Airports to Your Destination",
    description:
      "Fixed taxi rates, intercity buses, shared transfer services, and Bolt availability from Larnaca and Paphos airports — with realistic journey time estimates for every major route.",
    sections: [
      {
        heading: "Larnaca Airport: your options at a glance",
        body: "Larnaca International Airport (LCA) is Cyprus's main hub and handles the majority of international arrivals. The taxi rank is immediately outside arrivals — licensed taxis have fixed rates for major routes, displayed at the rank and regulated by the government. Current published rates: Larnaca city centre €20, Ayia Napa €35–€40, Protaras €45, Limassol city €50–€60 (depending on exact destination), Nicosia €50, Paphos €100–€110. These are one-person rates; most drivers do not add supplements for luggage or late-night arrivals, but confirm before entering. Journey times: city centre 15–20 minutes, Ayia Napa 45 minutes, Limassol 55–70 minutes, Nicosia 50–65 minutes. For the Limassol and Nicosia routes, shared taxi services (see below) offer the same journey at significantly lower cost. Bolt (the Uber equivalent in Cyprus) is available at Larnaca but has inconsistent coverage at the airport itself — it works well for rides from the city but airport pickups depend on driver availability.",
      },
      {
        heading: "Paphos Airport: taxis and connections",
        body: "Paphos International Airport (PFO) serves Paphos, western Cyprus, and overflow tourist traffic from Limassol. The fixed taxi rates from Paphos airport are: Paphos city centre and tourist area €15–€20, Limassol €45–€55, Nicosia €90–€100, Larnaca €100–€115. Journey times: Paphos centre 15–20 minutes, Limassol 45–55 minutes, Nicosia 90–100 minutes. Paphos is well served by local taxi drivers who know the international community and will quote reasonable rates; the official taxi rank outside arrivals has metered and fixed-rate options. Bolt does operate in Paphos city but airport coverage is limited — do not rely on it for an airport pickup with luggage, particularly in the evening. For the Limassol route, a local private transfer service called A2B Transfer and several Limassol-based operators offer pre-booked fixed-price transfers that are often cheaper than taxis for two or more passengers.",
      },
      {
        heading: "OSYPA intercity buses from airports",
        body: "OSYPA (the Cyprus intercity bus operator) runs routes connecting Larnaca airport to Larnaca city centre and Limassol. The Larnaca airport to Limassol express bus runs several times daily on weekdays and costs approximately €4–€8; journey time is about 90 minutes, stopping in Larnaca first. OSYPA's schedules are available at intercitybuses.com — the timetable is broadly reliable but does not operate the same frequency as a train network, so check the last departure time before relying on it for a late-night flight. From Paphos airport, there is no direct intercity bus service to the airport terminal; the nearest bus stop is on the main road roughly 1km away, served by routes into Paphos town (€1.50). Most Paphos airport arrivals use taxis or pre-booked transfers. For arrivals with heavy luggage or late-night flights, the cost difference between a €6 bus and a €20 taxi is rarely worth the inconvenience.",
      },
      {
        heading: "Shared transfer services and the Bolt alternative",
        body: "For the high-traffic Larnaca–Limassol and Larnaca–Nicosia corridors, shared transfer services are the best value option. KIKA Transfers and Cyprus Bus operate pre-booked shared minivan services that collect you from the arrivals hall, potentially pick up 2–3 other passengers heading the same direction, and drop you at your Limassol or Nicosia address. Pricing: approximately €15–€20 per person to Limassol, €18–€22 to Nicosia. Book in advance on their websites — arriving and hoping for a spot is risky during peak tourist season. Bolt operates across Cyprus (Limassol, Larnaca, Nicosia, Paphos) and is the default ride-hailing option for point-to-point journeys within cities. Prices are 30–50% lower than licensed taxis for city journeys. For airport-to-city journeys, Bolt works but requires pre-booking via the app as airport driver availability is inconsistent. For late-night arrivals at Larnaca (say, a 2 AM EasyJet flight), budget for a licensed taxi — Bolt and shared services wind down after midnight.",
      },
      {
        heading: "Tips for smooth arrivals and late-night logistics",
        body: "Three practical notes from regular Cyprus travellers. First, have your destination address written down (not just 'the Limassol marina area') — taxi drivers know landmarks but not all know every building name, and the GPS on some older taxis is unreliable for new developments. Second, Cyprus taxis accept cash (euros) and most now accept cards — always confirm card payment before the journey begins, since a few older drivers still only take cash. Third, for group arrivals of three or more, a private transfer pre-booked online is almost always cheaper than splitting a licensed taxi: compare rates on Taxiplon, ICT Cyprus, and Paphos Taxis before booking. For the Larnaca to Ayia Napa route, Paralimni-based shared minivans run to the resort strip for under €15 per person and are worth investigating if you are arriving at a reasonable hour. The Larnaca to Larnaca city centre journey is so short — under 20 minutes — that a taxi for €20 is almost always the correct answer regardless of group size.",
      },
    ],
  },
  {
    slug: "cycling-guide",
    title: "Cycling in Cyprus — Infrastructure, Best Routes, and Honest Assessment",
    description:
      "A city-by-city assessment of cycling conditions in Cyprus, the best routes for road and mountain bikers, honest notes on the challenges, and when to actually go.",
    sections: [
      {
        heading: "The honest infrastructure assessment",
        body: "Cyprus is not a cycling country in the way the Netherlands or Denmark is, and pretending otherwise does nobody any favours. Most Cypriot cities have limited or no dedicated cycle infrastructure; cars dominate road culture, drivers are not accustomed to cyclists, and the aggressive summer heat makes cycling from June to September genuinely dangerous for most people. That said, pockets of excellent cycling exist, and the off-road mountain biking scene is genuinely world-class. The key is knowing where cycling works and where it does not. Limassol has the best urban cycling infrastructure of any Cypriot city — a 12km dedicated coastal promenade from the old port to the new marina and beyond, surfaced for cycling, with almost no car conflict. This is legitimately good cycling and the Sunday morning crowd of cyclists, families, and rollerbladers reflects its popularity. Paphos has a decent seafront path running about 4km along the tourist strip, pleasant but short. Nicosia's historic walled city has a designated 3km circuit inside the walls that is car-free on weekend mornings. Larnaca has a promenade road along the salt lake that is flat and moderately cycled.",
      },
      {
        heading: "Road cycling: Troodos and the mountain routes",
        body: "For road cyclists, Cyprus offers something no coastal ride can match: the Troodos mountain range. The roads are well-surfaced, traffic is sparse outside summer weekends, the gradients are serious (Mt Olympos sits at 1,952m), and the scenery from the upper plateaux is dramatic. The classic ride is the circuit from Platres through Troodos square and back, approximately 35km with 1,200m of climbing — challenging but manageable for a fit cyclist. The Machairas Forest area in the southern foothills offers more accessible routes: the ring road around Machairas monastery is roughly 25km with moderate climbing and very little traffic. Serious road cyclists cite early May and October as the sweet spot: the temperature at 1,000m elevation is 15–22°C, the roads are clear, and the cafes in Kakopetria and Platres are open. Bike lanes do not exist on mountain roads — you share the tarmac with cars — but driver behaviour is generally patient outside peak summer.",
      },
      {
        heading: "Mountain biking: Akamas and forest trails",
        body: "The Akamas peninsula in the northwest of Cyprus is the highlight for mountain bikers — rugged limestone terrain, unmarked goat tracks, views to Turkey, and almost no people mid-week. The main access point is Latchi village near Neo Chorio. The trails are largely unsignposted and require navigation by GPS or local knowledge; the trail network is informal rather than purpose-built, though efforts to map and formalise it have been underway since 2022. The Athalassa National Forest Park near Nicosia has beginner-friendly gravel trails suitable for a casual afternoon. The Cyprus Cycling Federation (cycling.org.cy) publishes a trail map that covers the main mountain bike areas; it is the most reliable starting point for route planning. Several Limassol-based operators (Bikefun Cyprus, Ride and Seek) run guided off-road tours and rent quality mountain bikes — worth considering if you are new to the island's terrain.",
      },
      {
        heading: "E-bikes and rental options",
        body: "E-bike availability in Cyprus has grown significantly since 2022 and has meaningfully changed the cycling proposition for people who want to commute or explore without arriving drenched in sweat. Rental e-bikes are available in all major tourist areas — the Limassol Marina area, Paphos harbour, and Ayia Napa all have rental shops. Rates run approximately €25–€40 per day for a decent e-bike, or €150–€250 per week. Several Limassol bike shops (Bicycle Centre Limassol, Velocipede) now stock and service mid-range e-bikes for purchase at €1,500–€3,000. For commuting use, the Limassol coastal promenade with an e-bike is genuinely pleasant year-round except July and August. Cyprus does not require registration or insurance for e-bikes below 250W (EU standard), and the same traffic rules that apply to regular bikes apply to e-bikes.",
      },
      {
        heading: "Best months, cycling clubs, and realistic expectations",
        body: "The comfortable cycling window in Cyprus is October through April. November to February is the coolest and moodiest period — some rain, temperatures 10–18°C at sea level, ideal for road cycling and mountain biking. March and April are the most popular with visiting cyclists: wildflowers, moderate temperatures, long daylight hours. October is also excellent. From May onwards, heat management becomes the primary challenge; early morning starts (before 9am) are the only practical strategy, and July and August should be avoided entirely for anything more than a leisurely coastal ride. Cycling clubs: the Limassol Cycling Club (Facebook: Limassol Cycling Club) organises group rides most Saturdays; the rides are mixed ability and beginner-friendly. The Nicosia Cycling Group does the walled city circuit on Sunday mornings. Both are accessible to newcomers and are a useful community entry point. The Cyprus Cycling Federation organises occasional road races open to amateurs.",
      },
    ],
  },
  {
    slug: "ferry-routes-guide",
    title: "Ferry Routes from Cyprus to Greece, Lebanon, and Egypt",
    description:
      "Passenger ferry and cargo-passenger services from Limassol port — Grimaldi Lines to Piraeus, seasonal cruise routes, vehicle transport costs, and practical tips for overnight crossings.",
    sections: [
      {
        heading: "The state of Cyprus ferry services",
        body: "Cyprus has no land borders — it is an island — and for most of its modern history passenger ferry services have been secondary to air travel for residents. The discontinuation of the Limassol-Haifa route (previously operated by Nissos Cyprus) and the suspension of some Mediterranean routes have reduced options over the years. As of 2026, the most reliable scheduled passenger service is the Grimaldi Lines service connecting Limassol with Piraeus (Athens's port), routing via Crete (Heraklion). This service operates roughly weekly during the high season (approximately April to October) with reduced frequency in winter. It is a cargo-passenger service — meaning the primary commercial purpose is freight, and the passenger capacity is secondary — which sets the tone: this is a comfortable but utilitarian voyage, not a luxury cruise experience. Seasonal cruise-style routes operated by Louis Cruises and other Mediterranean operators add additional options in summer.",
      },
      {
        heading: "Grimaldi Lines Limassol to Piraeus: what to expect",
        body: "The Grimaldi service from Limassol to Piraeus takes approximately 36–40 hours, with a stop in Heraklion adding several hours. Deck passage (reclining seat, access to public areas, no cabin) starts from approximately €80 per person each way. An interior cabin (no window) runs €120–€160 per person; a sea-view cabin is €200–€280. Cabins sleep 2–4 passengers. The ships are Italian-operated and well-maintained: there is a self-service restaurant, a bar, and adequate public seating. The crossing can be choppy between Crete and Piraeus during winter months — this is the Eastern Mediterranean, not the English Channel, but it is not always flat either. Booking is done through the Grimaldi Lines website (grimaldi-lines.com) or through local travel agents in Limassol; booking well in advance during summer is strongly recommended as the limited passenger capacity sells out. Check the current schedule directly with Grimaldi before planning, as sailing dates and routes change seasonally.",
      },
      {
        heading: "Vehicle transport on the ferry",
        body: "Transporting a vehicle from Cyprus to Greece (or vice versa) on the Grimaldi service is one of the most practical aspects of the route for relocators. Vehicle rates start from approximately €200–€350 for a standard car, depending on vehicle length and the specific sailing. A standard 4m car runs approximately €250. Motorhomes and campervans pay by length and run €400–€600. The vehicle is driven onto the ferry at Limassol and driven off at Heraklion or Piraeus; you cannot access your vehicle during the crossing for safety reasons — so pack what you need for the voyage in your hand luggage. This route is used by Cyprus residents transporting cars to Greece for sale or vice versa, by people moving households, and occasionally by tourists doing a longer road-trip itinerary (ferry Cyprus to Greece, drive north through Greece and the Balkans). Booking vehicle transport requires providing exact vehicle dimensions; do this accurately as weight and size restrictions apply.",
      },
      {
        heading: "Seasonal routes, Lebanon, and Egypt services",
        body: "Seasonal passenger services from Cyprus to Lebanon (Tripoli or Beirut) have existed historically but are subject to geopolitical disruption — the current availability depends on the political situation in Lebanon and should be verified directly with Limassol Port Authority (limassolport.com.cy) or local travel agents at the time of travel. Services to Egypt (Port Said or Alexandria) have operated intermittently; as of early 2026 there is no regular scheduled passenger service, though freight connections exist. The Latchi harbour in the Paphos district is relevant for boat hire and private yacht movement rather than commercial ferry services. It is a popular departure point for day trips to the Akamas peninsula sea caves and for private charters to Turkey (Kas or Antalya, roughly 90 nautical miles). Charter hire from Latchi for day trips runs €150–€350 depending on the boat size and duration.",
      },
      {
        heading: "Practical tips: booking, packing, and the overnight experience",
        body: "Four pieces of practical advice for the Limassol-Piraeus crossing. First, book a cabin rather than deck passage if you are doing the full 36-hour journey — the price difference (€50–€100) is small relative to the quality difference, and deck seats are uncomfortable for a full day and night. Second, bring your own food supplements — the on-board restaurant is functional but limited and expensive; a bag of snacks, fruit, and good coffee from the supermarket makes the journey significantly better. Third, boarding begins 3 hours before departure, and vehicles are loaded before passengers — if you are transporting a car, arrive at the port with considerable margin. Fourth, check the Grimaldi schedule against your preferred travel date rather than assuming weekly sailings — during the shoulder season (October-November and March-April) the frequency drops to every 10–14 days, and missing your sailing by a day can mean a long wait for the next one.",
      },
    ],
  },
  {
    slug: "road-safety-driving",
    title: "Driving in Cyprus — Road Safety, Culture, and What to Expect",
    description:
      "Everything you need to know before driving in Cyprus — left-hand traffic, speed limits, camera locations, accident procedures, and an honest assessment of local driving culture.",
    sections: [
      {
        heading: "Left-hand traffic: the British colonial legacy",
        body: "Cyprus drives on the left, which is either immediately intuitive (if you come from the UK, Ireland, Malta, Australia, Japan, or India) or requires deliberate adjustment (if you come from continental Europe, North America, Israel, or most of the rest of the world). The island retained left-hand traffic from the British colonial period, which ended in 1960, and unlike many former colonies that switched sides, Cyprus has kept it. The practical implications: roundabouts flow clockwise (counterclockwise from a driver's perspective), you give way to the right on roundabouts, and the biggest adjustment point for new arrivals is turns — particularly left turns, which cut across oncoming traffic. Most expat drivers report that left-hand driving becomes second nature within 2–3 weeks of daily use, but the adjustment period requires conscious attention. If you arrive with a right-hand-drive car (UK or Japanese import), the driver's position is natural; if you arrive with a left-hand-drive car, you are driving from the wrong side of the car for the traffic direction, which adds complexity at junctions.",
      },
      {
        heading: "Speed limits, cameras, and enforcement",
        body: "Legal speed limits in Cyprus: 50 km/h in urban areas, 80 km/h on main rural roads, 100 km/h on motorways (A1, A2, A3, A5, A6). The motorway network is limited — the main axis runs Paphos-Limassol-Larnaca-Nicosia on the A1/A2/A6 corridor. Speed enforcement has increased significantly since 2019: fixed speed cameras are installed on several motorway sections and on the approach to Nicosia, and mobile camera vans operate throughout the island. Fines are issued by post to the registered keeper. The Cyprus Police Traffic Department publishes fixed camera locations on their website, and Waze (widely used in Cyprus) shows community-reported mobile cameras. Note: Cyprus drivers routinely exceed the 80 km/h rural road limit by 20–30 km/h, which means driving at the legal limit on rural main roads can produce tailgating pressure. This is a cultural norm, not a reason to speed — but it helps to understand what you will encounter.",
      },
      {
        heading: "Legal requirements: licence, seatbelts, and alcohol",
        body: "EU driving licences are valid in Cyprus indefinitely — no exchange required. Non-EU licence holders may drive on their home-country licence for up to 6 months after establishing residency, after which they must exchange it for a Cyprus licence (an administrative process, not a new test, for most countries). An international driving permit (IDP) is required alongside a non-EU licence in some cases; check the Cyprus Transport Ministry website for your specific country. Seatbelt use is compulsory for all occupants in all seats; children under 150cm require an age-appropriate child seat. Using a handheld mobile phone while driving is illegal and carries a €300 fine. The drink-drive blood alcohol limit is 0.09% — marginally higher than the EU average of 0.05%, though enforcement via roadside checks has increased. Practically, two standard drinks over two hours approaches the limit for most adults; three drinks makes you clearly over it.",
      },
      {
        heading: "Accident procedure and the Hermes Insurance Bureau",
        body: "Cyprus law requires that the police are called to all road traffic accidents, regardless of severity. Do not move vehicles until the police officer has attended, photographed the scene, and given you clearance — even for minor scrapes this is the correct procedure, and insurance claims are significantly complicated without a police report. Call 112 (emergency) or 1460 (non-emergency police) from the scene. The Hermes Motor Insurance Bureau (hermescyprus.com) is the central body that coordinates insurance claims in Cyprus; every insurer operating in Cyprus is a member. If you are in an accident with an uninsured driver, or if there is a dispute about who is at fault, Hermes is the arbitration body. Exchange: driver name, licence number, insurance company and policy number, vehicle registration, and contact details — photograph everything with your phone before any vehicles move.",
      },
      {
        heading: "Road quality, hazards, and driving culture",
        body: "Motorway and main A-road quality in Cyprus is good — well-surfaced, well-marked, and recently improved. Secondary roads (B-routes) and rural village roads vary considerably: some are excellent, others have patches of broken tarmac, loose gravel at bends, and poor line-marking. Hairpin mountain roads in the Troodos are narrow and occasionally dusty after dry periods — reduce speed before blind bends and use the horn as a warning. Three specific hazards worth knowing: stray cats crossing roads at night are common throughout Cyprus, particularly in residential areas; sudden dust storms (calima winds from the Sahara, occurring a few times per year) can reduce visibility to 50m on motorways — hazard lights on and slow down significantly; and unmarked speed bumps (rampe) appear frequently in villages with no warning signs, particularly at 50–80 km/h on rural main roads. Parking: the main cities have paid parking in central areas (1–2 hours free, then metered); in Limassol's tourist zones, free parking is genuinely scarce and a nearby paid car park is the practical solution.",
      },
    ],
  },
  {
    slug: "language-learning-cyprus",
    title: "Learning Greek in Cyprus — Resources, Schools, and How Much You Actually Need",
    description:
      "A frank guide to Cypriot dialect vs Standard Modern Greek, which one to learn, how much you actually need day-to-day, and the best schools and apps for learning while living in Cyprus.",
    sections: [
      {
        heading: "Cypriot dialect vs Standard Modern Greek: the key distinction",
        body: "The most important thing to understand about language in Cyprus is that Cypriots speak a distinct dialect — Cypriot Greek (Kypriaka) — that differs significantly from Standard Modern Greek (SMG) as spoken in Athens and taught in almost all language resources. The differences are not trivial: Cypriot Greek retains medieval vocabulary (words from Byzantine Greek that have been replaced in SMG), has different pronunciation, different verb forms, and a significant number of loanwords from Arabic, Turkish, Italian, and English. A Greek from Athens visiting Cyprus for the first time will understand perhaps 70% of a conversation between Cypriots, and vice versa. For a learner, this creates an immediate question: which one to learn? The answer is Standard Modern Greek, for three reasons: all written text in Cyprus uses SMG, all official documents and formal communication use SMG, and all language learning resources (Duolingo, Pimsleur, textbooks) teach SMG. Cypriots will always understand and respond in SMG when they hear you attempting it.",
      },
      {
        heading: "How much Greek do you actually need",
        body: "The honest answer depends on where in Cyprus you live. Limassol and Paphos have large enough international English-speaking communities that daily life — supermarket, pharmacy, restaurants, most administrative offices, banks, real estate agents — can be conducted almost entirely in English without difficulty. English is the default second language for professionals under 50, and many businesses catering to expats have English-speaking staff by design. Larnaca is more mixed; English works reliably in tourist and commercial areas, less so in local neighbourhoods and with older tradespeople. Nicosia is where Greek becomes more genuinely useful — the inland capital has fewer expats proportionally, more Greek-only signage in non-tourist commercial areas, and a more traditional Cypriot demographic in many districts. For anyone dealing with neighbours, local contractors, government officials at district level, or who wants to feel genuinely at home rather than perpetually foreign, learning Greek to conversational level transforms the experience. Landlords and local service workers respond noticeably better to any attempt at Greek, however basic.",
      },
      {
        heading: "Best apps and self-study resources",
        body: "Duolingo's Greek course teaches Standard Modern Greek and is a reliable way to build basic vocabulary and grammar over 6–12 months of daily use; the limitation is that it teaches no Cypriot vocabulary and little of the informal register Cypriots use in speech. Pimsleur Greek (audio-based, 30-minute daily lessons) is better for spoken production than Duolingo — it prioritises listening and speaking over reading, which is more useful in daily life situations. The Assimil New Greek with Ease course is highly regarded by serious learners who want grammatical foundation alongside spoken practice. For Cypriot Greek specifically, resources are genuinely scarce — there is no widely used Cypriot dialect course; the best available are YouTube channels run by Cypriot educators (search 'Cypriot Greek phrases') and informal exposure. The practical shortcut: learn SMG formally, then pick up Cypriot expressions through immersion. Cypriots will naturally accommodate your SMG while you build familiarity with the local forms.",
      },
      {
        heading: "Language schools in Cyprus",
        body: "Several accredited institutions offer Greek as a foreign language courses in Cyprus. The Cyprus Institute of Language and Computing (CyILE), affiliated with the University of Cyprus, runs intensive and regular-pace Greek language courses at various levels from beginner to advanced; courses are offered in Nicosia, Limassol, and Larnaca, with term durations of 8–16 weeks and approximate costs of €300–€600 per level. Frederick University in Nicosia and Limassol offers short courses in Greek as part of its continuing education programme; these are worth checking for summer intensive formats. The ΙΝΕΚ (Institute of Adult Education) runs subsidised evening Greek courses at community centres in major cities — these are informal and cheap (€30–€60 for a term), oriented at integrating foreign residents, and a social environment as much as a language class. Private tuition from qualified Greek teachers runs €25–€45 per hour in Limassol and Nicosia; online platforms like Italki and Preply both have listings for Cyprus-based Greek tutors who can provide Cypriot-specific context.",
      },
      {
        heading: "Survival phrases, language exchange, and realistic progression",
        body: "For immediate daily life, a core set of 50–100 phrases covers most interactions: greetings (Γεια σας, Γεια σου), numbers, asking for the bill (Τον λογαριασμό, παρακαλώ), ordering coffee (Έναν καφέ, παρακαλώ), thanking people (Ευχαριστώ), and basic navigational questions. Google Translate's camera mode handles most Greek signage passably. Language exchange (language tandem) groups exist in Limassol and Nicosia — the Limassol International Community Facebook group and the Expats in Cyprus group regularly post about informal Greek practice meetups. Realistic progression: with Duolingo daily plus a weekly class, most adults reach functional tourist-level Greek (ordering food, understanding simple instructions, basic shopping) within 4–6 months. Genuine conversational fluency in the contexts that matter for daily life in Cyprus — joking with your landlord, following a local conversation, understanding a government office — takes 1.5–2 years of consistent exposure. This is not faster or slower than learning any other European language; it is Greek, and the alphabet and grammar are genuinely different from western European languages.",
      },
    ],
  },
  {
    slug: "cultural-etiquette-guide",
    title: "Cypriot Culture and Social Etiquette — A Guide for Newcomers",
    description:
      "Filoxenia, name days, Orthodox holidays, the kafeneion as a social institution, tipping norms, and the practical cultural knowledge that helps newcomers build real relationships in Cyprus.",
    sections: [
      {
        heading: "Filoxenia: take the coffee, eat the food",
        body: "The most important cultural concept to internalise is filoxenia — literally 'love of the stranger', the ancient Greek tradition of hospitality towards guests and newcomers. In Cyprus this is not an abstract value but a daily social practice. When you visit someone's home, you will be offered coffee and food; declining repeatedly is read as rudeness or discomfort, not politeness. Accept the first offering. When a Cypriot neighbour or shopkeeper brings you something spontaneously — a piece of fruit, a small sweet, a coffee — this is an act of social inclusion. The correct response is genuine appreciation, a small reciprocal gesture when appropriate, and not treating it as an awkward transaction. Filoxenia extends to hospitality in the widest sense: being shown around, being given directions, being guided through bureaucracy by someone who volunteers their time. These gestures are genuine, not transactional, and the relationship is what matters. Newcomers who embrace this reciprocal hospitality culture tend to integrate socially much faster than those who keep formal distance.",
      },
      {
        heading: "Family, name days, and the Orthodox calendar",
        body: "Family is the organising structure of Cypriot society in a way that may feel intense to newcomers from more individualistic cultures. Sunday lunch with extended family is a widely observed institution; family obligations — attending christenings, weddings, memorial services, graduation dinners — take clear priority over professional or social commitments, and this is universally understood. Name days (onomastica) are celebrated more prominently than birthdays in traditional Cypriot families — if someone's name is Giorgios, his name day (St George's Day, 23 April) is when you call, send a message, or bring a small gift. Not knowing this results in no social harm, but knowing it and acknowledging it is a meaningful gesture of cultural respect. The Orthodox calendar drives the annual rhythm: Christmas (December 25 — Western date, though Orthodox Easter is often on a different date to Western Easter) and Easter are the major family occasions; Carnival and Clean Monday mark the start of Lent; Assumption (15 August) is a significant summer holiday with religious processions in many villages. Most businesses in Cyprus close on major Orthodox feast days, including Kataklysmos (Pentecost Monday, a uniquely Cypriot water festival in late May or June).",
      },
      {
        heading: "Relationship before transaction",
        body: "In northern European and North American professional cultures, transactions tend to precede relationships — you engage a service provider, complete the transaction, and the relationship may or may not develop from there. In Cyprus, the sequence is frequently reversed: a relationship (however brief) is expected before a transaction can properly proceed. This means that showing up cold to a meeting, completing business in 15 minutes, and leaving is read as odd or dismissive. The expectation is that you make small talk — ask about the family, comment on the weather, discuss something in the news — before getting to the business point. This is not inefficiency; it is a different social grammar. The most common place this misaligns for newcomers is in dealing with tradespeople, landlords, and local government offices: being purely transactional produces slower and colder service; showing genuine interest in the person first produces warmth and often preferential treatment. Allow more time for interactions than you would in northern Europe.",
      },
      {
        heading: "Tipping norms, direct communication, and religious sites",
        body: "Tipping in restaurants: 10% is standard if you are happy with the service, or rounding up to the nearest €5–€10. Service charges are sometimes added automatically at tourist-facing restaurants — check the bill. For taxis, round up to the nearest euro or nearest €5 for longer journeys; there is no expectation of 15–20% taxi tips as in the US. Coffee shop tipping is rounding up or leaving small coins on the table — not a significant percentage. Hairdressers and beauty services: €2–€5 is customary. Cypriot communication style is direct by Mediterranean standards — people say what they think with less circumlocution than in British culture, but with more warmth than in German culture. Disagreements are expressed openly and without lasting social damage. At religious sites — Orthodox churches, monasteries, religious processions — dress modestly (shoulders and knees covered), maintain quiet behaviour inside church buildings, and if you wish to light a candle (a common respectful gesture by both Orthodox and non-Orthodox visitors), the appropriate donation is €0.50–€1. Photography inside churches is not universally permitted; check for a sign or ask before photographing icons or services.",
      },
      {
        heading: "The kafeneion as a social institution",
        body: "The kafeneion (καφενείον) — the traditional Cypriot coffee house — is more than a place to drink coffee. It is the social engine of village and neighbourhood life: the place where older men gather to play backgammon (tavli), discuss local politics, read the newspaper, and maintain the social fabric. In towns, kafeneions have been partially displaced by modern cafes, but in villages and working-class neighbourhoods they remain alive and important. As a newcomer in a village setting, visiting the local kafeneion, drinking a Cyprus coffee (a thick, sweet espresso-style coffee made in a briki, ordered glykos/sweet, metrios/medium, or sketos/no sugar), and being willing to sit and talk is a social act that signals openness and genuine interest in the community. You do not need Greek to do this; the willingness to be present and unhurried communicates more than vocabulary. A Cyprus coffee costs €1–€1.50. Never rush one. The kafeneion operates on village time, and that is a feature, not a bug.",
      },
    ],
  },
];
