/**
 * Guides batch G3 — business and family guides.
 * Consumed alongside GUIDES and GUIDES_G2 by lib/guides.ts (or the guide index).
 */

import type { GuideInfo } from "./guides";

export const GUIDES_G3: ReadonlyArray<GuideInfo> = [
  {
    slug: "hiring-in-cyprus",
    title: "Hiring Employees in Cyprus — Employment Law, Costs, and Process",
    description:
      "What Cyprus employment law requires when you hire your first employee — contracts, minimum wage, social insurance, probation, and how to calculate redundancy. Prices and rules change — verify with official Cyprus sources before acting.",
    sections: [
      {
        heading: "Employment contracts and minimum terms",
        body: "Cyprus employment law requires a written contract of employment for every employee, issued within one month of the start date. The contract must state at minimum: job title and description, place of work, start date and duration (if fixed-term), salary and payment frequency, working hours (the standard is 40 hours per week, 8 hours per day), probationary period (maximum 6 months), and notice period. The governing legislation is the Termination of Employment Law of 1967 (as amended) and the Employment Information Law of 2009. Contracts can be in English; there is no requirement for a Greek translation for the employer's records. Fixed-term contracts are permitted but repeated renewals that together exceed 4 years allow the employee to claim a permanent contract by statute.",
      },
      {
        heading: "Minimum wage and mandatory benefits",
        body: "Cyprus introduced a statutory minimum wage in January 2023, set initially at €940 per month and increased to €1,000 per month from January 2024 for all employees who have completed six months of continuous employment with the same employer; new starters receive 80% of the minimum for the first six months. The minimum wage applies to nearly all employees regardless of sector, with exemptions for domestic workers and trainees. Mandatory benefits include 20 working days of paid annual leave per year (or 4 weeks, whichever is greater), paid sick leave after completion of probation (partially funded by the Social Insurance Fund), and public holiday pay. A 13th salary — typically paid in December — is not mandated by statute but is standard practice across most sectors; it should be specified or excluded explicitly in the contract to avoid disputes.",
      },
      {
        heading: "Employer social insurance and other payroll costs",
        body: "The headline payroll cost beyond salary is the employer's contribution to the Social Insurance Fund: 8.3% of gross salary as of 2024, with a ceiling applied to the insurable earnings. Employers also contribute to the General Healthcare System (GeSY) at 2.90% of gross salary, to the Redundancy Fund at 1.2%, to the Human Resource Development Authority (HRDA) at 0.5%, and to the Social Cohesion Fund at 2%. In total, the employer-side social charges run to approximately 14.9% of gross salary for most full-time employees. For a €2,000/month employee, the total employer cost is roughly €2,298 per month before any benefits. Employees pay their own social insurance contribution (8.3%) and GeSY contribution (2.65%), which are deducted from gross salary before net pay is calculated.",
      },
      {
        heading: "Probation, notice periods, and termination",
        body: "Probationary periods are legally capped at 6 months. During probation, either party can terminate without notice or compensation unless the contract specifies otherwise. After probation, statutory minimum notice periods scale with tenure: zero to two years requires one week's notice; two to four years, two weeks; four to seven years, four weeks; and the scale continues to a maximum of eight weeks for twelve-plus years. Notice must be given in writing. Employees terminated after 26 weeks (6 months) of continuous employment qualify for statutory redundancy pay, calculated as two weeks' pay per year of service for the first 4 years and three weeks' pay per year thereafter, subject to the insurable earnings ceiling. Immediate dismissal for gross misconduct is permitted but must be documented carefully — Cyprus courts tend to favour employees in ambiguous dismissal disputes.",
      },
      {
        heading: "Practical steps to make your first hire",
        body: "Before the employee starts, the employer must register the employment with the Social Insurance Services (form TE.S.P. 5) and ensure the employee has a Tax Identification Number (TIC) and Social Insurance number. The HRDA registration (for the Human Resource Development levy) can be done online. Payroll is typically processed monthly; payslips are required to show gross pay, deductions, and employer contributions. For non-EU employees, work permits are required before they begin work — these are processed by the Civil Registry and Migration Department, and obtaining one for a skilled worker typically takes 3–6 weeks for approved company sponsors. Many small Cyprus employers use a local payroll bureau (€50–€120 per employee per month) rather than managing Social Insurance filings themselves, particularly in the first year.",
      },
    ],
  },
  {
    slug: "startup-visa-ict",
    title: "Cyprus Innovative Company Residence Permit — The Tech Founder Visa",
    description:
      "How non-EU tech founders can get a 2-year Cyprus residence permit through the Innovative Company scheme — income requirements, the business plan evaluation, and what happens if you are rejected. Prices and rules change — verify with official Cyprus sources before acting.",
    sections: [
      {
        heading: "Who the permit is designed for",
        body: "The Cyprus Innovative Company Residence Permit — colloquially called the startup visa or ICT founder visa — is designed for non-EU nationals who want to live in Cyprus while operating an innovative technology company. The permit was introduced as part of Cyprus's broader strategy to attract knowledge-economy businesses, and it is evaluated and issued by the Research Promotion Foundation (RPF, or RESTART in Greek). Eligible applicants must be founders or co-founders of a Cyprus-registered company operating in a technology or innovation-intensive field: software, deep tech, biotech, cleantech, fintech, and similar sectors. The company must be legally incorporated in Cyprus and genuinely operational — shell or holding companies do not qualify. Applications are submitted to the Migration Department in parallel with the RPF technical evaluation.",
      },
      {
        heading: "Income and substance requirements",
        body: "The applicant must demonstrate a personal income of at least €4,000 per month, documented by salary from the Cyprus company, dividends, or a combination. This income threshold is intended to confirm genuine economic activity rather than passive presence. The company must have a Cyprus-based office (a registered address is not sufficient — a real working space or coworking membership is required as evidence), and at least the founding team must be physically present in Cyprus for a meaningful period each year. The RPF evaluates whether the company's technology has genuine innovation content, whether the business plan is credible, and whether the local presence is substantive. Unlike some EU startup visa programmes, Cyprus does not require a minimum investment amount or a minimum number of local employees at the application stage, though the evaluation criteria reward demonstrable traction.",
      },
      {
        heading: "Business plan and RPF evaluation",
        body: "The business plan submitted for the RPF evaluation is a formal document typically 20–40 pages covering: the problem and solution, the technology and its innovative elements, the team's qualifications and track record, the market opportunity with supporting data, the business model and monetisation path, a three-year financial projection, and a description of the Cyprus operations. The RPF panel includes technical reviewers who assess whether the innovation claim is credible — vague descriptions of 'disruptive technology' without specifics are routinely challenged. Strong applications include IP ownership (or a clear path to it), evidence of customer validation (letters of intent, contracts, user numbers), and a founder with a track record in the relevant technical domain. The RPF review typically takes 6–10 weeks. A positive RPF assessment does not guarantee approval of the migration permit, but a negative one ends the process.",
      },
      {
        heading: "Permit duration, renewal, and family rights",
        body: "The initial permit is issued for two years. Renewal for a further two years is possible and requires demonstrating continued operation of the company, continued minimum income, and physical presence in Cyprus (the two-year renewal evaluation looks at whether the business has progressed beyond the plan submitted at the initial application). There is a third possible renewal bringing total permit duration to six years; after five years of continuous legal residence, the holder can apply for long-term residence. Family extension is available: the permit covers a spouse and dependent children under 18. The spouse is permitted to work in Cyprus under the family permit without requiring a separate work permit, which is a meaningful advantage over several other EU member state startup visa programmes. After the third renewal, or after qualifying years of residence, naturalisation to Cyprus citizenship may become available but involves separate criteria.",
      },
      {
        heading: "If your application is rejected and alternative routes",
        body: "Rejection at the RPF stage is relatively common for first-time applicants who submit business plans without professional preparation. If rejected, you can reapply with a stronger submission — there is no mandatory waiting period — or you can challenge the assessment with a formal rebuttal. If the RPF evaluation is positive but the Migration Department rejects the permit on administrative grounds, the appeal process goes through the Administrative Court. For founders who are rejected or who prefer a more straightforward route: the Digital Nomad Visa (available to non-EU remote workers and freelancers earning €3,500+/month) is a valid alternative if your work can be structured as services to non-Cyprus clients. Incorporating in Cyprus but holding the DNV is a legitimate configuration used by many founders in the early stage. The Permanent Residency by Investment route (minimum €300,000 property purchase) is a third option that bypasses the business-innovation evaluation entirely, though it does not grant the right to work.",
      },
    ],
  },
  {
    slug: "ip-registration-cyprus",
    title: "Registering IP in Cyprus — Trademarks, Patents, and Software",
    description:
      "How to protect a brand, patent an invention, and understand software copyright in Cyprus — covering the Cyprus Trademark Registry, EUIPO, the European Patent Office, and the .cy domain registry. Prices and rules change — verify with official Cyprus sources before acting.",
    sections: [
      {
        heading: "Cyprus Trademark Registry — national registration",
        body: "Cyprus is a signatory to the Madrid Protocol, and trademarks registered through the Cyprus Trademark Registry (a department of the Registrar of Companies and Intellectual Property) provide protection within the Republic of Cyprus only. The application fee is approximately €250 for one class under the Nice Classification; each additional class adds ~€100. Applications are examined on absolute grounds (distinctiveness, descriptiveness) and published for opposition; the full process from filing to registration typically takes 6–9 months if unopposed. Applications can be filed directly online via the Registrar's portal. A Cyprus trademark is valid for 10 years and renewable indefinitely. For most businesses operating primarily in Cyprus, a national registration is sufficient for enforcement purposes. If your business plans extend to the broader EU market, a Cyprus national mark is rarely the right primary strategy — the EUIPO route is more efficient.",
      },
      {
        heading: "EUIPO EU trademark — the practical choice for most businesses",
        body: "An EU Trade Mark (EUTM) registered through the European Union Intellectual Property Office (EUIPO, based in Alicante, Spain) provides protection across all 27 EU member states including Cyprus for a single application. The official EUIPO application fee is €850 for one class (€50 for the second class, €150 for each further class). The examination and publication process typically takes 7 months from filing to registration if there are no oppositions. An EUTM registered before a business relocates to Cyprus automatically extends to Cyprus — there is no separate Cyprus filing needed. The EUIPO also offers an accelerated Fast Track procedure which can reduce the timeline to 4–5 months for applications that pass the initial checks cleanly. For brands targeting the EU market, an EUTM is almost always more cost-effective than filing in multiple EU member states individually. EUIPO's online filing system is straightforward and does not require a local agent, though using a trademark attorney reduces the risk of objections.",
      },
      {
        heading: "Patents — European Patent Office and the PCT route",
        body: "Cyprus is a contracting state of the European Patent Convention (EPC), meaning a European Patent granted by the European Patent Office (EPO) must be validated in Cyprus within 3 months of grant to have effect here. Validation in Cyprus requires payment of a validation fee (approximately €200–€300) and, for some categories, translation. Cyprus does not have an independent national patent office with examination capacity — the effective route for any patent with Cyprus coverage is through the EPO or, for global protection, the Patent Cooperation Treaty (PCT) with Cyprus designated. EPO application costs are substantial: official filing fees start around €4,000 and total costs including search, examination, and prosecution typically reach €8,000–€15,000 before grant, plus validation fees in each country. Patent attorneys are essentially mandatory for prosecution. Software patents per se are not granted by the EPO (software 'as such' is excluded), but software implementing a technical process or having technical effect is patentable — the boundary is complex and requires careful claim drafting.",
      },
      {
        heading: "Software copyright — automatic, no registration required",
        body: "Under Cyprus copyright law (Intellectual Property (Literary and Artistic Works) Law, as amended, implementing the EU Software Directive 2009/24/EC), software is protected as a literary work from the moment of creation. There is no registration requirement, no fee, and no formal process. The author (or the employer, for works created in the course of employment) holds copyright automatically. The protection term is 70 years from the death of the author for personal works. This means a startup building software in Cyprus is protected from day one with zero administrative overhead — the critical practical step is maintaining evidence of creation: timestamped commits in version control, development history, and any contracts with third-party developers assigning IP clearly to the company. A common mistake for funded startups is unclear IP assignment from co-founders or early contractors — fix this with explicit IP assignment clauses in all founder and contractor agreements before fundraising.",
      },
      {
        heading: "Domain names and the .cy registry",
        body: "The .cy country code top-level domain is administered by the University of Cyprus acting as the IANA-delegated registry. Registrations are available through accredited registrars including several Cyprus-based ISPs and hosting providers. The .cy registry operates under a reserved namespace policy: .com.cy is the standard commercial second-level domain; .org.cy and .net.cy are also available. A .com.cy registration requires proof of legitimate business interest in Cyprus (a company registration number satisfies this) and costs approximately €25–€35 per year through most registrars. The registration process takes 1–3 business days. Non-residents can register .com.cy domains but must provide a Cyprus company or local contact address. For businesses incorporating in Cyprus, registering the corresponding .com.cy domain alongside a .com or other international TLD is standard practice.",
      },
    ],
  },
  {
    slug: "trade-licenses-cyprus",
    title: "Trade License Requirements in Cyprus — Which Businesses Need One",
    description:
      "Which business activities require a license before trading in Cyprus, which authority issues each one, and what the typical costs and timelines look like. Prices and rules change — verify with official Cyprus sources before acting.",
    sections: [
      {
        heading: "The Municipal Business License — the baseline requirement",
        body: "Most physical business premises in Cyprus require a Municipal Approval of Business Activity (commonly called a dimos license or epaggelmatiki adeia) issued by the local Municipal Authority (dimos) in whose jurisdiction the premises sit. This applies to offices, retail units, warehouses, restaurants, and most other fixed premises. The application is made to the dimos with supporting documents including the lease or ownership certificate for the premises, a floor plan, proof of company registration, and evidence that the premises comply with planning and building regulations. The dimos fee varies by municipality and business category but typically runs €80–€300 per year for a standard office, and higher for food service or premises open to the public. Processing time is generally 2–6 weeks. Some municipalities require an inspection of the premises before approval. Businesses operating from home addresses still technically need to check whether their municipality permits commercial use of a residential address.",
      },
      {
        heading: "Food and hospitality businesses — the strictest regime",
        body: "Food-related businesses face the most complex licensing stack in Cyprus. A restaurant, café, food production facility, or catering company needs: a Municipal Business License from the dimos, a Veterinary Services approval (for any premises handling animal-derived products, including standard restaurant kitchens), a Food Establishment Permit from the District Administration Office under the Food Safety legislation, and compliance inspections from the Cyprus Organisation for Standardisation (CYS). The Veterinary Services inspection covers hygiene standards, food storage equipment, pest control, and staff health certificates. Inspections are typically carried out within 4–8 weeks of application. Foreign investors opening a restaurant in Cyprus are sometimes surprised that a standard small restaurant can face 4–5 separate approvals from 4–5 different bodies — budget 3–4 months from company registration to trading.",
      },
      {
        heading: "Financial services — Central Bank and CySEC",
        body: "Financial services businesses are among the most regulated in Cyprus. The Central Bank of Cyprus licenses and supervises: banks and credit institutions, payment institutions, electronic money institutions, and credit servicers. The Cyprus Securities and Exchange Commission (CySEC) licenses: investment firms (CIF), fund managers (AIFM, UCITS), crypto-asset service providers (CASP under the EU's MiCA framework), and insurance intermediaries. CySEC has become one of the most commonly chosen EU financial regulators for fintech companies because of its relatively transparent process and active dialogue with applicants. A CIF license (for investment firms) requires minimum capital of €750,000, qualified directors with verified experience, appropriate AML systems, and a formal business plan; the process takes 6–12 months and requires ongoing compliance infrastructure. CySEC publishes a full licensing checklist on its website (cysec.gov.cy), which is essential reading before beginning an application.",
      },
      {
        heading: "Construction and real estate — Ministry of Interior and dimos",
        body: "Construction companies operating in Cyprus must register with the Council for Registration of Contractors (ETEK), which maintains separate registers for different contractor categories (civil engineering, building, M&E, etc.). Registration requires documented relevant qualifications and experience for the responsible technical person. Real estate agencies must obtain a license from the Council of Real Estate Agents (Cyprus Real Estate Agents Registration Council), which requires passing an examination, proof of professional indemnity insurance, and registration with the Registry. The license is renewable every three years. Real estate developers selling off-plan properties must register the sale contract with the Land Registry — failure to do so is a recurring source of buyer protection issues and is heavily discouraged. For construction, planning permission is issued by the relevant District Administration for land outside municipal boundaries, or by the dimos for land within municipal areas, and is separate from the building permit issued once full plans are approved.",
      },
      {
        heading: "Energy, professional services, and other regulated sectors",
        body: "Energy companies — electricity generators, renewable energy producers, energy suppliers — require a license from the Cyprus Energy Regulatory Authority (CERA, or RAEK in Greek). Solar and wind projects below certain capacity thresholds may qualify for simplified approval rather than a full license; CERA's website publishes the current thresholds. Pharmacies require a personal pharmacist license (Ministry of Health) plus a premises license. Legal practices require registration with the Cyprus Bar Association; auditing firms with the Institute of Certified Public Accountants of Cyprus (ICPAC). Healthcare providers (private clinics, physiotherapy practices) require Ministry of Health registration. For technology companies without a physical product — software firms, consulting businesses, digital agencies — the typical license requirement reduces to the Municipal Business License from the dimos, a registration with the Social Insurance Office, and standard company registration, making Cyprus one of the operationally simpler EU jurisdictions for pure-service businesses.",
      },
    ],
  },
  {
    slug: "international-vs-public-school",
    title: "International vs Public Schools in Cyprus — An Honest Comparison",
    description:
      "A frank look at what public and international schools in Cyprus actually deliver — language, curriculum, costs, university outcomes, and who each track works for.",
    sections: [
      {
        heading: "Public school basics — Greek-medium with English from age 6",
        body: "Cyprus's public school system is Greek-medium from day one. All core subjects — maths, science, history, geography — are taught in Greek throughout primary and secondary school. English is taught as a compulsory foreign language starting at age 6 (Year 1) with increasing hours through primary school, and there are subject teachers for English at secondary. A second foreign language (typically French or German) is added from Year 4. Public school is entirely free, including books, and the calendar runs September to June. For expat children who arrive with zero Greek, immersion is the explicit policy — there is no formal English-medium stream in the public system, though some teachers will support settling-in pupils in English. Children who arrive before age 8 typically reach functional Greek within one school year; children arriving at secondary school age face a much steeper integration curve. The academic standard in public school ranges widely by school — urban schools in Limassol and Nicosia are generally stronger than rural ones.",
      },
      {
        heading: "International school curricula and fees",
        body: "International schools in Cyprus predominantly follow three curricula: the British IGCSE and A-Level pathway (the most widely available), the International Baccalaureate (IB) Diploma Programme, and — at a smaller number of schools — the American curriculum with US High School Diploma. Most international schools are privately owned and the quality of teaching, facilities, and pastoral care varies considerably even within the same curriculum type. Annual fees range from approximately €4,000 to €8,000 per year at the smaller or newer schools in Paphos and Larnaca, to €10,000–€16,000 per year at the established schools in Limassol (Grammar School Limassol, Heritage School) and Nicosia (American Academy, The English School). The English School in Nicosia is a semi-public institution that charges modest fees (around €3,000–€4,000/year) with a highly competitive entry examination — it is often the first choice for academically strong children of EU residents.",
      },
      {
        heading: "Social integration and language outcomes",
        body: "The choice between public and international school is partly a bet on what your child's life in Cyprus will look like in five years. International school children typically make English-speaking expat friends easily, have strong relationships with other internationally mobile families, and integrate into the expat social bubble. Greek-language outcomes from international schools are generally weak — most have Greek as a second language, but a child spending 8 hours a day in an English-medium environment rarely achieves functional Greek. Public school children develop Cypriot Greek fluency and build social networks that extend into the local community — which matters considerably if your family is planning to stay long-term. The pattern among long-term Cyprus residents is: families planning to stay 10+ years and arriving with children under 8 often choose public school; families on a 3–5 year horizon, families who value curriculum continuity with the UK or US, and families arriving with older children almost always choose international.",
      },
      {
        heading: "University recognition and academic pathways",
        body: "British A-Level and IB Diplomas from Cyprus international schools are recognised directly by UK, US, and European universities without any additional equivalency steps. The British curriculum pathway in particular has a strong track record for UK Russell Group admissions from Cyprus schools. Public school students in Cyprus sit the Pancyprian Examinations (Pankyprior Examinations) at the end of secondary school, which qualify them for admission to Cypriot public universities and, via NARIC equivalency, for applications to EU universities. UK and US university applications from public school are possible but require individual equivalency assessments and are less frequently pursued. IB schools in Cyprus — including Pascal English School and a small number of others — produce graduates who have genuinely unrestricted university access globally, which is why IB has grown in popularity among internationally mobile families even at its higher price point.",
      },
      {
        heading: "Who chooses public and who needs international",
        body: "The families who successfully choose public school tend to share a profile: they are planning a permanent or very long-term stay, they have children under 8, they have a parent who speaks some Greek (helpful for parent-teacher communication), and they view Cypriot social integration as a priority. Some families from EU countries with strong language learning cultures are also more comfortable committing to a Greek-medium environment than UK or US families. The families who genuinely need international school include: English-only families who cannot support a Greek-learning child at home, families on time-limited assignments (3–5 years), children with A-Level or IB as the target qualification for university applications, and children with SEN needs who require specific support (public school SEN provision is improving but inconsistent — see our SEN guide for detail). Cost is real: at €10,000–€16,000 per child per year, two children at an established international school add €1,500–€2,700 per month to a family budget before any other costs.",
      },
    ],
  },
  {
    slug: "universities-in-cyprus",
    title: "Universities in Cyprus — Guide for Students and Relocating Families",
    description:
      "The public and private universities in Cyprus, fees for EU and non-EU students, English-medium programmes, degree recognition, and why some expat families factor university proximity into their relocation decision.",
    sections: [
      {
        heading: "The university landscape — public and private",
        body: "Cyprus has a relatively large higher education sector for a country of its size, split between public universities (state-funded, with regulated fees) and private universities (independently funded, with market-rate fees). The public universities are: University of Cyprus (UCY, Nicosia — the flagship research university), Cyprus University of Technology (CUT, Limassol — strong in engineering and applied sciences), and the Open University of Cyprus (distance learning). The main private universities with full university status are: University of Nicosia (UNIC — largest, with strong medical and law programmes), Frederick University (Nicosia and Limassol), European University Cyprus (Nicosia), Neapolis University Paphos, and UCLan Cyprus (Pyla, Larnaca — a campus of the University of Central Lancashire). Each university is accredited by the Cyprus Agency of Quality Assurance and Accreditation in Higher Education (DIPAE), and degrees from all accredited institutions are recognised within the EU.",
      },
      {
        heading: "Fees for EU and non-EU students",
        body: "Public university fees for EU students are subsidised by the Cyprus government and are very low by European standards: the University of Cyprus charges approximately €3,400 per year for EU students in most programmes. For non-EU international students, public university fees range from €6,800 to €9,500 per year depending on the programme. Private universities charge market rates: €6,000 to €9,500 per year for undergraduate programmes for EU students, and €8,000 to €12,000 for non-EU students. The exception is the University of Nicosia's medical programme, which is significantly more expensive (and in high demand from non-EU students) due to its EU accreditation and clinical placement access. Living costs as a student in Cyprus are lower than in UK, German, or Dutch university cities — a student sharing an apartment in Nicosia or Larnaca can live on €700–€1,000 per month including rent, food, and transport.",
      },
      {
        heading: "English-medium programmes",
        body: "This is a significant selling point of the Cyprus university system for internationally mobile families. Almost all private universities offer the majority of their programmes entirely in English — UCLan Cyprus, University of Nicosia, Frederick University, Neapolis, and European University Cyprus all teach primarily in English. The public universities (UCY and CUT) teach most undergraduate programmes in Greek, but both offer a growing range of English-medium postgraduate and doctoral programmes, and UCY has English-medium undergraduate programmes in specific departments. For expat families whose children attended English-medium international schools in Cyprus and want to continue at university in Cyprus, the private university route in English is seamless. For students targeting the University of Cyprus (which is the academically strongest public institution), Greek language proficiency is required for most undergraduate admissions.",
      },
      {
        heading: "EU degree recognition and quality",
        body: "Degrees from all DIPAE-accredited Cyprus universities are EU degrees, recognised across the EU for employment and further study. For professional qualifications — medicine, law, engineering, architecture — the relevant professional body in the receiving country determines recognition, but Cyprus degrees in these fields are generally on par with other EU member state degrees. The University of Nicosia Medical School gained LCME (US) accreditation in addition to EU recognition, which makes its medical degree valid for US residency applications — this has driven significant American student enrolment. UCLan Cyprus degrees are awarded by the University of Central Lancashire and carry the same recognition as degrees from UCLan's main Preston campus. For families considering Cyprus partly for their children's university access, the combination of English-medium programmes, EU degree status, and lower living costs makes Cyprus meaningfully competitive with UK, Irish, and Dutch universities as a destination.",
      },
      {
        heading: "Why families plan around university proximity",
        body: "A recurring pattern among expat families in Cyprus is that secondary school choices are made with an eye on domestic university options. Families who enrol children in the IB programme at a Cyprus school can feed directly into the University of Nicosia, Frederick, or UCLan Cyprus, keeping the family in Cyprus without the gap year logistics and tuition expense of UK university. This matters more than it might seem: a child in secondary school in Limassol from age 14 and then continuing at University of Cyprus or University of Nicosia in Nicosia keeps the family unit together and avoids the €30,000–£45,000/year UK university cost. Some families explicitly structure their relocation horizon around this: arrive when children are 12–14, settle into international school, consider a Cyprus university for undergraduate, and then the child can choose Europe, UK, or US for postgraduate. It is a financially rational strategy that several hundred expat families in Limassol and Nicosia appear to be following deliberately.",
      },
    ],
  },
  {
    slug: "child-registration-guide",
    title: "Registering Your Child in Cyprus — School, ARC, and Healthcare",
    description:
      "The documents and steps to register a child born in Cyprus or arriving as part of a relocating family — birth registration, ARC for minors, school enrollment paperwork, and the GeSY children's healthcare card. Prices and rules change — verify with official Cyprus sources before acting.",
    sections: [
      {
        heading: "Birth registration for children born in Cyprus",
        body: "If your child is born in Cyprus, the birth must be registered at the Civil Registry and Migration Department (CRMD) within 3 months of the birth date. The hospital will provide a birth notification form; you take this to the CRMD or a district registrar's office with both parents' passports and marriage certificate (if applicable). For non-EU parents, the birth registration establishes the child's legal presence in Cyprus and is a prerequisite for the subsequent ARC application. Note that birth in Cyprus does not automatically confer Cyprus citizenship or EU citizenship — citizenship follows the parents' nationality. If you are an EU citizen, the child born in Cyprus inherits EU citizenship through you. The birth certificate issued is an official Cyprus civil document and is accepted as proof of identity for the child in all subsequent administrative steps.",
      },
      {
        heading: "ARC for minor children of non-EU parents",
        body: "Non-EU parents with a Cyprus residence permit (ARC) must apply for an ARC for each dependent minor child. The application process is essentially identical to the adult ARC: the parent applies on the child's behalf at the CRMD district office, submitting the child's passport (or travel document), birth certificate, two recent passport photos, proof of parent's ARC, and proof of address. The child's ARC ties to the parent's permit category and has the same expiry date. For newborns: a temporary travel document is issued by the child's country of nationality before the ARC can be processed (since a passport takes weeks to arrive) — the CRMD will accept the birth certificate and an in-progress passport application as interim evidence. Renew the child's ARC at the same time as the parent's permit to keep all documents in sync.",
      },
      {
        heading: "School enrollment documents",
        body: "Enrolling a child in a Cyprus public school requires: a completed registration form from the District Education Office, the child's birth certificate (apostilled if issued by a foreign country), the child's previous school records (last two school reports, translated into Greek if from a non-Greek-medium school), an up-to-date immunisation record (following the Cyprus national immunisation schedule — a local paediatrician can issue a certificate confirming equivalent vaccinations), and the family's proof of address in Cyprus. Private and international schools have their own admissions processes but typically require the same core documents plus a placement test. Apostilling foreign documents is done in the country of issue — if you are coming from the UK, each document needs an apostille from the UK Foreign, Commonwealth and Development Office (FCDO); from Israel, from the Notary Public under the Ministry of Justice; from the US, from the Secretary of State in the issuing state. Factor 2–4 weeks for apostille processing into your timeline if you have not done this before leaving.",
      },
      {
        heading: "Accessing GeSY healthcare for children",
        body: "Children are registered under Cyprus's General Healthcare System (GeSY) as dependants of the registered parent. Once the primary adult's GeSY registration is complete (at hio.org.cy), dependants including children can be added to the same household health record. Each child receives access to the GeSY GP, referral system, specialist appointments, and hospital care under the same cost-sharing structure as adults (small co-payments per visit, no co-payment for children under specific thresholds). To add a child to GeSY, you need the child's ARC number or Yellow Slip number (for EU families), and the birth certificate. GeSY covers paediatric visits, vaccinations on the national schedule, referrals to paediatric specialists, and emergency hospital care. For children with chronic conditions or specific specialist needs, GeSY's network of approved specialist paediatricians is extensive in Limassol and Nicosia; coverage is thinner in Paphos and Larnaca, where private paediatric appointments (€60–€120 per visit) fill the gap.",
      },
      {
        heading: "Practical timeline for arriving families",
        body: "The recommended order for families relocating with children is: 1) Arrive and secure accommodation. 2) Register parents' ARC or Yellow Slip — this is the dependency anchor for everything else. 3) Apply for child's ARC using parents' permit as the basis. 4) Register with GeSY as a family unit once ARC or Yellow Slip numbers are issued. 5) Begin school enrollment — public school applications go to the District Education Office; international school admissions can be started earlier online before arrival. 6) Book a paediatric check-up to obtain a Cyprus immunisation certification letter, which most schools require. The whole sequence — from arrival to a child having an ARC, GeSY access, and confirmed school place — realistically takes 6–10 weeks if documents are prepared in advance. The single most common bottleneck is missing or un-apostilled birth certificates and school records; preparing these before you leave your home country saves a month.",
      },
    ],
  },
  {
    slug: "sen-guide",
    title: "Special Educational Needs in Cyprus — Resources and School Support",
    description:
      "What SEN provision actually looks like in Cyprus public and private schools, how to request an assessment, the role of the Educational Support and Evaluation Service, and where to find English-speaking therapists.",
    sections: [
      {
        heading: "SEN in the public school system",
        body: "Cyprus public schools operate under a Special Education legislation framework (Law 113(I)/1999, as amended) that mandates inclusion and support for pupils with SEN in mainstream schools. In practice, support is delivered through two main mechanisms: the Resource Room (tmima enischysis), where a specialist teacher works with pupils for dedicated pull-out sessions, and the in-class support teacher (parastas) for pupils with more significant needs who require continuous classroom support. The resource room model is the more common provision and is available in most primary schools in the main cities; secondary schools have fewer dedicated resources. EDEK — the Special Education department within the Ministry of Education — oversees the national SEN framework and manages the deployment of specialist teachers. The language of all public school SEN provision is Greek, which is a significant constraint for English-speaking children with SEN who have not yet acquired functional Greek.",
      },
      {
        heading: "The Educational Support and Evaluation Service (EAE)",
        body: "The EAE (Ypiresia Eidikou Paidagogikou Schediasmon kai Axiologisis) is the official assessment and evaluation service under the Ministry of Education. The EAE carries out psycho-educational assessments, issues formal diagnoses that qualify pupils for SEN support, and recommends the appropriate level of school-based provision. Referrals to the EAE are made through the school principal or class teacher. The assessment process typically takes 3–6 months from referral to formal report, during which time the child may be placed in resource room support on an interim basis. A written request from parents, supported by any prior private assessments (from the child's home country), can accelerate the priority queue. The EAE report is the gating document for any formal in-school provision — without it, schools may offer informal support but cannot commit specialist teacher hours. Parents of newly arrived children with existing diagnoses should request an EAE referral in their first week at school.",
      },
      {
        heading: "Private school SEN provision — the variance is large",
        body: "International and private schools in Cyprus vary enormously in SEN provision, and this is one area where visiting and asking specific questions before enrolment is essential. Heritage School Limassol has a dedicated Learning Support Department with multiple qualified staff, an established EHCP-equivalent individual education plan process, and experience supporting pupils with dyslexia, ADHD, autism spectrum conditions, and sensory processing needs — it is consistently cited as the most capable SEN provision in the private sector. Grammar School Limassol has support staff but a smaller specialist team. Paphos and Larnaca international schools generally have basic learning support for mild needs but limited capacity for complex profiles. ISP schools (International Schools Partnership group, which includes several Cyprus campuses) have a corporate SEN framework and dedicated coordinators at the larger campuses. When visiting schools, ask specifically: how many qualified SEN staff are employed, what IEP (Individual Education Plan) process they use, whether they support EHCPs from the UK, and what the maximum class size is in support groups.",
      },
      {
        heading: "English-speaking therapists in the private sector",
        body: "For children who need speech and language therapy, occupational therapy, applied behaviour analysis (ABA), or psychological support, the private sector in Cyprus has a growing English-speaking provider base — concentrated in Limassol and Nicosia, with more limited availability in Paphos and Larnaca. Limassol has the largest cluster of English-speaking child psychologists, speech and language therapists (SLTs), and occupational therapists (OTs); several practice groups specifically serve the expat community and accept international referral letters. Rates range from €60 to €120 per session for most therapies. ABA services for children with autism are available but the therapist pool is smaller — Nicosia has the most concentrated ABA provision. GeSY covers referrals to state-sector SLT and OT under certain conditions, but the waiting lists for state child therapy services are long (6–18 months in most districts); most families with SEN children use private providers and claim partial reimbursement via supplementary health insurance. Before relocating with a child who has significant therapeutic needs, research specific named practitioners in your target city — the availability of one trusted therapist can be the deciding factor between Limassol and Paphos as a base.",
      },
      {
        heading: "International SEN standards vs Cyprus reality",
        body: "Parents arriving from the UK with a child who has an Education, Health and Care Plan (EHCP) will find that Cyprus has no direct equivalent document — the EAE report and Individual Support Plan serve a similar function but with weaker legal enforceability. The legal right to appropriate SEN provision is established in Cyprus law, but the enforcement mechanism is less robust than the SENCO-and-EHCP framework that UK families may be used to. Parents from the US familiar with an IEP under IDEA will have a similar experience: the framework exists, the paperwork is possible, but the school's capacity to deliver the support depends heavily on which school and which year group. The practical advice from experienced SEN parents in Cyprus is: be an assertive advocate from day one, get the EAE referral in immediately, keep copies of all prior assessments translated into Greek, and build a relationship with a private therapist who can bridge the school-therapy gap. For children with significant needs, Limassol is materially better resourced than other Cyprus cities and is the practical first choice.",
      },
    ],
  },
];
