/**
 * Long-form relocation guides. Written for search engines + real readers
 * deciding whether to move to Cyprus. Each guide is ~1500–2500 words.
 *
 * Disclaimer: this is general information, not legal or tax advice. Specific
 * thresholds, deadlines and fees change frequently — always verify with the
 * Cyprus Tax Department, Civil Registry & Migration Department, and a local
 * accountant or lawyer before acting.
 */

export type GuideInfo = {
  slug: string;
  title: string;
  /** URL: /guides/{slug}. */
  description: string;
  sections: Array<{ heading: string; body: string }>;
};

export const GUIDES: ReadonlyArray<GuideInfo> = [
  {
    slug: "residency-and-visas",
    title: "Cyprus residency and visa options for relocators (2026 guide)",
    description:
      "What kind of permit you actually need to move to Cyprus — Permanent Residency by Investment, the Digital Nomad Visa, EU registration, and more.",
    sections: [
      {
        heading: "Why Cyprus has multiple paths",
        body: "Cyprus offers an unusually wide spread of residency options because it has tried hard, for the last decade, to attract residents in three distinct buckets: wealthy non-EU buyers (the Permanent Residency by Investment route), remote workers and freelancers (the Digital Nomad Visa), and EU citizens moving for work or lifestyle (which technically isn't a visa at all, just a registration). Each route has its own minimum thresholds and trade-offs, and the right one depends almost entirely on your passport and what you intend to do with your days. The good news: Cyprus is one of the easier EU member states to relocate to legally, and the immigration department in Nicosia is broadly responsive to well-prepared applications.",
      },
      {
        heading: "Permanent Residency by Investment (the property route)",
        body: "The most common path for non-EU buyers is the Permanent Residency by Investment programme — historically called Category F, currently regulated under Regulation 6(2) of the Aliens and Immigration Regulations. The headline requirement is a real-estate purchase of at least €300,000 (excluding VAT) in a newly-built residential property, paid via bank transfer from a Cypriot account. You also need to demonstrate annual income of at least €50,000 from sources outside Cyprus, plus an additional €15,000 for a spouse and €10,000 per dependent child. There is no minimum stay requirement once granted — you only need to visit Cyprus once every two years to keep the permit alive — which is what makes it popular with families who plan to keep one foot somewhere else for tax or schooling reasons. The permit covers spouse and unmarried children up to 25 if financially dependent, and it does not directly lead to citizenship: that's a separate naturalisation track that requires seven years of legal residence with most of the time physically spent in Cyprus.",
      },
      {
        heading: "Digital Nomad Visa",
        body: "Cyprus introduced its Digital Nomad Visa in late 2021 and significantly expanded it in 2024. It targets non-EU nationals who work remotely for foreign employers or as freelancers serving non-Cyprus clients. The minimum income requirement is €3,500 per month net (after tax, social contributions and any other deductions), increased by 20% for a spouse and 15% per dependent child. The visa is issued for one year, renewable for up to three years, and gives you full residency rights including the ability to bring family members. Crucially, after 183 days in Cyprus during a tax year, you become a Cyprus tax resident — which can be either an advantage (Cyprus has favourable tax treatment for foreign-sourced income and a tax-free dividend regime for non-domiciled residents) or a disadvantage (you may have new filing obligations in Cyprus), depending on your home country's tax treaty and your specific situation. The application is processed through the Civil Registry and Migration Department; expect about 5–8 weeks if your documents are clean.",
      },
      {
        heading: "EU citizens and family members",
        body: "If you hold an EU passport, you do not need a visa to live in Cyprus. After 90 days of continuous presence, you must register your residence with the Civil Registry — they issue a Registration Certificate (often called an MEU1 or yellow slip, though the slip itself is now blue). The requirements are minimal: proof of accommodation (a rental contract or property deed), proof of health insurance or registration with the General Healthcare System (GeSY), and either proof of employment or proof of sufficient funds (typically the same €30,000–€40,000 per year as a self-supporting resident). EU registration is permanent — there is no expiry date — and after five years of continuous legal residence you qualify for the Long-term Residence permit, which carries near-identical rights to citizenship.",
      },
      {
        heading: "Practical advice",
        body: "Three pieces of advice that come up consistently in expat forums. First, do not rely on a tourist entry to scout property and then formalise the residency later — both the PR and digital nomad visas require you to apply from outside Cyprus or via a specific in-country procedure, and people get bounced back to their home country surprisingly often if they apply wrong. Second, work with a local lawyer for any property-based application — fees of €1,500–€3,000 are normal, the paperwork is genuinely intricate, and a botched application can delay things by a year. Third, keep originals of every document you used in the application. Cyprus immigration is paper-heavy and a request to re-prove your income from three years ago is not unusual at renewal.",
      },
    ],
  },
  {
    slug: "cost-of-living",
    title: "Cost of living in Cyprus — what relocators actually spend (2026)",
    description:
      "Realistic monthly budgets for Limassol, Paphos, Larnaca and Nicosia — rent, utilities, food, schooling, healthcare and transport.",
    sections: [
      {
        heading: "How the regions compare",
        body: "Cost of living in Cyprus splits sharply by region. Limassol is the most expensive city by a meaningful margin — about 30 to 50 percent more expensive than Larnaca, Paphos or Nicosia for equivalent housing. The other three cities are surprisingly close to each other on most metrics, with Paphos slightly cheaper for property purchase, Larnaca slightly cheaper for groceries and Nicosia slightly cheaper for everything except restaurants. Rural villages can be a third cheaper again, with the trade-off of needing two cars per household and longer drives to schools and hospitals. The cheapest region overall is the Famagusta free area outside the summer months, when resort pricing inflates everything from coffee to taxis.",
      },
      {
        heading: "Rent and utilities",
        body: "A two-bedroom apartment in a modern building (built in the last ten years, balcony, parking, walking distance to amenities) runs roughly: Limassol €1,400–€2,200, Larnaca €900–€1,400, Paphos €850–€1,400, Nicosia €900–€1,500. Sea-view tower apartments in Limassol's seafront strip push past €3,000 easily. Electricity in Cyprus is notoriously expensive — the EAC (Electricity Authority) is a state monopoly and a hot Cypriot summer with the AC on can produce a €350–€450 bill for a two-bedroom flat, billed every two months. Water is comparatively cheap (under €30 per month for most households). Internet is fast and reliable — 1 Gbps fibre packages run €40 to €60 per month with most providers — and mobile data is among the cheapest in the EU at €15 to €25 for an unlimited plan.",
      },
      {
        heading: "Food, restaurants and groceries",
        body: "A weekly supermarket shop for a family of four lands around €120 to €180. The main chains — Sklavenitis, Lidl, Alphamega, Metro — cover the spectrum from value to premium. Imported brands carry a real premium (think 30–50% over equivalent UK or German pricing) but Cypriot produce is cheap and excellent: tomatoes, courgettes, watermelon, halloumi, olive oil and most fish are roughly half what you'd pay in northern Europe. Restaurant prices are reasonable but trending up: a sit-down meze dinner for two with a bottle of wine is €60 to €90 outside the touristy areas, €100 to €150 inside them. The lunch menus, where they exist, are exceptional value — €10 to €15 for two courses including coffee at a normal weekday restaurant in any of the four cities.",
      },
      {
        heading: "Healthcare and schooling",
        body: "Cyprus's public General Healthcare System (GeSY) covers all residents and is genuinely usable — primary care, specialists, prescriptions and most hospital procedures are free or have small co-payments. Most relocators also keep a private health insurance plan (€800 to €2,500 per adult per year depending on age and coverage) for faster access to specialists and private hospitals. Private hospitalisation is meaningfully cheaper than the UK or US — a normal childbirth runs around €2,500–€4,000 at a top private hospital, MRIs around €350, dental cleanings around €60. International schooling is where the budget gets serious: expect €5,000–€10,000 per child per year at the cheaper end (Paphos, Larnaca), and €10,000–€18,000 at the established Limassol and Nicosia schools. Public school is free and rapidly improving its English-medium programming, but most established relocators still default to private for secondary years.",
      },
      {
        heading: "Transport and the realistic monthly budget",
        body: "Cyprus is a car culture. Public transport is functional within Limassol and Nicosia and almost non-existent everywhere else; outside the cities a car is essentially mandatory. Used cars are cheap by EU standards (a 2018 Toyota Yaris is €7,000–€9,000) but new cars carry significant registration tax. Petrol runs around €1.40 per litre. Putting it all together, a realistic monthly budget for a family of four living comfortably (two-bed apartment in a non-towering complex, one car, private school for one child, both adults working): Limassol €4,500–€6,000, Larnaca/Paphos/Nicosia €3,200–€4,500. A retired couple in Paphos or Larnaca living modestly can do well on €2,500–€3,000 per month. Add €500–€1,000 if you want to eat out frequently or run a second car.",
      },
    ],
  },
  {
    slug: "taxes-for-expats",
    title: "Taxes for relocators in Cyprus — the non-dom regime and what it means",
    description:
      "How Cyprus's tax system works for new residents — the famous non-domiciled rules, the tax-free income band, capital gains and crypto.",
    sections: [
      {
        heading: "The headline: why Cyprus attracts tax migrants",
        body: "Cyprus's tax system has become a quietly important reason that wealthy non-EU and EU professionals consider relocating to the island. The headline features are three: a 0% personal income tax band on the first €19,500 of annual income, a flat 12.5% corporate tax rate (one of the lowest in the EU), and most importantly the non-domiciled (non-dom) regime, which exempts new residents from any tax on dividends, interest income, and most foreign-sourced passive income for up to 17 years. For someone whose income is largely derived from investments, dividends or a foreign company, Cyprus can plausibly be the most tax-efficient EU country to be tax resident in, by a wide margin. The catch is that you need to actually become tax resident, and the recent rules around tax residency are stricter than the marketing brochures suggest.",
      },
      {
        heading: "Becoming a Cyprus tax resident",
        body: "There are two ways to qualify as a Cyprus tax resident. The classic test is the 183-day rule: if you spend more than 183 days in Cyprus during a calendar year, you are tax resident for that year. The second is the 60-day rule introduced in 2017, designed specifically to attract high earners who travel: you can be tax resident with only 60 days in Cyprus provided you (a) do not spend more than 183 days in any other country in the same year, (b) are not tax resident anywhere else, (c) have a permanent residence in Cyprus (rented or owned), and (d) carry on business or employment in Cyprus, including holding an office in a Cyprus-resident company. The 60-day rule is what makes Cyprus genuinely attractive to globally mobile entrepreneurs, but it is also where most tax-residency disputes happen — the Cyprus Tax Department has tightened audit on the 60-day applications, and you need real substance to defend it.",
      },
      {
        heading: "The non-dom regime in detail",
        body: "Non-dom status is automatic for tax residents who have been domiciled outside Cyprus, which in practice means almost every relocator. Once you are a Cyprus tax resident and a non-dom, the following income types are completely exempt from Cyprus tax: dividends received from anywhere in the world, interest received from anywhere, rental income from properties outside Cyprus (though you still pay Cyprus's GeSY healthcare contribution on it — 2.65%), capital gains on shares and securities, and most types of capital gains on property outside Cyprus. The non-dom regime lasts for 17 of the 20 tax years following your relocation, so it is genuinely long-term. For employment income earned in Cyprus, you pay regular Cypriot income tax (0% on the first €19,500, scaling up progressively to 35% above €60,000), and for self-employment income earned in Cyprus the same. There is a special 50% income tax exemption for new residents earning more than €100,000 per year from Cypriot employment for the first 17 years.",
      },
      {
        heading: "Capital gains, property and crypto",
        body: "Cyprus capital gains tax applies only to gains on Cypriot real estate and on shares of companies that hold Cypriot real estate. The rate is 20% on the gain, with several lifetime exemptions (€85,430 for a primary residence sold once in your lifetime, smaller exemptions for agricultural land and gifts to family). All other capital gains — including foreign property, all listed shares, all private company shares (unless they hold Cypriot real estate), gold, crypto — are completely tax-free. Crypto is the source of significant uncertainty: Cyprus has not yet released formal guidance on whether crypto trading by individuals is taxable income (most accountants currently treat occasional disposals as exempt capital gains, and active day-trading as taxable self-employment income), and this is the single biggest tax question relocators should pin down with a local accountant before assuming the position.",
      },
      {
        heading: "Filing, deadlines and getting it right",
        body: "Cyprus's tax year is the calendar year. Individual tax returns (Form TD1) are due by 31 July of the following year if you file electronically — the deadline used to be later but was tightened in 2024. The forms are not complex by EU standards, but the non-dom and 60-day declarations need to be made affirmatively each year, and the Tax Department has increasingly asked for travel-day records, accommodation contracts and economic-substance evidence to support 60-day claims. An accountant fee for a non-dom individual return runs €400–€900 per year, which is money well spent — DIY filing is technically possible but the cost of getting the non-dom claim wrong is large. The final pragmatic note: Cyprus has double-tax treaties with over 65 countries including the UK, Germany, France, India, Russia, South Africa and most of the EU, so relocators rarely face actual double-taxation; they face complexity. The cleanest move is to settle your prior-country tax exit properly before claiming Cyprus residency, rather than trying to do both at once.",
      },
    ],
  },
  {
    slug: "buying-process",
    title: "How to buy property in Cyprus — the full buying process step by step",
    description:
      "From the first viewing to the title deed in your name: reservation, lawyer, sales contract, deposits, completion and registration in Cyprus.",
    sections: [
      {
        heading: "Before you start: deciding what and where",
        body: "Buying property in Cyprus follows a roughly predictable path that takes between two and twelve months depending on whether you are buying off-plan (an apartment that isn't built yet) or completed (an already-existing flat or house). Before signing anything, three preliminary decisions matter more than any other. First, region — Limassol, Paphos, Larnaca, Nicosia and Ayia Napa have very different price brackets, lifestyles, schooling options and rental yields; spend a week in your shortlisted region in low season (November–February) and high season (July–August) before committing. Second, new versus resale — new builds carry 19% VAT (or 5% reduced VAT on a first primary residence under specific conditions, capped at 130 m² for properties up to €350,000), while resales pay transfer fees instead, typically 1.5–4% of the price after exemptions. Third, financing — Cyprus banks (Bank of Cyprus, Hellenic Bank, Eurobank, Astrobank, Alpha Bank Cyprus) lend to non-residents at 30–50% deposit and a fixed-or-variable rate currently in the 3.5–5.5% range, but the documentation requirements are heavy and most buyers complete the purchase before approaching a bank for refinancing. Cash buyers complete much faster.",
      },
      {
        heading: "Step 1: Reservation agreement",
        body: "Once you have settled on a specific unit, the developer or selling agent will ask for a reservation. This is a short written agreement (one or two pages) that takes the property off the market for typically 14–30 days while your lawyer does due diligence. The reservation fee is usually €2,000–€10,000 depending on the property's price, paid into the developer's escrow account or directly into the seller's account. Critically, the reservation fee is normally refundable if the due diligence turns up problems and you withdraw within the agreed window — but the agreement must be written to make that explicit. Never sign a reservation that does not specify the conditions under which the fee is returned. At this stage you should also receive: the developer's company registration certificate, recent audited accounts, a copy of the title or the right-of-ownership document, the building permit (if off-plan), and the technical specifications of the unit. Your lawyer will want to see all of these before you proceed.",
      },
      {
        heading: "Step 2: Choose a lawyer (the most important hire)",
        body: "Hiring an independent Cyprus property lawyer is the single most important step in the entire process. Do not use the developer's or the agent's recommended lawyer — Cyprus has had multiple historical scandals around developer-linked lawyers protecting the developer's interest at the buyer's expense. Find an independent local lawyer through the Cyprus Bar Association (cyprusbarassociation.org) or through a referral from a recent Cypriot expat. Expected fees: €1,500–€3,000 for a full property purchase up to €500,000, more for higher-priced or complex deals. The lawyer will do title searches at the Land Registry, verify the developer's mortgages and encumbrances on the land (a critical step — historically many Cyprus title-deed delays were caused by undisclosed bank mortgages on the developer's land that should have been cleared before unit handover), draft and negotiate the Sale and Purchase Agreement, oversee deposit transfers, register the contract with the Land Registry (which protects you against the developer selling the same unit twice), apply for any permits you need, and eventually file the title deed in your name once it issues. A good lawyer also assists with residency applications if applicable.",
      },
      {
        heading: "Step 3: Sale and Purchase Agreement",
        body: "The Sale and Purchase Agreement (SPA) is the binding contract. It typically runs 20–40 pages and must specify, at minimum: the exact unit being sold (with reference to the developer's plans and the Land Registry plot), the total price, the payment schedule (often staged against construction milestones for off-plan), the expected delivery date, what happens if the developer delays, the specification of materials and finishes (look for the FF&E schedule — fixtures, finishes and equipment), the share of common areas that comes with the unit, any defects-rectification period after handover, and which party pays which fees. A few specific clauses to insist on. First, late-delivery penalties — typically 0.5% of the price per month of delay after a stated grace period; without this, developers have little incentive to deliver on time. Second, defects rectification — typically two years for hidden defects after handover, with the developer responsible for repair. Third, common-area maintenance — the SPA should clarify whether common areas are part of the price or charged separately. Sign the SPA only when your lawyer is satisfied; once signed, retracting is expensive.",
      },
      {
        heading: "Step 4: Deposit, stamping and Land Registry filing",
        body: "On signing the SPA, a deposit becomes due — typically 20–30% of the purchase price, paid by bank transfer into the developer's account. Within 30 days of signing, the SPA must be stamped at the Tax Department (stamp duty is small — 0.15% of the first €170,000 and 0.20% above that, capped at €20,000 total) and lodged with the Land Registry (filing fee ~€50). Lodging with the Land Registry is what protects you from the developer selling the same unit again or pledging it as security; do not let this step slip. For off-plan purchases, subsequent payments are due against construction milestones — typically 25% on foundation completion, 25% on roof completion, 20% on internal works completion, and the balance on handover. Each milestone payment is signed off by an independent structural engineer; do not pay milestones the engineer has not confirmed. For completed properties, the full balance is due at the title-deed transfer (Step 6).",
      },
      {
        heading: "Step 5: Permits — Council of Ministers approval for non-EU buyers",
        body: "Non-EU buyers — including, post-Brexit, UK passport holders unless they hold an EU passport — need approval from the Cypriot Council of Ministers to register property in their name. This is a formality in 95% of cases (a non-EU buyer can own up to two properties, including one residential plus one piece of land up to 4 dönüm / 5,350 m²), but it adds 4–8 months to the process. The application is filed by your lawyer and includes proof of clean criminal record (apostilled from your home country), proof of funds, and the SPA. The Council of Ministers approval is normally still pending at handover; you take physical possession and live in the property while waiting, with the SPA registered at the Land Registry protecting your interest. The final title-deed transfer (Step 6) cannot happen until approval comes through.",
      },
      {
        heading: "Step 6: Handover, title deed and transfer fees",
        body: "Handover is when the developer hands you the keys — usually after a joint inspection where you note any defects (the snag list) and the developer agrees to rectify them within an agreed window. From the handover date you typically have utility connections to set up (EAC for electricity, the local water board, your chosen internet provider) and to register the property for municipal taxes. The title-deed transfer is a separate, later event. For off-plan properties this often happens 1–3 years after handover, once the developer has obtained the final certificate of approval for the building from the local authority and the Land Registry has separated the title into individual unit titles. For resale properties, the transfer happens immediately at the Land Registry. Transfer fees at the Land Registry are 1.5%/2.5%/4% of the price in three bands (€0–85k / €85k–170k / above €170k), with a 50% reduction available, and full exemption on new builds where VAT has already been paid. Once the title deed issues in your name, you are the legal owner.",
      },
      {
        heading: "Costs to budget for and common pitfalls",
        body: "Beyond the purchase price, budget roughly 7–10% in fees on a new build (19% VAT or 5% reduced; legal fees; stamp duty; Land Registry filing; possible Council of Ministers fees) and 3–5% on a resale (transfer fees; legal fees; stamp duty). The most common pitfalls Cyprus buyers experience: (1) Title-deed delays — historically Cyprus developers were slow to deliver title deeds and a portion of the older stock still has pending titles; only buy from a developer whose recent track record on title delivery is verifiable. (2) Hidden developer mortgages on the underlying land — if a developer borrowed against the land and goes bankrupt, the bank's mortgage can seize the property even after you've paid for it. The 2015 Specific Performance Law and various 2016+ reforms have improved buyer protection here, but the issue still exists for older or less reputable developers — your lawyer must verify the land is unencumbered or that the developer's mortgage is being released against your specific unit. (3) Off-plan delivery delays of 6–18 months are common; build a buffer into your move plans. (4) Specifications drift — what you saw in the show flat is not always what you get in your unit; insist on a detailed FF&E schedule in the SPA. (5) VAT refund timing — if you qualify for the 5% reduced rate, the refund of the difference can take 12–24 months to process; budget cash flow accordingly. Use the price, region, and unit filters on this site to shortlist developments, then take that shortlist to an independent lawyer for due diligence.",
      },
    ],
  },
  {
    slug: "property-taxes-2026",
    title: "Cyprus property taxes 2026 — VAT, transfer fees, capital gains, rentals",
    description:
      "Every tax on Cyprus property in 2026: VAT (19% or reduced 5%), transfer fees, stamp duty, capital gains, rental income, and municipal taxes.",
    sections: [
      {
        heading: "The taxes you actually pay",
        body: "Cyprus's property tax framework is simpler than the UK or US but has several moving parts. The taxes that hit Cyprus property fall into five categories: transaction taxes (paid once, at purchase), holding taxes (paid annually while you own), income taxes (paid on rental income), exit taxes (paid when you sell), and inheritance considerations (paid when ownership transfers at death). Importantly, Cyprus abolished its annual immovable property tax (IPT) in 2017, which is one of the lowest-friction parts of the system: there is no headline annual property tax in Cyprus, only small municipal taxes. This guide covers each category in detail with 2026 rates. The single most important thing to know up front: most of the buyer taxes are heavily dependent on whether the property is brand new (carries VAT) or resale (carries transfer fees), so the choice between new and resale has tax implications beyond the obvious.",
      },
      {
        heading: "VAT on new-build property",
        body: "Cyprus charges 19% VAT on new-build residential property — the standard EU rate. For first-time buyers using the property as their primary residence, a reduced rate of 5% VAT applies to the first 130 m² of buildable area (130 m² of building, not plot), provided the total transaction value does not exceed €350,000 and the buyable area does not exceed 190 m². The reduced rate is the single biggest tax saving available to Cyprus property buyers: on a €300,000 apartment, the difference between 19% and 5% VAT is €42,000. To qualify, the buyer must (a) be 18 or older, (b) not have benefited from the reduced VAT rate on a previous property in Cyprus, (c) use the property as their main residence for at least ten years (if you sell or rent out the property within ten years, you must repay the difference between 5% and 19% pro-rata for the years remaining), and (d) be a Cyprus tax resident or planning to become one. Non-EU buyers can qualify for the reduced rate, but should plan for the ten-year primary-residence requirement carefully. The application is made by your lawyer to the Cyprus Tax Department and typically processed within 6–12 weeks; the refund of the VAT difference is paid back into your account.",
      },
      {
        heading: "Transfer fees on resale property",
        body: "Resale properties do not carry VAT; instead, the buyer pays transfer fees to the Land Registry. The rates are: 1.5% on the first €85,000, 2.5% on the portion from €85,000 to €170,000, and 4% on anything above €170,000. So a €300,000 resale property would carry €1,275 + €2,125 + €5,200 = €8,600 in transfer fees. Cyprus has, however, applied a 50% reduction on transfer fees since 2012, and that 50% reduction has been extended every year since — making the effective rate currently 0.75% / 1.25% / 2.0%. The €300,000 resale example becomes €4,300 in effective transfer fees. The 50% reduction does not apply to gifts or inheritance, only to arm's-length sales. Note that resale property where VAT was originally paid by the first buyer is exempt from transfer fees entirely — so if you're buying a 2018 apartment from its first owner who paid VAT in 2018, you pay no transfer fees. This is a meaningful saving and worth confirming in writing through your lawyer.",
      },
      {
        heading: "Stamp duty and miscellaneous fees",
        body: "Cyprus stamp duty applies to all property purchase contracts at 0.15% on the first €170,000 and 0.20% on amounts above, capped at €20,000 total. On a €300,000 transaction this is €255 + €260 = €515. The contract must be stamped at the Tax Department within 30 days of signing or late penalties apply. Land Registry filing fees are negligible — typically under €100 to register the SPA and an additional small fee for the title transfer. Legal fees are not technically a tax but should be budgeted alongside them: €1,500–€3,000 for a standard purchase up to €500,000. For non-EU buyers, the Council of Ministers permit application carries small government fees (~€500). If you are also obtaining residency via the €300,000 property purchase route, your residency application carries additional fees of approximately €500 in government charges. Bank charges for international wire transfers in EUR to Cyprus banks are typically €25–€80 from EU SEPA countries and higher from non-SEPA sources. Total transaction friction on a €300,000 new build with reduced VAT is around €17,000–€20,000 (5% VAT + stamp + legal + small fees); on a €300,000 resale with the 50% transfer-fee reduction, around €6,000–€7,000.",
      },
      {
        heading: "Municipal taxes and ongoing holding costs",
        body: "Annual property holding costs in Cyprus are modest. The national immovable property tax (IPT) was abolished in 2017 — there is no equivalent of the UK Council Tax or US property tax at the national level. What you pay each year is: (1) Municipal property tax, levied by your local municipality (Limassol, Larnaca, Paphos, Nicosia, Famagusta-area municipalities) at a rate that varies by municipality but typically 0.1%–0.5% of the property's assessed value, generally producing an annual bill of €100–€500 for a typical apartment. (2) Sewerage tax (separate from refuse), 0.05%–0.30% of assessed value annually, typically €50–€250. (3) Refuse collection charge, a flat annual amount of €120–€220 in most municipalities. (4) Communal common-area charges (kinochrista) if your unit is in a development with shared facilities — these are paid to the management committee, not the government, but feel like a tax: budget €100–€500 per month depending on pool, gym, lifts, security. Total annual holding cost on a typical two-bedroom Cyprus apartment is generally €1,500–€5,000 all-in, with common charges driving most of the variation.",
      },
      {
        heading: "Rental income tax",
        body: "Rental income from Cyprus property is taxable to Cyprus tax residents at their personal income tax rates (0% on the first €19,500; 20% on €19,500–€28,000; 25% on €28,000–€36,300; 30% on €36,300–€60,000; 35% above €60,000), with several allowances. Specifically: a 20% deduction is allowed against gross rental income to cover repairs and maintenance, regardless of actual expenses (a 'wear and tear' allowance), so only 80% of gross rent is taxable. Mortgage interest on the property is deductible. Actual major repair expenses (separate from the 20% allowance) are deductible if you have receipts. Building depreciation at 3% per year is deductible. There is also a 3% Special Defence Contribution (SDC) on rental income for Cyprus-domiciled residents — but non-dom new residents are exempt from SDC, which is part of why the non-dom regime is so attractive to landlords. For non-Cyprus tax residents (e.g. someone who owns a Cyprus rental but lives in the UK), withholding tax of 25% on net rent applies, often reduced by Cyprus's double tax treaties. Short-term rentals (Airbnb / holiday lets) follow the same tax rules but require a tourism licence from the Deputy Ministry of Tourism — operating without one carries fines of €1,500–€5,000 per breach.",
      },
      {
        heading: "Capital gains tax when you sell",
        body: "Cyprus capital gains tax (CGT) applies only to gains on Cypriot real estate (or shares in companies holding Cypriot real estate). The flat rate is 20% on the realised gain. Several reliefs apply. (1) A lifetime exemption of €17,086 on any disposal of property. (2) An additional lifetime exemption of €25,629 if you are disposing of agricultural land. (3) A larger lifetime exemption of €85,430 for the sale of your primary residence (Cyprus only allows this exemption once per lifetime). (4) Indexation: the original cost basis is adjusted upward for Cyprus inflation since the purchase date, reducing the taxable gain. (5) Improvements with documented receipts are added to the cost basis. The CGT is calculated by the Land Registry as part of the sale process and is settled before the title deed transfers to the new buyer — sellers cannot avoid it by leaving Cyprus. Gifts of property between family members (parents to children, between spouses) are exempt from CGT. Gains on foreign property held by Cyprus tax residents are completely exempt from Cyprus CGT, regardless of size — one of the most generous CGT positions in the EU and a meaningful benefit of becoming a Cyprus tax resident.",
      },
      {
        heading: "Inheritance and getting professional help",
        body: "Cyprus abolished inheritance tax in 2000, so property passing to heirs at death is not subject to any Cypriot inheritance tax. The estate may still face inheritance tax in the deceased's country of domicile (for example, UK inheritance tax can still apply to Cyprus property if the deceased was UK-domiciled), which is why high-net-worth relocators should usually update their will and consider whether to claim non-domicile status in their prior country. Cyprus succession law applies to the property — by default, Cyprus follows EU Regulation 650/2012 (Brussels IV), meaning EU citizens can elect the law of their nationality to govern their estate in their will, which avoids forced-heirship complications. The practical recommendation: always use a Cyprus tax-qualified accountant (€400–€1,200 per year) for ongoing rental and CGT positions, and a property lawyer for any sale; the costs are small relative to the tax savings and the audit risk avoided. Cyprus property taxation rules have evolved meaningfully in the last decade and this guide reflects 2026 settings — verify any specific figure with a professional before relying on it for a decision.",
      },
    ],
  },
  {
    slug: "schools-in-cyprus",
    title: "International schools in Cyprus — full guide for relocating families",
    description:
      "Every major English-medium, American and IB school in Limassol, Nicosia, Paphos, Larnaca and the Famagusta area — fees, curricula, admissions.",
    sections: [
      {
        heading: "The shape of the school market",
        body: "Cyprus has three parallel school systems running side by side, and any relocating family needs to choose deliberately between them. The public (state) school system is free for all residents, taught in Greek, with an increasingly developed Greek-as-a-second-language programme for international children. The private Greek-medium system serves families who want smaller class sizes and stronger academics but a Cypriot cultural environment. The private English-medium system — what most relocators end up choosing — is the dominant choice for international families, offering British curriculum (the largest category), American curriculum (a smaller but well-established subset), International Baccalaureate Diploma at sixth-form level in many schools, and small French, Russian and Lebanese-Arabic options in specific cities. Public schooling works well for primary-age children with time to acquire Greek; for secondary-age teens, most expat families choose private English-medium to ensure smooth integration into UK or international universities. Annual fees in private schools range from €4,500 to €18,000 depending on city, curriculum and school prestige.",
      },
      {
        heading: "Limassol — the deepest international market",
        body: "Limassol hosts the largest concentration of international schools in Cyprus. The Heritage Private School in Pyrgos is the most prestigious and most expensive — British curriculum from age 3 to 18, with IB Diploma at sixth form, fees from €8,000 (early years) to €14,000 (sixth form), and a waiting list for senior-year admissions of typically 6–12 months. Foley's Grammar School is the second flagship British-curriculum option, broadly comparable academically with slightly more accessible admissions and fees of €6,500–€11,000. The Grammar School Limassol covers ages 3 to 18 in British curriculum with strong A-level results, fees €6,000–€10,000. The American Academy Limassol covers American curriculum through AP level, fees €5,500–€9,500. For Russian-medium schooling, several private Russian schools operate in the city though enrolment has declined sharply since 2022. The City University Limassol and Cyprus University of Technology give Limassol the strongest secondary-to-tertiary pipeline on the island; many Limassol expat families specifically choose this for the option of children continuing at local university.",
      },
      {
        heading: "Nicosia — diplomatic and academic depth",
        body: "Nicosia has the longest-established international schools on the island. The English School Nicosia, founded in 1900 by the British colonial administration, is the oldest and most prestigious — selective entry (entrance exam at age 11), fees around €6,000–€9,000, and consistently strong A-level outcomes that send graduates to Oxbridge, Russell Group and Ivy League universities. The American International School (AIS) Cyprus offers full US curriculum from kindergarten through Grade 12 plus IB Diploma, on a single shared campus in Engomi serving the diplomatic community alongside international families. The Junior School covers early years and primary in British curriculum. The Falcon School and Pascal Schools provide additional British-curriculum capacity. For Greek-medium private schooling, Manessis School and The Grammar School Nicosia are the established names. Nicosia's secondary-to-tertiary integration is the strongest in the country — the University of Cyprus (public, flagship) and the University of Nicosia (private, home of the medical school) make Nicosia particularly suitable for families with academically ambitious teenagers planning to study at home rather than abroad.",
      },
      {
        heading: "Paphos and Larnaca — quality without scale",
        body: "Paphos and Larnaca have smaller international school markets but with credible options. In Paphos, The International School of Paphos is the largest English-medium school, British curriculum from age 3 to 18, fees €5,800–€9,200. Aspire Private British School covers ages 4–18 with smaller class sizes (~14 per class) and fees €5,500–€8,500. Logos School of English Education is the older, more academic option with consistently strong A-level results. École Française de Paphos serves French-medium families at primary level. Neapolis University Paphos provides local tertiary education in psychology, law and business. In Larnaca, The American Academy Larnaca is the best-known English-medium school, US-style curriculum through to Grade 12 with SAT preparation, fees €5,500–€8,500. Pascal Private School operates a Larnaca campus alongside its Nicosia and Limassol locations. The Med High School covers ages 12–18 with British curriculum. Several smaller British-curriculum primary schools serve the under-12 expat population. Larnaca's tertiary options are thinner — most students continue at Nicosia or Limassol universities or go abroad.",
      },
      {
        heading: "The Famagusta-Ayia Napa area — the schooling challenge",
        body: "The Famagusta free area has the thinnest school market of the five regions on this site, and schooling is the single most common reason families with secondary-age children choose Larnaca over Protaras or Ayia Napa despite preferring the SE beaches. The Heritage Private School Paralimni (distinct from the Limassol Heritage) is the main local British-curriculum option, well-regarded at the primary level with secondary years still being established. A small number of additional preschools and primaries serve the expat community. For secondary education (ages 12–18), most expat families in the SE either commute their children daily to The American Academy Larnaca (35–45 minutes each way) or to one of the Larnaca British schools, or — for a small minority — board their teenagers in Nicosia. Public Greek-medium schools in Paralimni, Sotira and Frenaros are good and have absorbed meaningful numbers of expat primary children. The pragmatic recommendation for families with school-age children considering the SE: confirm your school plan before signing on the property, including a test of the daily commute.",
      },
      {
        heading: "Curricula and university outcomes",
        body: "The dominant curriculum across Cypriot international schools is British — IGCSE at age 16, A-level or BTEC at 18 — followed by American curriculum (Grade 12 high school diploma, with SAT or ACT for university applications) and the International Baccalaureate Diploma (offered at Heritage Limassol, AIS Nicosia, and a few others). Choosing a curriculum should follow the likely university destination: A-levels are well-recognised for UK, Ireland and most European universities; American curriculum + SAT is best for US universities; IB Diploma is the most universal and well-respected at top European and US universities but is more academically intensive. For students likely to attend Cypriot or Greek universities, public Greek-medium schooling can actually be a better preparation route, since Cyprus and Greek universities give admission preference to Greek-medium graduates. University outcomes from the top Cypriot international schools are strong — The English School and Heritage routinely send graduates to Oxbridge, Imperial, UCL, LSE and top US schools; mid-tier private schools place strongly into UK and Greek universities; the public system produces the bulk of graduates at the University of Cyprus and University of Nicosia.",
      },
      {
        heading: "Fees, admissions and practical advice",
        body: "Private school fees in Cyprus are paid annually, typically in three terms (September, January, April). Most schools also charge a one-time application fee of €100–€300 and an annual registration/enrollment fee of €300–€700 on top of tuition. Sibling discounts of 10–15% are common. Extras to budget for: uniforms (€300–€800 in the first year), school transport if you live more than 20 minutes from school (€2,000–€4,000 per year), after-school activities (€500–€2,000), school trips (€500–€1,500), and exam fees at IGCSE/A-level/IB (€1,000–€3,000 in exam years). Admissions for the top schools (Heritage, English School Nicosia) typically require an entry test plus interview; applications open 9–12 months in advance, and waitlists for senior years are real. For other private schools, admissions are generally rolling but the popular year-groups fill 6–9 months ahead. Pragmatic advice: start the school search before you commit to a region or development, contact 3–4 schools in your target region for tours, visit during the academic year (not in July/August when schools are closed), and join the Cyprus relocation Facebook groups for current parent reviews — published Ofsted-equivalent inspection data is limited for Cypriot schools and parent forums are the best source of unvarnished information.",
      },
    ],
  },
  {
    slug: "healthcare-in-cyprus",
    title: "Healthcare in Cyprus — GeSY, private hospitals, and what to know as a new resident",
    description:
      "How healthcare works in Cyprus in 2026 — the national GeSY system, private hospitals, insurance, dental, mental health and emergencies.",
    sections: [
      {
        heading: "The GeSY revolution",
        body: "Cyprus's General Healthcare System, known by its Greek acronym GeSY (sometimes anglicised as GHS), is the country's universal healthcare system. It was rolled out in two phases — outpatient care in 2019, inpatient care in 2020 — and now provides healthcare to essentially all legal residents of Cyprus. Before GeSY, Cyprus had a fragmented system where public hospitals were generally seen as a last resort and most professionals carried private insurance; the GeSY rollout fundamentally changed the country's healthcare market by making free, universal, EU-standard public care available across the island. For relocators, this means that healthcare costs are much lower than the UK or US and access is meaningfully better than most southern European countries. GeSY funding comes from a payroll deduction — currently 2.65% from the employee, 2.90% from the employer, and 4.70% from the state — and applies automatically to anyone legally resident with social insurance contributions. Pensioners pay 2.65% on pension income. Self-employed residents pay 4% on their declared income.",
      },
      {
        heading: "Registering with GeSY",
        body: "Once you are legally resident in Cyprus — EU registration certificate, work permit, residence permit, or refugee status — you are eligible to register with GeSY. The process is straightforward: register online at gesy.org.cy with your Cypriot social insurance number, residence permit details, and a valid Cypriot address. You then select a Personal Doctor (essentially a GP) from a list of providers in your area; this person becomes your primary point of contact for the system. Many Personal Doctors are general physicians; some have specific specialisations (paediatrics, family medicine). Registration is free and instant; you receive a digital GeSY beneficiary card immediately and use your social insurance number for all subsequent visits. Children under 18 are automatically registered with one of their parents' Personal Doctors but can be transferred to a paediatrician. Switching your Personal Doctor is allowed up to four times per year. For non-residents (tourists, short-term visitors), GeSY does not apply — you need travel insurance or pay out-of-pocket. Note that the Digital Nomad Visa requires you to hold private health insurance during your first year of residency before GeSY registration becomes available.",
      },
      {
        heading: "What GeSY covers",
        body: "GeSY covers an extensive list of services with no out-of-pocket cost or with very small co-payments: visits to your Personal Doctor (free), visits to specialists by referral from your Personal Doctor (€6 per visit, capped at €150 per year per beneficiary), all prescription medications dispensed by GeSY-contracted pharmacies (€1 co-payment per prescription, also capped annually), most laboratory and imaging tests at GeSY-contracted facilities (€1 per test up to caps), inpatient hospitalisation including surgery at GeSY-contracted public and private hospitals, emergency room visits (€10 co-payment), childbirth (free), preventive care including vaccinations and screening tests (free), mental health services (free to €6 per visit). Dental care is included for children under 18 (free preventive and conservative care) and partially included for adults (some basic interventions). Major exclusions: cosmetic procedures, fertility treatments beyond a limited subsidised programme, most adult dental work beyond basics, optical (eye tests and glasses), and elective procedures with long-established alternative private routes. Co-payment annual caps protect against catastrophic costs — total out-of-pocket per beneficiary is capped at €300 per year for most categories, €75 for low-income earners and €0 for vulnerable groups.",
      },
      {
        heading: "Public versus private hospitals",
        body: "Cyprus has a mix of public hospitals (run by the state but accessed via GeSY) and private hospitals (most of which are also GeSY-contracted for many services, though some operate purely privately). The major public hospitals are the New Nicosia General Hospital (the country's main referral hospital — major trauma, complex surgery, the Bank of Cyprus Oncology Centre), Limassol General, Larnaca General, Paphos General, and Paralimni General. Public hospitals via GeSY are competent for most procedures but waits for non-emergency surgery can run weeks to months. The major private hospitals include Mediterranean Hospital of Cyprus (Limassol — the largest and most internationally certified), Apollonion (Nicosia and Limassol locations), Ygia Polyclinic (Limassol), Hippocrateon (Nicosia), Aretaeio (Nicosia), Iasis (Paphos and Larnaca), Evangelistria (Paphos), ECO Medical Center (Larnaca), and the German Oncology Center (Limassol). Most private hospitals contract with GeSY for many services, so you can use them with GeSY coverage; the gap is closing rapidly. Choice of hospital for elective procedures often defaults to whichever has the shortest wait and the best specialist for your specific need rather than public vs private.",
      },
      {
        heading: "Private health insurance — still useful",
        body: "Even with GeSY, many Cypriot expats keep a top-up private health insurance plan. The reasons are specific: faster access to specialists (private appointments often within days versus weeks for GeSY referrals), choice of specific consultants (popular private specialists often have shorter waits in their private practice than through GeSY), private rooms in hospitalisation (GeSY default is shared rooms in most hospitals), broader dental and optical coverage, mental health depth beyond GeSY's relatively limited programme, and international coverage for travel and medical evacuation. Comprehensive private plans for an adult under 50 typically run €60–€180 per month; family plans €200–€500 per month. Major Cypriot insurers include MetLife Cyprus, Universal Life, Pancyprian, EuroLife and CNP Cyprialife; major international insurers active in Cyprus include Bupa Global, Allianz Care, and Cigna Global. For relocators specifically, several insurers offer expat-tailored plans with annual limits of €1–€5 million and including international transfer to specialist hospitals abroad if needed. Compare carefully — coverage exclusions on pre-existing conditions, age-related premium increases, and dental sub-limits vary widely between providers.",
      },
      {
        heading: "Dental, optical and mental health",
        body: "Dental care is largely private in Cyprus and well-priced by EU standards. A standard cleaning runs €40–€80; a single filling €60–€140; a single implant €700–€1,400; orthodontics for a teenager €2,500–€5,000 over treatment. English-speaking dentists are abundant in all cities. Many Cypriot dentists trained in the UK, Germany or Greece and standards are generally high. GeSY covers basic dental for children and limited interventions for adults; private insurance often includes dental sub-limits of €300–€2,000 per year. Optical care (eye exams, glasses, contact lenses) is private only and reasonably priced — full eye exam €30–€60, mid-range glasses including lenses €150–€400. Mental health is the area where Cypriot healthcare has historically lagged. GeSY now covers basic mental health consultations and short-term therapy with referral, but specialist psychiatry, longer-term therapy and specific modalities (CBT, EMDR, family therapy) are mostly accessed privately. Private therapy in English typically runs €60–€100 per session in the major cities; specialist psychiatrists €100–€180 per consultation. The provider directory at the Cyprus Psychological Association (cpsy.org.cy) lists English-speaking professionals; expat Facebook groups are also a strong source of recommendations.",
      },
      {
        heading: "Emergencies, pharmacies and gotchas for new arrivals",
        body: "For emergencies, the EU-wide 112 number works throughout Cyprus and gives you ambulance, fire and police. Response times in the major cities are good (typically under 10 minutes for ambulances); rural village response can be longer. Emergency room visits at public hospitals are free for GeSY beneficiaries (with a €10 co-payment per visit); private hospitals will admit emergencies and bill GeSY or your insurance afterwards. Pharmacies are abundant in every city — every Cypriot neighbourhood has at least one — and a 24-hour pharmacy rota means there is always one pharmacy open in each city overnight (published in local newspapers and online). Pharmacists in Cyprus are highly trained and can dispense many medications that would require a prescription in the UK or US (antibiotics, some antihypertensives) without one for established conditions, though GeSY-funded medications require a prescription. A few gotchas for new arrivals. (1) Make sure you transfer your medical records before moving — Cypriot doctors will not have your history and key documents (immunisation records, surgical history, medication lists) are useful to have. (2) Bring at least three months of any specialist medication on arrival; sourcing identical brands locally can take time and prescription refills cannot happen before GeSY registration. (3) For chronic conditions, identify and visit your specialist in Cyprus within the first 90 days of arrival to establish care continuity. (4) The Digital Nomad Visa requires private health insurance for the first year before GeSY registration becomes available — factor this into the early-year budget. (5) GeSY has a 100% transparent online portal — log in with your Cypriot government credentials (Ariadne portal) and you can see all your records, prescriptions, referrals and billing in one place.",
      },
    ],
  },
  {
    slug: "cyprus-vs-portugal",
    title: "Cyprus vs Portugal for relocation — residency, taxes, cost and lifestyle",
    description:
      "Cyprus and Portugal are the two go-to EU relocation destinations for non-EU buyers. Compared head-to-head: visas, taxes, cost of living, climate, property markets, schools.",
    sections: [
      {
        heading: "Why people compare these two",
        body: "Cyprus and Portugal are the two destinations that come up most often in any serious EU-residency-via-investment conversation. Both are EU member states with English-speaking expat communities, warm Mediterranean climates, comparatively easy residency routes for non-EU buyers, and well-known tax-friendly regimes for new residents. The decision between them is rarely about objective facts — both are credible — and more often about lifestyle preference, family ties, and small but real differences in tax structure and property market. This guide compares the two head-to-head across the dimensions that actually matter for a relocation decision. The summary, for the impatient: Portugal has historically been more popular with families (better schools at scale, larger English-speaking expat networks, more diverse landscape and culture); Cyprus has been more popular with higher-net-worth individuals, retirees and tax-driven relocators (more aggressive non-dom tax position, lower property prices outside Limassol, simpler permanent-residency route, warmer year-round climate). Recent regime changes (Portugal narrowing the NHR programme in 2024, the Golden Visa exiting real estate in 2023) have shifted some of the calculus toward Cyprus.",
      },
      {
        heading: "Residency programmes compared",
        body: "Cyprus offers the Permanent Residency by Investment (€300,000 in new-build real estate), the Digital Nomad Visa (€3,500/month minimum income), regular work permits, and EU-citizen registration. The PR route grants permanent residency that is renewable indefinitely with as little as one visit every two years — the lightest physical presence requirement in the EU. Portugal until 2023 offered the Golden Visa via €500,000 real-estate investment, but that property route was closed in October 2023; the current Golden Visa requires €500,000 in qualifying investment funds, €250,000 in cultural heritage, or job-creation routes — meaningfully more complex than Cyprus PR. Portugal's D7 visa (passive-income retirees, €870/month minimum for a single applicant) and D8 (digital nomads, €3,480/month) are the equivalents to Cyprus's nomad visa. Portugal's residency requires more physical presence — generally 7+ days per year in the first two years and 14+ in subsequent two-year periods — to keep the permit alive, versus Cyprus's once-every-two-years. Both lead to citizenship after five years of legal residency, with the same Portuguese Citizenship by Investment route now requiring a similar timeline as Cyprus's seven-year naturalisation.",
      },
      {
        heading: "Taxes — non-dom vs NHR",
        body: "Tax is where most relocators do the maths. Cyprus's non-dom regime: 0% tax on dividends, interest and most foreign-sourced passive income for 17 of the next 20 tax years; 0% income tax on the first €19,500 of Cypriot employment; 50% income tax exemption on Cypriot employment income above €100,000 for the first 17 years; flat 12.5% corporate tax; 20% capital gains tax only on Cypriot real estate (everything else exempt). Portugal's Non-Habitual Resident (NHR) regime was sharply curtailed in 2024 — the new version (now called IFICI for new applicants from 2024+) applies only to specific high-value-added professions and offers a narrower set of benefits than the previous NHR, with a 20% flat rate on covered Portuguese income for 10 years and varying treatment of foreign income. Pre-2024 NHR applicants remain on the old regime: 10-year preferential treatment with 10% on foreign-source pensions and various exemptions on foreign income. Verdict: Cyprus has the more generous and longer-lasting tax position for new applicants in 2026, particularly for individuals whose income is primarily dividends, interest or business profits. Portugal still has appeal for specific professional categories under the new IFICI regime, and for buyers prioritising lifestyle over tax.",
      },
      {
        heading: "Cost of living and property",
        body: "Property in Cyprus is meaningfully cheaper than Portugal in equivalent-tier locations. A two-bedroom new-build apartment 10 minutes from the beach: Larnaca or Paphos €230,000–€350,000; comparable Algarve or Setúbal €350,000–€500,000; comparable Lisbon outer suburbs €450,000–€700,000. Limassol is the closest Cyprus equivalent to Lisbon in pricing, and even there is generally 10–25% cheaper than Lisbon for tower apartments. Day-to-day cost of living: groceries, restaurants and services are similar in both countries (Lisbon and Limassol are roughly comparable; smaller cities in either country are cheaper); utilities are higher in Cyprus (electricity is a state monopoly and AC is more universally used); healthcare costs are comparable under both public systems (GeSY vs SNS). The hidden cost differential is property tax — Portugal still levies IMI (a municipal property tax of 0.3%–0.8% on assessed value annually) while Cyprus abolished IPT in 2017 and has only small municipal taxes. On a €400,000 property, Portuguese IMI runs €1,200–€3,200/year; Cyprus equivalent might be €400–€800. Over 10 years of ownership that's €8,000–€32,000 in Portugal versus €4,000–€8,000 in Cyprus.",
      },
      {
        heading: "Climate, lifestyle and family logistics",
        body: "Both countries are Mediterranean, but the experience is meaningfully different. Cyprus is hotter, drier and sunnier — Limassol gets 340+ sunny days per year and summer temperatures regularly hit 35–38 °C; Lisbon gets around 290 sunny days and rarely exceeds 32 °C. Cyprus winters are mild on the coast (15–18 °C daytime); Portuguese coastal winters are similar in temperature but wetter. For families with children, Portugal has more depth in international schooling and a larger English-speaking expat network, particularly in Lisbon, Cascais and the Algarve; Cyprus's international schools are good but concentrated in three cities (Limassol, Nicosia, Paphos) and the SE coast schooling situation is meaningfully thinner. For retirees, Cyprus's English-speaking medical community is unusually large for its size — many doctors trained in the UK — and the British expat community is well-established in Paphos and Larnaca. Lifestyle: Portugal has more landscape diversity (mountains, surf coast, Lisbon culture, Porto wine country), Cyprus has more concentrated beach quality and warmer sea later in the year.",
      },
      {
        heading: "Verdict — which fits which buyer",
        body: "If you are a high-net-worth individual with dividend, interest or business income, retiring or semi-retiring, and tax optimisation is the headline driver: Cyprus wins on the non-dom regime, the longer 17-year tax horizon, and the lighter physical-presence requirement. If you are a remote worker on €4,000–€10,000/month who wants the strongest lifestyle and family infrastructure within the EU: Portugal still has the edge on schooling depth, English-speaking expat community size, and landscape diversity, though Cyprus is closing the gap. If you are buying purely for residency on a budget close to €300,000: Cyprus is now the more accessible route since Portugal closed real-estate Golden Visa eligibility in 2023; Portugal's current investment routes start at €250,000 (cultural heritage) or €500,000 (qualifying investment funds), with neither giving you a property to live in. If you want maximum sun and warm sea for the longest season: Cyprus, by a wide margin. If you want easier flights to and from North America: Portugal has more direct US flights than Cyprus. Both countries have road-tested expat ecosystems, both lead to EU citizenship in five years, and both work — the choice is rarely between 'right' and 'wrong', more between matching your priorities to the differential. Many relocators visit both before committing; that's a reasonable strategy.",
      },
    ],
  },
  {
    slug: "relocation-checklist",
    title: "Cyprus relocation checklist — what to do in the 6 months before and after",
    description:
      "A practical week-by-week checklist for relocating to Cyprus — from the six-month planning window through your first 90 days on the island.",
    sections: [
      {
        heading: "The shape of a Cyprus relocation",
        body: "Relocating to Cyprus is a 6–12 month project from decision to settled. The actual move is the easy part — flights and shipping; the hard parts are residency, schooling, property and tax structuring, and getting all of them sequenced correctly. This checklist breaks the project into five phases: 6+ months out (research and decision), 3–6 months out (residency and property), 1–3 months out (moving logistics), the first month on the island, and the first 90 days settling in. Most relocators get 50–70% of this right and either move into temporary accommodation while they sort the rest, or quietly rebuild a few steps after arrival. That's normal. The checklist below is the optimum sequence; treat it as a guide, not a deadline.",
      },
      {
        heading: "6+ months out — research and decision",
        body: "Visit Cyprus twice, at least once in low season (November–February) and once in high season (July–August). Shortlist your target region — Limassol for business and tech jobs; Paphos or Larnaca for value, climate and retirement; Nicosia for academia, government and family infrastructure; the SE coast for beach lifestyle. Confirm your residency route — Permanent Residency by Investment (€300,000 in new-build) for non-EU buyers; Digital Nomad Visa for remote workers earning €3,500+/month; EU registration if you hold an EU passport. Talk to a Cyprus tax adviser about your specific situation — non-dom registration is mechanical but the 60-day-rule requires substance, and your prior-country exit tax position needs to be planned, not improvised. Identify your school preference if you have school-age children — international school admissions for the top schools (Heritage Limassol, English School Nicosia) start 9–12 months ahead, and waitlists for senior years are real. Open conversations with two or three Cypriot lawyers; pick one to engage formally once your purchase decision is made. Start collecting documents: apostilled birth and marriage certificates, criminal records check from your home country (Cypriot requirement for residency), bank statements for the last 12 months.",
      },
      {
        heading: "3–6 months out — residency and property",
        body: "Engage a Cypriot lawyer formally (€1,500–€3,000 retainer typical). Apply for your residency permit (PR application, Digital Nomad Visa application, or EU registration as appropriate). Visit Cyprus a third time to view shortlisted properties — at least 8–10 viewings across your target region. Make an offer on the property you want and sign a reservation agreement (€2,000–€10,000 fee, refundable if due diligence finds problems). Your lawyer runs Land Registry searches, verifies the developer's title and unencumbered ownership, and reviews the technical specifications. If you are using a Cypriot mortgage, apply now — approval takes 6–10 weeks. Sign the Sale and Purchase Agreement (SPA) and pay the initial deposit (typically 20–30% of purchase price). Your lawyer stamps the SPA at the Tax Department and files it at the Land Registry within 30 days. Apply for your Cyprus Tax Identification Code (TIC) if you do not already have one — needed for property, bank and tax purposes. Open a Cypriot bank account in person at a branch (you cannot do this remotely from most countries) — typical providers: Bank of Cyprus, Hellenic, Eurobank, Astrobank.",
      },
      {
        heading: "1–3 months out — moving logistics",
        body: "Book your relocation shipping if you're moving belongings. A 20-foot container from London or Hamburg to Limassol port runs €4,500–€7,000 and takes 4–6 weeks; from Israel €2,500–€4,000 and 2–3 weeks. Customs duty applies on shipments arriving more than 12 months after your residency permit start date — confirm your shipping timing with your lawyer. Cancel or transfer your home-country: tax registration (file an exit return where applicable), driver's licence (Cyprus accepts EU/UK licences for a year before you must convert), insurances, subscriptions, utilities. Notify your home-country tax authority of your move date. Book flights and an arrival window for the family. Arrange temporary accommodation in Cyprus if your purchase property is not ready — a furnished 2-bedroom Airbnb runs €1,800–€3,500/month, hotels €100–€250/night for medium-stay. Notify schools of arrival date for children; complete final admission paperwork. Plan your first-month spend: budget €5,000–€10,000 in cash float for set-up costs (car, furniture, deposits, etc).",
      },
      {
        heading: "Your first week in Cyprus",
        body: "Day 1–3: Pick up the keys from your lawyer or arrive at temporary accommodation. Get a Cypriot mobile number — visit a Cyprus Telecom, Epic, Cablenet or PrimeTel store with passport and residence permit; expect €20–€40 for SIM activation. Day 3–5: Visit the Civil Registry (immigration) to complete in-country residency formalities and get your residency card if not received by mail. Visit the Tax Department in person to confirm your TIC and your Cyprus tax residency status. Day 5–7: Apply for GeSY healthcare registration online once your social insurance number is issued; select your Personal Doctor in your area. Sort utilities: electricity (Cyprus Electricity Authority — EAC — visit a branch with your residency card and property deed/lease), water (your local municipality), internet (CyTA, Epic, Cablenet — 1 Gbps fibre €40–€60/month). Get a Cypriot driver's licence if your prior licence isn't accepted long-term — visit the Department of Road Transport with your prior licence, two passport photos and €40. Book the children's first school day; visit the school to drop off any final paperwork.",
      },
      {
        heading: "Your first month",
        body: "Buy or lease a car — used cars under €15,000 from Cypriot dealers in any major city; new cars carry significant registration tax. Get Cypriot car insurance (€500–€1,200/year typical depending on driver age and history). Set up direct debits with EAC for electricity, with the water board, with your management committee for common charges if you bought in a development. Register with the local municipality for refuse and municipal tax. Find a private dentist, GP and any specialists you need long-term — book the first appointment within the first month to establish continuity of care. Open a Cyprus tax residency file with your accountant if you are claiming non-dom — they will need your travel records, prior-country tax confirmation, and proof of residence. Get the children settled into school (most international schools have a buddy system for new arrivals). Join the relevant Cyprus expat Facebook groups — the practical knowledge density is high and the recommendations on dentists, mechanics, plumbers, and Greek tutors are gold.",
      },
      {
        heading: "Your first 90 days",
        body: "Activate your Cyprus tax residency through your accountant — the formal non-dom declaration must be made in your first tax return. Begin building Cyprus economic substance for the 60-day-rule if applicable: open a Cyprus company if needed, sign a Cyprus rental or take possession of your purchase, establish day-to-day expenses on Cypriot bank cards. If you are claiming the reduced 5% VAT rate on your property purchase, your lawyer files the application to the Tax Department — the refund of the VAT difference can take 12–24 months. Start Greek lessons — a beginner course (~€500–€900 for 60 hours at a private language school) opens many social and bureaucratic doors. Register children for any after-school activities (sports clubs, music, art) — Cyprus has surprisingly developed extracurricular infrastructure in all major cities. If you plan to work locally, this is when you start the job search or company-formation process; if you are on Digital Nomad Visa, this is when you re-confirm your remote employer's structure works with Cyprus tax. Visit each of the major regions you didn't shortlist — Cyprus is small enough that you can do a full day-trip to any region, and seeing them anew once you're settled gives you a much better picture of where to spend weekends and where you'd consider moving in five years.",
      },
      {
        heading: "Ongoing — the first year and beyond",
        body: "Cyprus rewards integration in ways that are hard to predict in the planning phase. Within the first year, most relocators report three patterns. First, they make most of their Cypriot friends through their children's schools, their gym or padel club, or the developer's owner community for their building — not through dedicated 'expat meetups', which exist but are limited. Second, they spend dramatically less than they budgeted on entertainment (the lifestyle is more about long lunches, beach Sundays and home-cooked meze than expensive nights out) and more than they budgeted on travel (Cyprus is a 2–4 hour flight to most European capitals, and weekend trips become easy). Third, they discover that Cyprus's small size is its quiet superpower — you can be at any beach, any mountain village, any city centre, within 90 minutes of your front door. After the first year, most relocators either deeply settle (extend the property, take Cypriot citizenship application after five years, send children to Cypriot university) or quietly realise the climate or pace doesn't suit them and move on. The decision usually clarifies in months 8–14. Whichever way it lands, the relocation infrastructure on the island — lawyers, accountants, schools, hospitals, services — is mature enough that the move is reversible without much friction. That, more than anything else, is what makes Cyprus a comparatively low-risk relocation choice.",
      },
    ],
  },
];

export function guideBySlug(slug: string): GuideInfo | undefined {
  return GUIDES.find((g) => g.slug === slug);
}
