/**
 * Guides batch G1 — housing and immigration guides.
 * Consumed by the same guide-rendering infrastructure as lib/guides.ts.
 *
 * Disclaimer: this is general information, not legal or tax advice. Specific
 * thresholds, deadlines and fees change frequently — always verify with the
 * Cyprus Land Registry, Civil Registry & Migration Department, and a local
 * lawyer or accountant before acting.
 */

import type { GuideInfo } from "./guides";

export const GUIDES_G1: ReadonlyArray<GuideInfo> = [
  {
    slug: "title-deed-status-guide",
    title: "Cyprus Title Deed Guide — Protecting Yourself as a Foreign Buyer",
    description:
      "How to check title deed status at the Land Registry, what 'subject to mortgage' means in practice, and the contract protections that matter most. Prices and rules change — verify with official Cyprus sources before acting.",
    sections: [
      {
        heading: "The legacy backlog — why title deeds are still a major issue",
        body: "Cyprus accumulated a well-documented title deed backlog over the 1990s and 2000s: developers built properties on bank-mortgaged land, sold the units to buyers, and then — in many cases — failed to transfer the deeds once construction completed. At its peak, the backlog exceeded 130,000 properties. Legislative reforms from 2015 onwards (Law 139(I)/2015 and subsequent amendments) introduced a fast-track transfer mechanism allowing buyers to transfer titles even when an outstanding developer mortgage exists, provided the buyer pays the transfer fees. As of 2025, the backlog is materially smaller, but legacy-stock properties built before 2010 still commonly lack clear individual title deeds, and buyers of resale units in older complexes are still frequently purchasing properties where the communal or individual title deed has never been separated from the original plot title. Always treat a title deed search as mandatory due diligence, not optional.",
      },
      {
        heading: "How to search the Land Registry",
        body: "The Cyprus Department of Lands and Surveys (DLS) maintains the authoritative register of all immovable property. You or your lawyer can search the registry in person at any district DLS office (Limassol, Paphos, Larnaca, Nicosia, Famagusta), and an online portal (dls.moi.gov.cy) provides limited property information for registered users. For a complete search, your lawyer requests an official certificate of registration (Certificate of Encumbrances), which states the current registered owner, any mortgages, any charges, any restrictions, and whether the title deed is an individual title or still a plot title shared with other units. The certificate costs approximately €20–€50 and is issued within a few working days. Critically, confirm that the title being sold matches the physical unit — plot boundaries and apartment numbers on the title must correspond to the unit on the ground. Discrepancies are more common than buyers expect, particularly in older complexes.",
      },
      {
        heading: "What 'subject to mortgage' means",
        body: "When a property is 'subject to mortgage', it means the land or building carries a charge in favour of a lender — typically the developer's construction bank. Buying a property with an uncleared developer mortgage creates real risk: if the developer defaults, the bank can theoretically enforce against the mortgaged asset, including your unit. The 2015 fast-track law provides a mechanism to transfer title despite an outstanding mortgage, but only if the buyer applies at the DLS, the transfer fees are paid, and the bank consents or the procedure is followed correctly. Do not rely on the developer's verbal assurance that the mortgage 'will be cleared soon'. Your contract should explicitly require the developer to clear any mortgage on your specific unit before completion, or alternatively, that your purchase price funds are applied directly to clearing the mortgage before transfer. Your lawyer should also confirm that no additional charges have been registered after the property was sold to you.",
      },
      {
        heading: "Contract protections to insist on",
        body: "The Contract of Sale must be deposited with the DLS within 60 days of signing — this is a legal requirement under the Immovable Property (Transfer and Mortgage) Law and is your primary protection as a buyer. A deposited contract creates a charge in your favour and prevents the developer from mortgaging or reselling the property to someone else. Without a deposited contract, you have no priority. Beyond this, insist on: a specific completion date with liquidated damages (typically 0.5–1% of purchase price per month of delay) for any delay beyond that date; a clause requiring the developer to apply for and deliver the individual title deed within a specified period after completion (36–60 months is common; push for less); a retention mechanism allowing you to withhold 5–10% of the purchase price until the individual title deed is in your name; and a provision that the purchase price funds are held in an escrow or notarised account until key documents are delivered. A good Cyprus property lawyer will have standard clauses for all of these; the negotiation is about getting the developer to accept them.",
      },
      {
        heading: "The immovable property transfer process",
        body: "Once the individual title deed exists and the purchase price is paid, the formal transfer takes place at the DLS. Both buyer and seller (or their lawyers under power of attorney) attend. Transfer fees are levied on the current market value of the property at rates of 3% on the first €85,000, 5% on the next €85,001–€170,000, and 8% on amounts above €170,000, though reduced rates apply for purchases of new build properties from developers (50% discount on transfer fees has historically applied, and VAT-registered new builds may transfer fee-free in certain circumstances). Stamp duty applies to the contract: 0.15% on the first €170,860, 0.2% above that, paid within 30 days of signing. Title deed transfer typically takes 1–4 weeks once the application is lodged and all documents are in order. After transfer, you receive a title deed in your name from the DLS — this is the document that confirms you are the legal registered owner. Store it securely; lost title deeds require a court process to replace.",
      },
    ],
  },
  {
    slug: "off-plan-buying-guide",
    title: "Buying Off-Plan in Cyprus — Due Diligence Checklist",
    description:
      "Developer vetting, escrow requirements, planning documents to demand, title deed timelines, and the most common completion delay scenarios. Prices and rules change — verify with official Cyprus sources before acting.",
    sections: [
      {
        heading: "Vetting the developer before you sign anything",
        body: "The developer's track record is the single most important variable in an off-plan purchase — more than the location, the floor plan, or the price. Cyprus has no mandatory developer licensing in the way some jurisdictions do, but you can verify a development's legitimacy through several sources. First, confirm the Department of Lands and Surveys has issued a building permit and, for larger schemes, a planning permission for the specific development you are buying into. Request copies of both documents from the developer; if they refuse or stall, that is a significant warning sign. Second, search the developer's corporate registry record at the Registrar of Companies (mygov.cy) — check when the company was incorporated, who the directors are, and whether the company has filed accounts. Third, look at the developer's completed projects: visit or drive past buildings they have delivered in the past five years. Talk to residents where possible. A developer who delivered their last project three years late and never transferred title deeds has told you everything you need to know.",
      },
      {
        heading: "Escrow requirements and protecting your deposit",
        body: "Cyprus law does not currently mandate escrow for off-plan purchases, which means your deposit and stage payments are paid directly to the developer and are at risk if the developer becomes insolvent during construction. This is the most significant financial risk in off-plan buying in Cyprus, and it is one that most buyers underestimate until a project stalls. Practical protections you can negotiate: require that stage payments are held in a dedicated client account by the developer's lawyer (not the developer's operating account) until each milestone is certified by an independent architect; negotiate a bank guarantee from the developer's construction lender, which releases the deposit back to you if the project is not completed by a longstop date; insist on deposit insurance where available (some larger developers offer this through insurance partners). If the developer will not agree to any form of deposit protection, price that risk into your decision — or walk away.",
      },
      {
        heading: "Planning permission documents to demand",
        body: "Before you sign, obtain certified copies (not photocopies) of: the Town Planning Permit (issued by the local municipality or district planning authority), which defines what can be built and the permitted density; the Building Permit (issued by the DLS), which authorises the specific construction; and the Title of Registration for the land, confirming the developer legally owns or has the right to build on the plot. In some cases the developer will be building on land they own outright; in others, the land is held by a related entity or is still being purchased under a vendor mortgage. The latter creates title deed risk for you. Your lawyer should trace the ownership chain back to a clean title — if they cannot, the risk profile rises sharply. Also request a copy of the architectural plans (floor plan, elevations) that are annexed to the planning permission. These define the legal dimensions of what you are buying; any deviation at delivery gives you a claim against the developer.",
      },
      {
        heading: "Title deed timeline for new builds",
        body: "For a new build purchased off-plan and completed today, the typical timeline from completion to individual title deed is 3–5 years. The process is: developer applies for final planning approval (Certificate of Final Approval) after construction completes → local planning authority inspects and issues certificate (typically 6–18 months) → developer applies to DLS to subdivide the plot and register individual unit titles (typically 1–3 years) → individual title deeds issued to each unit. Delays occur at almost every step. The developer may not apply promptly if they are managing cash flow from multiple projects; the planning authority may request remediation of deviations from the original permit; the DLS subdivision process can stall if the developer's mortgage has not been cleared. Contract clauses requiring the developer to apply for each step within defined timeframes, with financial penalties for delay, are the only practical protection. Some buyers in well-structured contracts have received their title deeds within 18 months of completion; others are still waiting after eight years.",
      },
      {
        heading: "Common completion delay scenarios",
        body: "Understanding why Cyprus off-plan projects run late helps you build appropriate contractual protections. The most common causes: financing gaps, where the developer's construction loan is drawn against sales revenue and slow sales on other units in the project pauses construction on yours; subcontractor problems, particularly for fit-out trades (tiling, plumbing, electrical) where the island has chronic capacity constraints in peak development cycles; material price escalation, which has affected nearly every Cyprus project started since 2021 given the construction inflation in the post-COVID period; and planning deviation issues, where the developer built something that does not exactly match the approved plans and must either apply for an amendment or remediate. Force majeure clauses in Cyprus property contracts are broadly drafted and developers use them liberally; your counter is to define a longstop date after which you can withdraw and recover your deposit regardless of the cause of delay. Typical longstop is 24 months beyond the contractual completion date. Negotiate this before you sign.",
      },
    ],
  },
  {
    slug: "rental-transition-guide",
    title: "Moving from Short-Term to Long-Term Rental in Cyprus",
    description:
      "Standard lease terms, typical deposit amounts, what landlords require from foreign tenants, furnished versus unfurnished market realities, breaking a lease, and rent increase rules.",
    sections: [
      {
        heading: "How the long-term rental market actually works",
        body: "Cyprus's long-term rental market is largely informal by northern European standards: most landlords are private individuals, there is no mandatory deposit protection scheme, and lease terms are negotiated individually. Standard leases run for one or two years, with two-year leases increasingly common in Limassol (where demand consistently exceeds supply) and one-year leases more common in Paphos, Larnaca and Nicosia. Month-to-month arrangements are possible but uncommon for new tenants without an existing relationship. Most leases are signed in Greek, although English versions or bilingual contracts are common in Limassol where the international tenant population is largest. Have any lease you sign reviewed by a Cypriot lawyer before you commit — the legal interpretation of a Greek-language clause is what matters in a dispute, not your translation. Standard legal review of a residential lease costs €100–€250.",
      },
      {
        heading: "Deposits, upfront payments, and what landlords want",
        body: "Standard deposits in Cyprus are one to two months' rent, held by the landlord directly with no mandatory protection scheme. Two months is becoming the norm in Limassol for high-demand properties; one month remains standard in other cities. You will typically also pay the first month's rent upfront at signing. For foreign tenants, landlords commonly also request: proof of residency (ARC or Yellow Slip), proof of income (payslips, bank statements, or a letter from an employer), and sometimes references from a previous landlord. Landlords cannot legally discriminate on nationality, but in practice, a foreign tenant with clean documentation moves much faster than one who arrives with nothing. Landlords are also increasingly asking for a guarantor or additional deposit months (three months' rent deposit is common for tenants who are self-employed or recently arrived). Negotiate, but understand the market — in high-demand areas landlords have multiple applications and will take the lowest-friction tenant.",
      },
      {
        heading: "Furnished versus unfurnished",
        body: "The Cyprus rental market is predominantly furnished for international tenants, which reflects the large relocator and expat population accustomed to furnished accommodation. A 'furnished' Cyprus apartment typically includes white goods (fridge, washing machine, oven), sofas, beds, wardrobes, and basic kitchen equipment. Quality varies enormously: a furnished apartment in an older building may have mismatched furniture from the 1990s, while a modern furnished apartment will have new furniture and appliances. Always conduct a detailed inventory inspection at move-in and document the condition of every item with photographs — this is your protection against unfair deductions from your deposit at move-out. Unfurnished apartments are available (more commonly in the local Cypriot market) and are generally €100–€200 per month cheaper for equivalent space, but you need to budget for furnishing costs (€3,000–€8,000 for a basic two-bedroom setup from stores like IKEA in Limassol or local furniture retailers).",
      },
      {
        heading: "Breaking a lease",
        body: "Breaking a fixed-term lease in Cyprus before the end date generally requires three months' written notice and may entail a financial penalty — typically one to two months' additional rent — unless the lease contains a specific early-termination clause. The legal position is that a fixed-term lease is binding on both parties and the landlord can seek to hold you to the full rent for the remainder of the term. In practice, most landlords will negotiate, particularly if you are leaving before the halfway point and they can re-let the property quickly in a strong market. The cleanest approach is to include a break clause in your lease at signing: a right to terminate with two to three months' written notice after the first six months, with no penalty beyond those notice months. This is not unusual for international tenants and many landlords accept it. If your lease lacks this clause and you need to leave early, document any problems with the property (maintenance failures, noise, structural issues) contemporaneously — these create leverage in negotiation.",
      },
      {
        heading: "Rent increase rules and lease renewal",
        body: "Cyprus has limited rent control regulation compared to many EU countries. For existing contracts, the landlord cannot increase rent during the fixed term unless the lease explicitly provides for it. At renewal, the landlord can propose any new rent, and you can accept, renegotiate, or leave. In Limassol, annual rent increases of 8–15% have been common since 2022 due to demand pressure from the influx of relocated companies and individuals. In other cities, increases of 5–10% at renewal are typical. There is no statutory cap on rent increases for new contracts. If your landlord proposes an increase you consider unreasonable, the leverage you have is leaving: the time and cost of finding and qualifying a new tenant (typically 4–8 weeks void, one month's rent in agency fees) is a real cost to the landlord. The practical outcome in most renewals is a negotiated increase somewhere between the landlord's ask and your counter. Longer original lease terms (two years instead of one) can provide rent stability — insist on including the renewal rent or a cap on the increase in the original lease if you can.",
      },
    ],
  },
  {
    slug: "digital-nomad-visa-guide",
    title: "Cyprus Digital Nomad Visa — Complete Step-by-Step Guide (2026)",
    description:
      "Eligibility, required documents, the application portal, processing times, renewal up to three years, and family extension options. Prices and rules change — verify with official Cyprus sources before acting.",
    sections: [
      {
        heading: "Who qualifies for the Cyprus Digital Nomad Visa",
        body: "The Cyprus Digital Nomad Visa (DNV) is designed exclusively for non-EU nationals who work remotely — either as employees of a foreign company or as freelancers serving clients outside Cyprus. EU nationals do not need a DNV; they register as EU residents under the standard MEU1 process. The key eligibility criteria: you must be a non-EU national with a valid passport; your employer or your clients must be based outside Cyprus; you must not have Cypriot employment income (working for a Cyprus-based company disqualifies you unless you hold a separate work permit); and you must earn at least €3,500 per month net after all deductions. The €3,500 figure is the minimum for a single applicant; it increases by 20% (to €4,200 net) if you include a spouse, and by 15% per dependent child beyond that. These figures are minimums — in practice, applications with income comfortably above the threshold proceed faster and with fewer requests for additional documentation.",
      },
      {
        heading: "Required documents",
        body: "The DNV application requires the following documents, all in English or accompanied by certified translations: a completed application form (available on crmd.moi.gov.cy); a valid passport with at least 12 months remaining validity; two recent passport-size photographs; proof of remote income — for employees, an employment contract and the last three months of payslips and bank statements; for freelancers, service agreements or contracts with foreign clients and three to six months of bank statements showing consistent income deposits; a clean criminal record certificate from your home country (apostilled or legalised for Cyprus); health insurance valid in Cyprus with at least €30,000 coverage (public GeSY registration does not satisfy this — you need a private policy in place before the application); proof of accommodation in Cyprus (signed rental agreement or property purchase documentation); and a cover letter explaining your work arrangement and why you qualify. For family members, add marriage certificate (apostilled), birth certificates for children, and proof that the primary applicant's income meets the family threshold. All personal status documents require apostille or legalisation; check the requirements for your country of issue.",
      },
      {
        heading: "Applying via the CRMD portal",
        body: "Applications are submitted through the Civil Registry and Migration Department (CRMD) portal at crmd.moi.gov.cy. The process: create an account on the portal, select 'Visitor/Temporary Residence — Digital Nomad Visa', complete the online form, and upload all supporting documents. Applications can also be submitted in person at a CRMD district office — there are offices in Nicosia, Limassol, Larnaca, Paphos and Famagusta. In-person submission is recommended for first-time applicants as the officer can flag missing documents on the spot, preventing the need for a back-and-forth by post. The application fee as of 2025 is approximately €70 per adult applicant, payable at the CRMD office or through the portal. Submit from outside Cyprus if you have not yet entered, or within Cyprus on a valid visa (tourist entry is acceptable for initial application, but confirm current procedure with CRMD as this has changed previously).",
      },
      {
        heading: "Processing time and what to expect",
        body: "The official CRMD processing target for DNV applications is 5–8 weeks from submission of a complete file. In practice, 6–10 weeks is more realistic, with applications submitted in peak periods (September–November, when many families plan relocations for the start of the school year) sometimes taking 12 weeks or more. Incomplete applications — the most common cause of delay — are returned or suspended with a request for additional documents, resetting the clock. Once approved, you are notified by email and attend a CRMD office appointment to be biometrically enrolled (fingerprints and photo). The ARC (Alien Registration Certificate) is then produced — typically 2–4 weeks after biometric enrollment. During the wait between approval and ARC issuance, CRMD issues a certificate of application that serves as interim documentation. If your application is refused, you receive a written decision explaining the grounds, and you have the right to appeal or reapply with additional documentation.",
      },
      {
        heading: "Renewal, three-year maximum, and family rights",
        body: "The DNV is initially issued for one year. It is renewable for up to a further two years (total three years), provided you continue to meet all eligibility criteria: income still meets the threshold, you are still working remotely for non-Cyprus employers or clients, your health insurance remains valid, and you maintain accommodation in Cyprus. Renewal applications should be submitted at least two months before expiry. After the three-year maximum, you must either leave, switch to a different permit type (Permanent Residency by Investment, employment permit, or EU long-term residence if you have accumulated five years of legal residence through different permit types), or re-apply for the DNV after a qualifying absence period. Family members (spouse and unmarried financially dependent children up to 18, or up to 25 if in full-time education) are granted dependent residency status under the primary applicant's DNV. Dependents receive their own ARCs and have the right to live in Cyprus, access education and healthcare through GeSY, but cannot take employment in Cyprus unless they hold a separate work permit.",
      },
    ],
  },
  {
    slug: "family-reunification-guide",
    title: "Bringing Your Family to Cyprus — Reunification and Dependent Visas",
    description:
      "How the primary visa holder brings a spouse, children, and parents to Cyprus — documents by dependent type, income thresholds, processing timelines, and rights granted to dependents. Prices and rules change — verify with official Cyprus sources before acting.",
    sections: [
      {
        heading: "The framework: which permit type determines the options",
        body: "The family reunification rules in Cyprus differ significantly depending on what permit the primary applicant holds. EU citizens exercising free movement rights bring family members (EU or non-EU) under the EU Citizens Directive, which gives broad rights and a relatively straightforward process. Non-EU primary applicants — holders of Digital Nomad Visas, Permanent Residency permits, employment permits, or company-based category permits — bring dependents under the Aliens and Immigration Regulations, which are more document-intensive and have stricter income thresholds. The rights granted to dependents (whether they can work, attend school, access healthcare) depend on both the permit category and the dependent's relationship to the primary applicant. Before starting the process, confirm precisely what your primary permit allows — some older-format permits did not explicitly permit dependent applications and required an amendment before dependents could be added.",
      },
      {
        heading: "Spouse reunification: documents and process",
        body: "For a non-EU primary permit holder bringing a non-EU spouse: you need the original marriage certificate, apostilled and officially translated into Greek or English; a passport photograph for the spouse; the spouse's valid passport with at least 12 months remaining; proof that the primary permit is current and valid; proof of shared accommodation in Cyprus (a lease in both names is cleanest, or a landlord declaration that the spouse will reside at the address); health insurance valid in Cyprus for the spouse; and the primary applicant's bank statements for the past three to six months confirming the income threshold is met including the spousal uplift (typically 20% above the base threshold for the primary permit category). For DNV holders, this means €4,200 net per month as of 2025. The joint application is submitted at the CRMD; both applicants should attend in person when possible. Processing mirrors the primary permit timeline: 6–10 weeks for clean, complete files.",
      },
      {
        heading: "Bringing children: documents by dependent type",
        body: "Unmarried children under 18 (or under 25 if in full-time education and financially dependent) qualify as dependents for most permit categories. Required documents for each child: original birth certificate apostilled, official translation, valid passport, two passport photographs, proof of school enrollment for children over 6 (a Cyprus school enrollment letter works), health insurance covering the child, and the primary applicant's income evidence confirming the per-child threshold is met (typically 15% above the base income minimum per additional child). For children over 18 who are students, you also need a university enrollment letter confirming full-time study. Adopted children require the adoption court order apostilled. Step-children require the marriage certificate linking the applicant to the child's parent as well as the child's birth certificate. A Cypriot lawyer can confirm the precise documentary requirements for non-standard family structures, which vary based on the nationality and documentation practices of the country of origin.",
      },
      {
        heading: "Parents and other family members",
        body: "The rules for bringing parents and extended family are significantly more restrictive than for spouses and children. Parents of EU citizens may accompany under the EU Directive if they are financially dependent on the EU citizen. For non-EU primary permit holders, parents are generally classified as 'other dependent relatives' and require an exceptional circumstances application to the CRMD — this is a discretionary process, not a guaranteed right. For a successful parent application, you must demonstrate that the parent is genuinely financially dependent on you (no independent income, pension, or property in their home country that can support them), and that there are compelling family unity reasons. Income threshold for parent dependents is assessed on a case-by-case basis but is typically an additional 20–30% above the base minimum. Processing for parent applications takes longer (12–20 weeks is not unusual) and approval rates are lower. Other extended family members (siblings, aunts, uncles, adult children with their own income) are generally not eligible under family reunification and must apply for their own permits independently.",
      },
      {
        heading: "Rights granted to dependents and practical outcomes",
        body: "What dependents can do in Cyprus once their ARC is issued depends on the primary permit category. Under Digital Nomad Visa: dependents can live in Cyprus, attend Cypriot schools and universities, and access GeSY healthcare, but cannot take employment in Cyprus. If a dependent spouse wants to work, they must apply for a separate employment permit or DNV in their own name. Under Permanent Residency by Investment: dependents receive the PR permit and can live indefinitely in Cyprus; spouses may work subject to a separate work permit application. Under EU residency (primary applicant is EU citizen): non-EU family members receive a Residence Card of a Family Member of a Union Citizen, which grants the right to work in Cyprus, access social services, and travel freely within the Schengen area. Children's schooling: Cypriot public schools are free and accept children of all legal residents. Private international schools (typically €5,000–€18,000 per year) do not require a specific permit type. One practical note: the child's ARC should be obtained before the school year starts if possible — some schools require it for enrollment, though most will accept a pending application receipt as interim documentation.",
      },
    ],
  },
  {
    slug: "permanent-residency-5year",
    title: "Cyprus Permanent Residency After 5 Years — Requirements and Process",
    description:
      "The qualifying residency period, points criteria, language requirements, application documents, timeline, and how PR rights compare to citizenship. Prices and rules change — verify with official Cyprus sources before acting.",
    sections: [
      {
        heading: "Two routes to permanent residency",
        body: "It is important to distinguish between two different types of 'permanent residency' in Cyprus. The first is the Permanent Residency by Investment (sometimes called the Category F or Regulation 6(2) permit), which is available to non-EU nationals who make a qualifying property investment of at least €300,000 and does not require any prior period of residence. The second — the subject of this guide — is the Long-Term Resident permit acquired through five years of continuous legal residence, available under EU Directive 2003/109/EC as implemented by the Aliens and Immigration Law of Cyprus. The two are legally distinct documents with different rights, different application processes, and different costs. This guide covers the five-year route. If you hold the investment-based PR, the contents of this guide still apply to you if you later want to convert to the long-term resident status that accrues from physical presence.",
      },
      {
        heading: "The qualifying residency requirement",
        body: "To apply for the Long-Term Resident permit under the five-year route, you must have held continuous legal residence in Cyprus for at least five years immediately before the application date. 'Continuous' means you have not been absent from Cyprus for more than six consecutive months at any one time, and your absences in total have not exceeded ten months across the entire five-year qualifying period. Temporary absences for serious reasons (medical treatment, study, or professional posting abroad) may not break continuity but must be evidenced. The five years must be as a legal resident — tourist entries, visa waiver entries, and short visitor stays do not count. Each year of the qualifying period must be documented with a valid residence permit or registration certificate for that period. If you held several different permit types over the five years (for example, two years on a Digital Nomad Visa followed by three years on an employment permit), each must have been valid and uninterrupted — a gap in legal status, even for a few weeks, can technically break the qualifying period.",
      },
      {
        heading: "Language requirement and the points system",
        body: "Cyprus does not operate a points-based immigration system in the UK or Canadian sense. The Long-Term Resident application does not require a formal points calculation. What it does require is: sufficient resources (income or assets) to support yourself and your dependents without recourse to the social assistance system, and integration evidence, which in practice means providing documentation of your ties to Cyprus — employment, property ownership, school enrollment for children, tax filings, and social contributions. A Greek language test is not currently mandatory for the Long-Term Resident permit under EU Directive 2003/109 — this is different from naturalisation (citizenship), where Greek language proficiency at B1 level is required. However, applicants are encouraged to demonstrate social integration, and language evidence strengthens an application. The income threshold assessed for self-sufficiency is approximately €8,000 per year for the primary applicant plus €2,000 per dependent, though CRMD has assessed these figures inconsistently across applications. Work with a lawyer to confirm the current assessment standard for your profile.",
      },
      {
        heading: "Application documents",
        body: "The Long-Term Resident application is submitted to the CRMD with: a completed form M68; a valid passport; the current ARC; evidence of five years of uninterrupted legal residence (ARCs, registration certificates, and permit renewal documents for each year); evidence of sufficient resources — six months of bank statements and either payslips or company accounts for self-employed applicants; evidence of health insurance or GeSY registration; proof of accommodation in Cyprus (current lease or property title); a clean criminal record certificate issued within six months of the application date, apostilled; and a tax clearance certificate confirming no outstanding tax liabilities. For applicants who have had multiple permit types, bring the full documentation chain for each permit. The CRMD processes the application and conducts security checks with Cyprus Police; applicants with any criminal record (even minor offences from another jurisdiction) should take legal advice before applying. Application fee is approximately €200 per adult. The Long-Term Resident permit is a single-status permit covering the primary applicant and their registered dependents.",
      },
      {
        heading: "Rights versus citizenship — what the Long-Term Permit gives you",
        body: "The Long-Term Resident permit is permanent in the sense that it does not have an expiry date (though it must be renewed after five years to confirm continued residence status), and it cannot be revoked simply because you choose to be absent from Cyprus for a period (unlike the investment PR, which requires at least one entry every two years). Rights under the Long-Term Resident permit: right to work in Cyprus in any sector without a separate work permit; right to access social security and social assistance on the same terms as Cypriot citizens; right to access education and vocational training on equal terms; and the right to move freely within Cyprus. The permit does not give you EU free movement rights — you cannot move to Germany or France and work there on a Cyprus Long-Term Resident permit; for that you need citizenship. Naturalisation (Cypriot citizenship) requires seven years of continuous residence, with most of those years spent physically in Cyprus, a Greek language test at B1, a Cyprus history and culture test, and evidence of integration. The Long-Term Resident permit starts the clock toward citizenship but does not replace it. As a practical note: Cyprus citizenship confers full EU rights, including freedom of movement and work across all 27 EU member states, which is the primary reason many long-term residents pursue naturalisation.",
      },
    ],
  },
  {
    slug: "company-formation-visa",
    title: "Forming a Cyprus Company to Enable Residency — What You Need to Know",
    description:
      "Which visa categories require a Cyprus entity, minimum substance requirements, company formation steps, typical costs, and common pitfalls. Prices and rules change — verify with official Cyprus sources before acting.",
    sections: [
      {
        heading: "Which visa categories require a Cyprus company",
        body: "Not all residency routes require a Cyprus-registered company — the Digital Nomad Visa, for example, is explicitly designed for people who work for foreign entities and requires the absence of Cypriot employment. However, several other residency categories do require or strongly benefit from a Cyprus company. The most common: the Category F (Permanent Residency by Investment) sometimes requires a Cyprus company for applicants whose income comes from their own business, as the qualifying income must be demonstrably foreign-sourced and a Cyprus holding company can structure that cleanly; the employment permit (Category E), where a non-EU national employed by a Cyprus-registered company applies for a work permit tied to that entity; the self-employed permit, where an individual establishes a Cyprus company in which they hold a director or executive role; and the 60-day tax residency rule, which requires the applicant to 'carry on business or hold an office in a Cyprus-resident company'. The last is perhaps the most common reason entrepreneurs form a Cyprus company: to qualify as a Cyprus tax resident under the 60-day test while spending only a portion of each year physically in Cyprus.",
      },
      {
        heading: "Minimum substance requirements",
        body: "A Cyprus company used to support a residency application or tax residency claim must have genuine economic substance in Cyprus. The Cyprus Tax Department has tightened scrutiny on substance since 2022, and a shell company with a registered address but no real activity will not satisfy either the immigration or the tax authorities. Minimum substance requirements that are consistently applied: a physical office in Cyprus (a real lease, not just a registered address service — the distinction is checked); at least one full-time employee based in Cyprus, typically a local hire (this can be an office administrator or a part-time bookkeeper, but it must be a real employment relationship with social insurance contributions filed); the company's management and control must be exercised from Cyprus — the majority of board decisions should be documented as made in Cyprus, and the company's books and records should be maintained in Cyprus; and bank accounts and financial flows should run through Cyprus where commercially appropriate. The level of substance required scales with the tax and immigration benefit being claimed: a company supporting only a work permit needs less substance than one being used to establish 60-day tax residency.",
      },
      {
        heading: "Company formation steps",
        body: "Forming a private limited company (Ltd) in Cyprus is a straightforward process handled through the Registrar of Companies. The steps: choose a company name and confirm availability (the Registrar's online portal allows name checks); engage a Cyprus lawyer or licensed service provider to prepare the Memorandum and Articles of Association; file the incorporation documents with the Registrar of Companies (form HE1 for the shareholders, form HE2 for the registered address, form HE3 for the directors); register with the Tax Department for corporation tax and, if applicable, VAT (VAT registration is required if turnover exceeds €15,600 per year); open a corporate bank account (the hardest step for new companies — allow 4–8 weeks); and, if you will be employing staff, register as an employer with the Social Insurance Services. The Registrar typically issues the Certificate of Incorporation within 5–10 working days for standard applications. The total timeline from instructing a lawyer to having a functioning company with a bank account is typically 6–10 weeks.",
      },
      {
        heading: "Typical costs",
        body: "Company formation costs in Cyprus are competitive by EU standards. Government filing fees: approximately €200–€350 for a standard private company. Lawyer or service provider fees for incorporation: €800–€2,000 depending on complexity and the scope of services (some packages include company secretarial services for the first year, others do not). Registered office address (if you are using a service address rather than a leased office): €500–€1,500 per year. Nominee director services (if required to establish a Cypriot resident director): €1,000–€3,000 per year — these are legal and commonly used, but note that nominee directors must have access to company records and sign documents; choose a reputable provider. Annual accounting and audit: €800–€2,500 per year for a small dormant or low-activity company, more for active trading entities. Annual company maintenance (filing annual returns with the Registrar, preparing statutory accounts, filing with the Tax Department): included in most full-service packages at €1,000–€3,500 per year. Total cost of ownership for a straightforward single-purpose Cyprus company in the first year, including all of the above: €4,000–€8,000. Budget the same for each subsequent year.",
      },
      {
        heading: "Common pitfalls",
        body: "The most common mistakes Cyprus company formation for residency purposes: using a virtual office address for substance purposes — immigration and tax officers have become adept at identifying virtual office addresses from the postcode and building name, and these will not withstand scrutiny. Failing to open a real bank account — a company without a CY-IBAN cannot pay salaries, file VAT, or demonstrate actual trading; some applicants try to run the company through a Revolut Business or Wise Business account, which does not satisfy the banks or the tax authority. Under-capitalising the company — the company needs to have enough share capital and working capital to be credible; a company incorporated with €1,000 share capital and showing no bank activity will raise questions at any substantive review. Not filing annual accounts on time — Cyprus companies must file audited accounts with the Registrar within 18 months of incorporation and annually thereafter; late filings incur penalties and can lead to the company being struck off. Finally, using the same nominee director and registered address as dozens of other companies — the Tax Department maintains lists of common substance arrangements used purely for tax registration purposes, and applications relying heavily on shared-resource providers are subject to heightened review.",
      },
    ],
  },
  {
    slug: "new-development-buying-guide",
    title: "Buying a New Development in Cyprus — From Reservation to Title Deed",
    description:
      "The reservation process, signing the contract of sale, VAT on new builds, the Land Registry deposit requirement, title deed transfer timelines, and the snagging process. Prices and rules change — verify with official Cyprus sources before acting.",
    sections: [
      {
        heading: "The reservation process",
        body: "Buying a new development in Cyprus begins with a reservation — a payment (typically €2,000–€10,000 depending on the property price) that takes the unit off the market while the Contract of Sale is prepared. The reservation fee is usually refundable if the parties fail to agree final contract terms, but this should be explicitly stated in writing. Do not pay a reservation fee without a written receipt that confirms the property description (block, floor, unit number), the agreed price, the payment schedule, and the refund conditions. Reservation payments in Cyprus are almost always made in cash or by bank transfer to the developer directly; resist any request to pay to an individual rather than the company's official account. The reservation period is typically 7–21 days — the developer holds the unit for you while your lawyer reviews the contract. Use this window productively: appoint your lawyer on the same day you pay the reservation, give them the developer's draft contract immediately, and ask them to complete their review within the reservation period. Rushing the legal review to avoid losing the reservation is one of the most common ways buyers skip protections they later regret.",
      },
      {
        heading: "Signing the Contract of Sale",
        body: "The Contract of Sale is the primary legal document governing the purchase. Cyprus law (the Sale of Land (Specific Performance) Law, Cap. 232) requires the contract to be signed and deposited with the Department of Lands and Surveys within 60 days of execution. This deposit creates a specific performance right in your favour — it means the developer cannot sell the same unit to someone else or mortgage it again without your knowledge. Before signing, your lawyer should confirm: the title of the land on which the development is built is unencumbered or that the developer's mortgage will be discharged prior to completion; the planning permission and building permit are valid and in force; the payment schedule is linked to construction milestones (slab completion, shell completion, internal fit-out, final handover) rather than calendar dates that the developer can shift; penalties for delay are included; and the developer is obliged to apply for and deliver an individual title deed within a defined period after the Certificate of Final Approval is issued. Review the floor plan annexed to the contract and confirm it matches what you were shown — any deviation between the contracted plan and the built unit gives you a legal remedy only if the plan is clearly specified in the contract.",
      },
      {
        heading: "VAT on new developments",
        body: "VAT applies to the first sale of new residential properties in Cyprus. The standard rate is 19%, but a reduced rate of 5% applies to buyers who qualify under the primary residence scheme. To qualify for the 5% rate, you must be an individual (not a company), the property must be your primary and permanent residence in Cyprus, the property must not exceed 200 square metres of covered area (with the reduced rate applying to the first 130 square metres and the standard 19% rate applying above that within the same property), you must not have used the 5% scheme for another property in Cyprus in the preceding 10 years, and you must declare your intention to use the property as a primary residence and actually do so for at least 10 years after completion. The 5% eligibility must be confirmed and applied for before or at contract signing — it cannot be applied retrospectively after you have been charged 19%. If you purchase through a company, or you are not eligible for the reduced rate for any reason, VAT at 19% applies to the full purchase price. VAT-registered property purchases can also sometimes result in a VAT refund for the developer, which they may or may not pass through to buyers; clarify this in the contract.",
      },
      {
        heading: "Land Registry deposit and transfer fees",
        body: "After the Contract of Sale is signed, it must be stamped (stamp duty: 0.15% on the first €170,860 of the price, 0.2% above that) and deposited at the DLS within 60 days. The stamp duty must be paid before deposit — unpaid contracts incur penalties. The deposit registers your interest against the title and is the buyer's primary protection from double-selling or developer encumbrance. At the time of title deed transfer, transfer fees are calculated on the DLS's assessed market value (not necessarily the contract price, though the two are typically close for new builds). Transfer fee rates: 3% on the first €85,000 of value, 5% on €85,001–€170,000, 8% above €170,000. A 50% discount on transfer fees has historically applied to transfers directly from developers; confirm the current discount with your lawyer as this has been modified by legislation several times. For VAT-registered new build purchases, no transfer fees are payable — VAT and transfer fees are mutually exclusive in Cyprus tax law. Budget carefully: on a €400,000 property, transfer fees at full rate would be approximately €18,450; at the 50% discount, approximately €9,225.",
      },
      {
        heading: "Title deed timeline and snagging",
        body: "For a new build completed today, the realistic timeline from completion to individual title deed in your name is 3–5 years. This is not unusual by Cyprus standards: the developer must first obtain the Certificate of Final Approval from the planning authority (a process that typically takes 6–18 months and requires the building to match the approved plans), then apply to the DLS to subdivide the plot and register individual unit titles (typically a further 1–3 years). You can often obtain your title deed faster than average if your contract includes penalties for developer delay in applying for each step — follow up with your lawyer every six months on the status. Snagging (the process of identifying and documenting defects at handover) is critically important in Cyprus because the legal window to require remediation under warranty is narrow. At key handover, conduct a full inspection with a snag list before you sign the handover documents — do not sign anything confirming satisfactory completion until every snagged item is either fixed or documented in writing with a specific remediation deadline. Common snag items in Cyprus new builds: waterproofing on terraces and balconies (the most expensive to fix post-handover), tile alignment, door and window sealing, electrical labelling, and air-conditioning unit commissioning. Retain the last 5–10% of the purchase price contractually until all snagging items are resolved.",
      },
    ],
  },
];
