import { CITIES } from "./cyprusData";
import visibleListings from "./data/listings.visible.json";
import { placeListing } from "./listingRegion";

export type Offer = {
	unit?: string;
	title?: string;
	price?: string | null;
	"price per m²"?: string | null;
	pricePerM2?: string | null;
	bedrooms?: string | null;
	bathrooms?: string | null;
	"living area"?: string | null;
	"plot/land"?: string | null;
	floor?: string | null;
	parking?: string | null;
	note?: string | null;
	description?: string | null;
	features?: Record<string, string>;
};

export type ImageGallery = {
	title: string;
	images: string[];
};

export type Listing = {
	title: string;
	id: number;
	slug: string;
	url: string | null;
	priceRange: string | null;
	pricePerM2: string | null;
	location: string | null;
	lat: number;
	lng: number;
	logo?: string | null;
	headerImage?: string | null;
	images?: string[];
	imageGalleries?: ImageGallery[];
	developer: {
		name?: string;
		address?: string;
		logo?: string;
		url_slug?: string;
		description?: string;
	} | null;
	agents:
		| string[]
		| Array<{ name?: string; logo?: string; contacts?: unknown }>;
	specs: Record<string, string>;
	features: string[];
	offers: Offer[];
	nearby: Record<string, string>;
	brochures: string[] | Array<{ name?: string; url?: string }>;
	description: string | null;
	videoUrl?: string | null;
	contacts?: {
		phone?: string[];
		whatsapp?: string;
		email?: string;
	};
};

export type EnrichedListing = Listing & {
	regionCity: string;
	/** [x, z] in three.js scene space. */
	scenePos: readonly [number, number];
};

/**
 * Owner rule: Nicosia is intentionally excluded from RealCy.app. Listings
 * classified into a hidden classifier city (lib/cyprusData.ts
 * HIDDEN_CLASSIFIER_CITIES) are kept in lib/data/listings.json (reversible)
 * but hidden from every page. This module imports only
 * lib/data/listings.visible.json (generated by scripts/gen-visible-listings.mjs,
 * checked at build by lib/listings.ts), so hidden records never reach a client
 * bundle. LISTINGS, LISTINGS_BY_REGION, developers, the sitemap, static params
 * and every tool all derive from LISTINGS below.
 */
export const LISTINGS: EnrichedListing[] = (
	visibleListings as unknown as Listing[]
).map((l) => ({ ...l, ...placeListing(l.lng, l.lat) }));

export const LISTINGS_BY_REGION: Record<string, EnrichedListing[]> = (() => {
	const m: Record<string, EnrichedListing[]> = {};
	for (const c of CITIES) m[c.name] = [];
	for (const l of LISTINGS) {
		if (!m[l.regionCity]) m[l.regionCity] = [];
		m[l.regionCity].push(l);
	}
	return m;
})();
